const ABILITIES=["歌藝","演技","舞蹈","主持","聲線","鏡頭感","肢體表現","創作","作詞","作曲","編劇","樂器","靈感","外貌","氣質","時尚","儀態","親和力","口才","社交","學識"];
const ACTIONS={
  vocal:{group:"訓練中心",label:"聲樂基礎課",note:"歌藝為主，聲線為輔",type:"train",gains:[["歌藝",4,8],["聲線",1,3]],fatigue:8},
  acting:{group:"訓練中心",label:"新人表演課",note:"演技、鏡頭感與肢體表現",type:"train",gains:[["演技",4,8],["鏡頭感",1,3],["肢體表現",1,2]],fatigue:9},
  dance:{group:"訓練中心",label:"舞蹈基礎課",note:"舞蹈為主，肢體表現為輔",type:"train",gains:[["舞蹈",4,8],["肢體表現",1,3]],fatigue:11},
  speech:{group:"訓練中心",label:"主持口條課",note:"口才為主，主持為輔",type:"train",gains:[["口才",4,8],["主持",1,3]],fatigue:7},
  creation:{group:"訓練中心",label:"創意開發課",note:"創作與靈感訓練",type:"train",gains:[["創作",4,8],["靈感",1,3]],fatigue:7},
  songwriting:{group:"訓練中心",label:"詞曲創作課",note:"作詞、作曲與樂器",type:"train",gains:[["作詞",3,7],["作曲",3,7],["樂器",1,3]],fatigue:9},
  script:{group:"訓練中心",label:"劇本寫作課",note:"編劇為主，學識為輔",type:"train",gains:[["編劇",4,8],["學識",1,3]],fatigue:7},
  image:{group:"訓練中心",label:"形象儀態課",note:"氣質、儀態與親和力",type:"train",gains:[["氣質",3,6],["儀態",3,6],["親和力",1,3]],fatigue:6},
  networking:{group:"訓練中心",label:"社交應對課",note:"社交與親和力訓練",type:"train",gains:[["社交",4,8],["親和力",1,3]],fatigue:6},
  audition:{group:"工作機會",label:"新人廣告試鏡",note:"新人級；鏡頭感、親和力、口才",type:"work",fatigue:13},
  street:{group:"工作機會",label:"街頭演出",note:"累積經驗與被發掘的機會",type:"work",fatigue:12},
  free:{group:"生活安排",label:"自由活動",note:"探索城市，可能認識新人物",type:"life",fatigue:3},
  styling:{group:"生活安排",label:"造型研究",note:"提升時尚與外貌管理",type:"life",gains:[["時尚",3,6],["外貌",1,2]],fatigue:3},
  study:{group:"生活安排",label:"在家研究",note:"提升學識與創作靈感",type:"life",gains:[["學識",3,6],["靈感",1,2]],fatigue:2},
  rest:{group:"生活安排",label:"在家休息",note:"恢復體力並降低疲勞",type:"rest",fatigue:-18}
};
const DAYS=["星期一","星期二","星期三","星期四","星期五","星期六","星期日"];
let state={screen:"create",name:"",gender:"女性",customGender:"",stats:{},week:1,schedule:["vocal","acting","rest","speech","free","dance","rest"],lastSchedule:null,selectedAction:"vocal",stamina:100,fatigue:0,mood:70,knownPeople:[],runnerDay:0,runnerResult:null,weekResults:[],plannerNotice:""};
const app=document.querySelector("#app");
const random=(min,max)=>Math.floor(Math.random()*(max-min+1))+min;
const escapeHtml=(value)=>String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function rollStats(){state.stats=Object.fromEntries(ABILITIES.map(name=>[name,random(0,150)]));render()}
function render(){app.innerHTML=state.screen==="create"?createView():gameView();bind()}
function createView(){return `<main class="create-page"><header class="topbar"><div class="logo"><b>★</b>星途未定</div><span>五年娛樂圈成長模擬</span></header><section class="create-layout"><div class="create-intro"><p class="eyebrow">YEAR 1 · AGE 18</p><h1>還沒成名，<br>先決定你是誰。</h1><p>每一項能力都從同一條起跑線擲出。沒有預設職業、沒有天選主角；骰到你滿意，再帶著這組能力踏進星望市。</p></div><div class="create-card"><div class="identity-row"><div class="field"><label for="player-name">姓名</label><input id="player-name" maxlength="16" placeholder="輸入本名或藝名" value="${escapeHtml(state.name)}"></div><div class="field"><label for="gender">性別</label><select id="gender"><option>女性</option><option>男性</option><option>非二元</option><option>自訂</option></select><input id="custom-gender" class="custom-gender hidden" maxlength="20" placeholder="輸入性別描述" value="${escapeHtml(state.customGender)}"></div></div><div class="roll-head"><div><p class="eyebrow">INITIAL ABILITIES</p><h2>初始能力</h2><p>全部可訓練能力固定出現；每項獨立隨機 0～150，重骰不限次數。</p></div><button class="btn secondary" id="reroll">↻ 再骰一次</button></div><div class="ability-scroll">${ABILITIES.map(name=>`<div class="ability-row"><span>${name}</span><strong>${state.stats[name]}</strong><div class="bar" title="${state.stats[name]} / 1000"><i style="width:${state.stats[name]/10}%"></i></div></div>`).join("")}</div><div class="scale-note"><span>0｜毫無經驗</span><span>目前最多只會到整條的 15%</span><span>1000｜理論極限</span></div><button class="btn coral start-btn" id="start" ${state.name.trim()?"":"disabled"}>帶著這組能力出發 →</button></div></section></main>`}
function palette(){const groups=["訓練中心","工作機會","生活安排"];return `<aside class="action-palette"><h3>可安排事項</h3><p>先選一項活動，再點右側日期。行程可以反覆修改，確認後才會正式執行。</p><div class="action-groups">${groups.map(group=>`<section class="action-group"><div class="action-group-title">${group}</div>${Object.entries(ACTIONS).filter(([,a])=>a.group===group).map(([id,a])=>`<button class="action-option ${state.selectedAction===id?"active":""}" data-action="${id}"><b>${a.label}</b><small>${a.note}</small></button>`).join("")}</section>`).join("")}</div></aside>`}
function gameView(){return `<main class="game-page"><header class="topbar"><div class="logo"><b>★</b>星途未定</div><div class="game-top-info">第一年・第 ${state.week} 週<span>18 歲</span></div></header><div class="game-layout"><aside class="profile"><div class="portrait"><span>${escapeHtml(state.name.slice(0,1))}</span></div><p class="eyebrow">未簽約新人</p><h2>${escapeHtml(state.name)}</h2><div class="profile-line">18 歲 · ${escapeHtml(state.gender)}</div><div class="status"><div class="status-item"><div><span>體力</span><b>${state.stamina}</b></div><div class="bar"><i style="width:${state.stamina}%"></i></div></div><div class="status-item fatigue"><div><span>疲勞</span><b>${state.fatigue}</b></div><div class="bar"><i style="width:${Math.min(state.fatigue,100)}%"></i></div></div></div><div class="people"><h3>已認識人物</h3>${state.knownPeople.length?state.knownPeople.map(p=>`<div class="empty-people">${p}</div>`).join(""):`<div class="empty-people">目前還沒有認識任何人。<br>第一輪的人脈，要靠你自己遇見。</div>`}</div></aside><section class="workspace"><div class="workspace-head"><div><p class="eyebrow">WEEKLY CALENDAR</p><h1>安排第 ${state.week} 週行程</h1></div><div class="workspace-actions"><button class="btn secondary" id="copy" ${state.lastSchedule?"":"disabled"}>複製上週</button><button class="btn secondary" id="clear">全部休息</button></div></div><div class="opportunity"><div><span>本週通告</span><b>新人飲料廣告試鏡</b><small>期限：本週內｜新人級｜鏡頭感、親和力、口才</small></div><button class="btn secondary" id="quick-audition">一鍵排定</button></div>${state.plannerNotice?`<div class="planner-notice">${escapeHtml(state.plannerNotice)}</div>`:""}<div class="planner-shell">${palette()}<div><section class="calendar"><div class="calendar-title"><h3>星望市行事曆</h3><span>點日期排入「${ACTIONS[state.selectedAction].label}」</span></div><div class="weekdays">${DAYS.map(d=>`<div>${d}</div>`).join("")}</div><div class="calendar-grid">${DAYS.map((day,i)=>{const a=ACTIONS[state.schedule[i]];return `<button class="calendar-day" data-day="${i}"><span class="date">${i+1}</span><span class="weekday">${day}</span><div class="event-card ${a.type}"><b>${a.label}</b><p>${a.note}</p></div><span class="change">點一下更換行程</span></button>`}).join("")}</div><div class="calendar-help">目前採一天一項主要行程；多日通告與違約期限將在後續版本加入。</div></section><button class="btn coral begin-week" id="begin-week">確認行程，從星期一開始 →</button>${state.weekResults.length?`<div class="week-log"><h3>上一週紀錄</h3>${state.weekResults.map(x=>`<p>${x}</p>`).join("")}</div>`:""}</div></div></section></div>${state.screen==="runner"?runnerView():""}</main>`}
function runnerView(){const index=state.runnerDay;const action=ACTIONS[state.schedule[index]];return `<div class="runner"><section class="runner-card"><div class="runner-progress">${DAYS.map((_,i)=>`<i class="${i<=index?"done":""}"></i>`).join("")}</div><div class="runner-body"><div class="day-kicker">DAY ${index+1} · ${DAYS[index]}</div><h2>${index===0?"第一天":`第 ${index+1} 天`}</h2><div class="runner-action"><b>${action.label}</b><p>${action.note}</p></div>${state.runnerResult?`<div class="result-box"><h3>${state.runnerResult.title}</h3><p>${state.runnerResult.text}</p></div>`:`<div class="result-box pending"><h3>行程尚未執行</h3><p>按下按鈕，看看今天的努力會得到什麼結果。</p></div>`}<div class="runner-buttons">${state.runnerResult?`<button class="btn coral" id="next-day">${index===6?"完成本週結算":"前往下一天 →"}</button>`:`<button class="btn coral" id="run-day">執行本日行程</button>`}</div></div></section></div>`}
function applyGains(gains){return gains.map(([stat,min,max])=>{const gain=random(min,max);state.stats[stat]=Math.min(1000,state.stats[stat]+gain);return `${stat}＋${gain}`}).join("、")}
function performDay(){const id=state.schedule[state.runnerDay],a=ACTIONS[id];let title="成功！",text="";if(a.type==="train"){const summary=applyGains(a.gains);text=`${summary}。老師記住了你今天的進步。`;state.stamina=Math.max(0,state.stamina-a.fatigue);state.fatigue+=a.fatigue}else if(id==="rest"){title="好好休息！";const reduced=Math.min(state.fatigue,18);state.fatigue-=reduced;state.stamina=Math.min(100,state.stamina+24);text=`體力恢復，疲勞－${reduced}。今天沒有偷懶，是策略性躺平。`}else if(id==="free"){state.fatigue+=3;state.stamina=Math.max(0,state.stamina-4);if(!state.knownPeople.some(person=>person.startsWith("紀晴"))&&Math.random()<.65){state.knownPeople.push("紀晴｜廣播節目主持人");text="你在廣播電臺附近幫忙撿回散落的資料，第一次認識了主持人紀晴。"}else text="你走訪商圈與藝文中心，累積了一點對星望市的熟悉度。"}else if(a.gains){const summary=applyGains(a.gains);state.fatigue+=a.fatigue;state.stamina=Math.max(0,state.stamina-Math.max(2,a.fatigue));text=`${summary}。今天的自主安排有好好留下成果。`}else{state.fatigue+=a.fatigue;state.stamina=Math.max(0,state.stamina-a.fatigue);const power=id==="audition"?(state.stats.鏡頭感+state.stats.親和力+state.stats.口才)/3:(state.stats.歌藝+state.stats.肢體表現)/2;const chance=Math.max(8,Math.min(70,25+(power-75)*.22));if(Math.random()*100<chance){const stat=id==="audition"?"鏡頭感":"歌藝",gain=random(5,9);state.stats[stat]=Math.min(1000,state.stats[stat]+gain);text=`${id==="audition"?"獲得複試機會":"路人停下腳步替你鼓掌"}，${stat}＋${gain}。`}else{title="沒有成功……但不是白費！";const stat=id==="audition"?"鏡頭感":"歌藝",gain=random(1,3);state.stats[stat]=Math.min(1000,state.stats[stat]+gain);text=`這次沒有得到機會，${stat}仍因實戰經驗＋${gain}。`}}state.runnerResult={title,text};state.weekResults.push(`${DAYS[state.runnerDay]}｜${a.label}：${title} ${text}`);render()}
function bind(){if(state.screen==="create"){const name=document.querySelector("#player-name"),gender=document.querySelector("#gender"),custom=document.querySelector("#custom-gender");gender.value=["女性","男性","非二元"].includes(state.gender)?state.gender:"自訂";custom.classList.toggle("hidden",gender.value!=="自訂");name.addEventListener("input",e=>{state.name=e.target.value;document.querySelector("#start").disabled=!state.name.trim()});gender.addEventListener("change",e=>{state.gender=e.target.value;custom.classList.toggle("hidden",e.target.value!=="自訂")});custom.addEventListener("input",e=>state.customGender=e.target.value);document.querySelector("#reroll").onclick=rollStats;document.querySelector("#start").onclick=()=>{if(!state.name.trim())return;if(state.gender==="自訂")state.gender=state.customGender.trim()||"未標示";state.screen="game";render()};return}document.querySelectorAll("[data-action]").forEach(el=>el.onclick=()=>{state.selectedAction=el.dataset.action;render()});document.querySelectorAll("[data-day]").forEach(el=>el.onclick=()=>{const index=Number(el.dataset.day);state.schedule[index]=state.selectedAction;state.plannerNotice=`已將「${ACTIONS[state.selectedAction].label}」排入${DAYS[index]}。`;render()});document.querySelector("#quick-audition")?.addEventListener("click",()=>{let index=state.schedule.findIndex(id=>id==="rest");if(index<0)index=state.schedule.findIndex(id=>id==="free");if(index<0)index=6;state.schedule[index]="audition";state.plannerNotice=`通告已一鍵排入${DAYS[index]}。`;render()});document.querySelector("#copy")?.addEventListener("click",()=>{if(state.lastSchedule){state.schedule=[...state.lastSchedule];state.plannerNotice="已複製上週行程。";render()}});document.querySelector("#clear")?.addEventListener("click",()=>{state.schedule=Array(7).fill("rest");state.plannerNotice="本週已全部改為在家休息。";render()});document.querySelector("#begin-week")?.addEventListener("click",()=>{state.lastSchedule=[...state.schedule];state.runnerDay=0;state.runnerResult=null;state.weekResults=[];state.plannerNotice="";state.screen="runner";render()});document.querySelector("#run-day")?.addEventListener("click",performDay);document.querySelector("#next-day")?.addEventListener("click",()=>{if(state.runnerDay===6){state.week++;state.screen="game"}else{state.runnerDay++;state.runnerResult=null}render()})}
rollStats();
