const ABILITY_GROUPS={"表演":["歌藝","演技","舞蹈","主持","聲線","鏡頭感","肢體表現"],"創作":["創作","作詞","作曲","編劇","樂器","靈感"],"形象":["外貌","氣質","時尚","儀態","親和力"],"社交與知識":["口才","社交","學識"]};
const ABILITIES=Object.values(ABILITY_GROUPS).flat();
const ACTIONS={
vocal:{group:"訓練",icon:"♫",label:"聲樂基礎課",short:"聲樂課",note:"歌藝為主，聲線為輔",type:"train",gains:[["歌藝",4,8],["聲線",1,3]],fatigue:8,stamina:8,cost:800},
acting:{group:"訓練",icon:"🎬",label:"新人表演課",short:"表演課",note:"演技、鏡頭感與肢體表現",type:"train",gains:[["演技",4,8],["鏡頭感",1,3],["肢體表現",1,2]],fatigue:9,stamina:9,cost:900},
dance:{group:"訓練",icon:"♬",label:"舞蹈基礎課",short:"舞蹈課",note:"舞蹈為主，肢體表現為輔",type:"train",gains:[["舞蹈",4,8],["肢體表現",1,3]],fatigue:11,stamina:11,cost:1000},
speech:{group:"訓練",icon:"🎙",label:"主持口條課",short:"口條課",note:"口才為主，主持為輔",type:"train",gains:[["口才",4,8],["主持",1,3]],fatigue:7,stamina:7,cost:700},
creation:{group:"訓練",icon:"✦",label:"創意開發課",short:"創意課",note:"創作與靈感訓練",type:"train",gains:[["創作",4,8],["靈感",1,3]],fatigue:7,stamina:7,cost:650},
songwriting:{group:"訓練",icon:"🎼",label:"詞曲創作課",short:"詞曲課",note:"作詞、作曲與樂器",type:"train",gains:[["作詞",3,7],["作曲",3,7],["樂器",1,3]],fatigue:9,stamina:9,cost:950},
script:{group:"訓練",icon:"✎",label:"劇本寫作課",short:"編劇課",note:"編劇為主，學識為輔",type:"train",gains:[["編劇",4,8],["學識",1,3]],fatigue:7,stamina:7,cost:650},
image:{group:"訓練",icon:"◇",label:"形象儀態課",short:"儀態課",note:"氣質、儀態與親和力",type:"train",gains:[["氣質",3,6],["儀態",3,6],["親和力",1,3]],fatigue:6,stamina:6,cost:750},
networking:{group:"訓練",icon:"☕",label:"社交應對課",short:"社交課",note:"社交與親和力訓練",type:"train",gains:[["社交",4,8],["親和力",1,3]],fatigue:6,stamina:6,cost:500},
audition:{group:"工作",icon:"★",label:"新人廣告試鏡",short:"廣告試鏡",note:"鏡頭感、親和力與口才",type:"work",fatigue:13,stamina:13,cost:300},
adshoot:{group:"工作",icon:"🎥",label:"晨露汽水廣告拍攝",short:"廣告拍攝",note:"合約通告・共需完成 3 次拍攝",type:"job",fatigue:18,stamina:18,cost:0},
street:{group:"工作",icon:"🎸",label:"街頭演出",short:"街頭演出",note:"賺取小費並累積實戰曝光",type:"work",fatigue:12,stamina:12,cost:0},
free:{group:"生活",icon:"☀",label:"自由活動",short:"自由活動",note:"探索星望市，可能遇見新人物",type:"life",fatigue:3,stamina:4,cost:300},
styling:{group:"生活",icon:"✧",label:"造型研究",short:"造型研究",note:"提升時尚與外貌管理",type:"life",gains:[["時尚",3,6],["外貌",1,2]],fatigue:3,stamina:3,cost:600},
study:{group:"生活",icon:"📖",label:"在家研究",short:"在家研究",note:"提升學識與創作靈感",type:"life",gains:[["學識",3,6],["靈感",1,2]],fatigue:2,stamina:2,cost:0},
rest:{group:"休息",icon:"☁",label:"在家休息",short:"休息",note:"恢復體力並降低疲勞",type:"rest",fatigue:-18,stamina:-24,cost:0}
};
const DAYS=["星期一","星期二","星期三","星期四","星期五","星期六","星期日"],SHORT=["一","二","三","四","五","六","日"];
const FOCUSES={growth:{icon:"✦",label:"能力成長",note:"本週所有能力成長額外＋1"},fame:{icon:"★",label:"增加曝光",note:"工作成功率與知名度收益提高"},people:{icon:"♡",label:"拓展人脈",note:"遇見新人物與建立關係的機會提高"}};
const NPCS={jiqing:{name:"紀晴",job:"廣播節目主持人",location:"星望廣播電臺",bio:"星望廣播電臺節目主持人。反應快、待人親切，對有潛力的新人很敏銳。",avatar:"紀"}};
const JOB={brand:"晨露飲品",title:"晨露汽水形象廣告",tagline:"清爽校園感・平面與短影音廣告",pay:12000,sessions:3,workDays:[0,1,2],requirements:[["鏡頭感",60],["親和力",50],["口才",40]]};
let state={screen:"create",createStep:1,tab:"planner",appOpen:null,name:"",gender:"女性",customGender:"",stats:{},week:1,schedule:["vocal","acting","rest","audition","free","dance","rest"],lastSchedule:null,selectedDay:0,filter:"全部",focus:"growth",stamina:100,fatigue:0,mood:70,money:18000,fame:0,fans:0,contract:8,knownPeople:[],runnerDay:0,runnerPhase:"",runnerResult:null,runnerDecision:null,weekResults:[],history:[],notice:"",drawerOpen:false,reward:null,mapLocation:null,jobStage:"available",jobRemaining:3,jobDeadline:3,jobNotice:"",selectedNpc:null};
const app=document.querySelector("#app"),random=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const money=n=>`$${Math.max(0,n).toLocaleString("zh-TW")}`;
const width=n=>Math.max(.35,Math.min(100,n/10));
function rollStats(){state.stats=Object.fromEntries(ABILITIES.map(n=>[n,random(0,150)]));render()}
function render(){app.innerHTML=state.screen==="create"?createView():state.screen==="runner"?runnerView():state.screen==="summary"?summaryView():roomView();bind()}

function createView(){const best=Object.entries(state.stats).sort((a,b)=>b[1]-a[1]).slice(0,3);return `<main class="create-screen"><section class="create-art"><div class="logo">✦ 星途未定</div><img src="./assets/new-start-box.webp" alt="裝著表演用品的搬家紙箱"><div class="opening-copy"><span>序章｜18 歲的夏天</span><h1>帶著一箱夢想，<br>住進星望市。</h1><p>五年時間。沒有公司、沒有作品、沒有人脈。妳的明星人生，從這間小房間開始。</p></div></section><section class="create-form">${state.createStep===1?identityStep():statsStep(best)}</section></main>`}
function identityStep(){return `<div class="form-card"><div class="step-mark">STEP 1 / 2</div><h2>這位新人叫什麼名字？</h2><p>姓名與性別只影響稱呼和劇情，不會限制發展路線。</p><label><span>姓名／藝名</span><input id="player-name" maxlength="16" placeholder="輸入名字" value="${esc(state.name)}"></label><fieldset><legend>性別</legend><div class="gender-options">${["女性","男性","非二元","自訂"].map(g=>`<button class="${(g==="自訂"?!["女性","男性","非二元"].includes(state.gender):state.gender===g)?"active":""}" data-gender="${g}">${g}</button>`).join("")}</div></fieldset><label class="${["女性","男性","非二元"].includes(state.gender)?"hidden":""}"><span>自訂性別</span><input id="custom-gender" maxlength="20" value="${esc(state.customGender)}" placeholder="自由輸入"></label><button class="main-btn full" id="to-stats" ${state.name.trim()?"":"disabled"}>看看我的初始天賦 →</button></div>`}
function statsStep(best){return `<div class="form-card wide"><div class="roll-title"><div><div class="step-mark">STEP 2 / 2</div><h2>命運發了這副牌</h2><p>21 項固定能力各自隨機 0～150；不喜歡就無限重骰。</p></div><button class="reroll" id="reroll">↻ 全部重骰</button></div><div class="best-tags">${best.map(([n,v],i)=>`<span>天賦 ${i+1}<b>${n} ${v}</b></span>`).join("")}<em>能力上限皆為 1000</em></div><div class="rolled-grid">${Object.entries(ABILITY_GROUPS).map(([group,names])=>`<section><h3>${group}</h3>${names.map(n=>`<div class="mini-stat"><span>${n}</span><i><b style="width:${width(state.stats[n])}%"></b></i><strong>${state.stats[n]}</strong></div>`).join("")}</section>`).join("")}</div><div class="form-actions"><button class="back-btn" id="back">← 修改身分</button><button class="main-btn" id="start">就用這組，搬進星望市 →</button></div></div>`}

function roomView(){return `<main class="room-screen"><img class="room-bg" src="./assets/rookie-room.webp" alt="新人租屋處的工作桌"><header class="room-hud"><div class="player-chip"><div>${esc(state.name.slice(0,1))}</div><span><b>${esc(state.name)}</b><small>18 歲・未簽約新人</small></span></div><div class="hud-stats"><span>💰 <b>${money(state.money)}</b></span><span>★ 知名度 <b>${state.fame}</b></span><span>♡ 粉絲 <b>${state.fans}</b></span><span>☁ 疲勞 <b>${state.fatigue}</b></span></div></header><button class="desk-pin phone-pin" data-open-app="people"><i>1</i><b>手機</b><small>${state.knownPeople.length?"查看聯絡人":"新的城市，空白通訊錄"}</small></button><button class="desk-pin mail-pin" data-open-job><i>!</i><b>通告信封</b><small>新人廣告試鏡・本週截止</small></button><section class="tablet"><div class="tablet-camera"></div><div class="tablet-screen">${tabletHome()}${tabletDock()}</div></section>${state.appOpen?appWindow():""}</main>`}
function tabletHome(){return `<div class="tablet-home"><header><span>第一年・第 ${state.week} 週</span><b>${esc(state.name)}，早安！</b><small>今天先從安排這一週開始吧。</small></header><div class="home-contract"><div><span>簽約準備度</span><b>${state.contract}%</b></div><i><b style="width:${state.contract}%"></b></i><small>${state.contract<35?"經紀公司還在觀望，先累積作品與曝光。":"開始有公司注意到妳了。"}</small></div><button class="next-action" data-open-app="planner"><span>下一步</span><b>安排第 ${state.week} 週行程</b><small>7 天尚未開始・預計支出 ${money(budget())}</small><i>→</i></button><div class="home-launchers"><button data-open-app="map"><b>⌖ 星望市地圖</b><small>選擇自由活動地點</small></button><button data-open-app="jobs"><b>▤ 通告中心</b><small>${state.jobStage==="available"?"1 份新邀約":state.jobStage==="active"?`剩餘 ${state.jobRemaining} 次拍攝`:"查看試鏡進度"}</small></button><button data-open-app="npc"><b>◈ 人物檔案</b><small>已認識人物的資料與關係</small></button></div></div>`}
function tabletDock(){return `<nav class="tablet-dock">${[["planner","▦","行程"],["stats","◫","能力"],["people","♡","人際"],["log","≡","紀錄"]].map(([id,icon,label])=>`<button data-open-app="${id}"><i>${icon}</i>${label}</button>`).join("")}</nav>`}
function appWindow(){const meta={planner:["▦","行程與工作","安排七天行程、策略與預算"],stats:["◫","能力資料","檢視 21 項能力與天賦"],people:["♡","手機與人際","查看聯絡人和關係進度"],log:["≡","星途紀錄","回顧每週成果與重大選擇"],map:["⌖","星望市地圖","選擇自由活動要前往的地點"],jobs:["▤","通告中心","接取邀約、參加試鏡與管理合約"],npc:["◈","人物檔案","已認識人物的資料與關係"]}[state.appOpen];const views={planner:plannerApp,stats:statsApp,people:peopleApp,log:logApp,map:mapApp,jobs:jobsApp,npc:npcApp};const body=views[state.appOpen]();return `<div class="app-backdrop" data-close-app></div><section class="app-window ${state.appOpen}"><header class="window-bar"><div class="window-icon">${meta[0]}</div><div><h2>${meta[1]}</h2><p>${meta[2]}</p></div>${state.appOpen==="planner"?`<button class="window-start" id="begin-week">開始這週 →</button>`:""}<button class="window-close" data-close-app aria-label="關閉">×</button></header><div class="window-body">${body}</div></section>`}

function budget(){return state.schedule.reduce((s,id)=>s+ACTIONS[id].cost,0)}
function forecastFatigue(){return state.schedule.reduce((s,id)=>Math.max(0,s+ACTIONS[id].fatigue),state.fatigue)}
function plannerApp(){const spend=budget(),fat=forecastFatigue(),train=state.schedule.filter(id=>ACTIONS[id].type==="train").length,work=state.schedule.filter(id=>["work","job"].includes(ACTIONS[id].type)).length;return `<div class="planner-app">${state.jobStage==="active"?`<button class="contract-alert" data-open-app="jobs"><span>進行中通告</span><b>晨露汽水形象廣告</b><strong>剩餘 ${state.jobRemaining} 次・第 ${state.jobDeadline} 週截止</strong><em>查看合約 →</em></button>`:""}<div class="week-brief"><div><span>本週任務</span><b>準備簽約面談</b><small>訓練 2 天＋工作 1 次＋週末疲勞 ≤ 60</small></div><strong>獎勵<br><b>$1,500・簽約＋10%</b></strong></div><div class="focus-row"><span>本週策略</span>${Object.entries(FOCUSES).map(([id,f])=>`<button class="${state.focus===id?"active":""}" data-focus="${id}" title="${f.note}">${f.icon} ${f.label}</button>`).join("")}</div><div class="calendar-head"><div><b>八月・第 ${state.week} 週</b><small>點一天打開行程選單</small></div><div><button id="copy" ${state.lastSchedule?"":"disabled"}>複製上週</button><button id="rest-all">全部休息</button></div></div><div class="ipad-calendar">${state.schedule.map((id,i)=>calendarDay(id,i)).join("")}</div><div class="week-check"><span>訓練 <b>${train}/2</b></span><span>工作 <b>${work}/1</b></span><span>預估疲勞 <b class="${fat>60?"bad":""}">${fat}</b></span><span>本週支出 <b class="${spend>state.money?"bad":""}">${money(spend)}</b></span><em>${spend>state.money?"預算不足，請調整行程":fat>60?"任務可能因疲勞過高而失敗":"本週任務條件可達成"}</em></div>${state.notice?`<div class="mini-toast">✓ ${esc(state.notice)}</div>`:""}${state.drawerOpen?activityDrawer():""}</div>`}
function calendarDay(id,i){const a=ACTIONS[id],freePlace=id==="free"&&state.mapLocation?MAP_LOCATIONS[state.mapLocation].name:null,dueDay=state.jobStage==="active"&&JOB.workDays.includes(i);return `<button class="calendar-cell ${state.selectedDay===i?"selected":""} ${dueDay?"due-day":""}" data-day="${i}" ${dueDay?`title="通告指定工作日"`:""}><span>${i+1}<small>週${SHORT[i]}</small></span><i class="${a.type}">${a.icon}</i><b>${freePlace||a.short}</b><em>${a.cost?money(a.cost):"免費"}${id==="adshoot"&&state.jobStage==="active"?`・剩 ${state.jobRemaining} 次`:""}</em></button>`}
function activityDrawer(){const entries=Object.entries(ACTIONS).filter(([id,a])=>(id!=="adshoot"||state.jobStage==="active")&&(state.filter==="全部"||a.group===state.filter));return `<div class="drawer-shade" data-close-drawer></div><aside class="activity-drawer"><header><div><span>正在安排</span><b>${DAYS[state.selectedDay]}</b></div><button data-close-drawer>×</button></header><nav>${["全部","訓練","工作","生活","休息"].map(f=>`<button class="${state.filter===f?"active":""}" data-filter="${f}">${f}</button>`).join("")}</nav><div class="drawer-list">${entries.map(([id,a])=>`<button class="${state.schedule[state.selectedDay]===id?"active":""}" data-pick="${id}"><i class="${a.type}">${a.icon}</i><span><b>${a.label}</b><small>${a.note}</small></span><em>${a.cost?money(a.cost):"免費"}<small>疲勞 ${a.fatigue>0?"+":""}${a.fatigue}</small></em></button>`).join("")}</div></aside>`}

function statsApp(){const best=Object.entries(state.stats).sort((a,b)=>b[1]-a[1]).slice(0,3);return `<div class="inside-page"><div class="inside-title"><div><span>ABILITIES</span><h2>能力與天賦</h2></div><p>目前最高：${best.map(([n,v])=>`${n} ${v}`).join("・")}</p></div><div class="stats-columns">${Object.entries(ABILITY_GROUPS).map(([g,names])=>`<section><h3>${g}</h3>${names.map(n=>`<div class="stat-row"><span>${n}</span><i><b style="width:${width(state.stats[n])}%"></b></i><strong>${state.stats[n]}<small>/1000</small></strong></div>`).join("")}</section>`).join("")}</div></div>`}
function peopleApp(){return `<div class="inside-page"><div class="inside-title"><div><span>CONTACTS</span><h2>手機通訊錄</h2></div><p>${state.knownPeople.length} 位聯絡人</p></div>${state.knownPeople.length?`<div class="contact-list">${state.knownPeople.map(id=>{const n=NPCS[id];return `<article><div>${n.avatar}</div><span><b>${n.name}</b><small>${n.job}</small></span><em>剛認識</em></article>`}).join("")}</div>`:`<div class="tablet-empty"><span>♡</span><h3>還沒有認識任何人</h3><p>第一輪沒有免費人脈。安排自由活動或參加工作，讓第一次相遇真的發生。</p><button data-go-free>去安排自由活動</button></div>`}</div>`}
function logApp(){return `<div class="inside-page"><div class="inside-title"><div><span>CAREER LOG</span><h2>星途紀錄</h2></div><p>已完成 ${state.history.length} 週</p></div>${state.history.length?`<div class="log-list">${[...state.history].reverse().map(w=>`<article><b>第 ${w.week} 週</b><span>${w.results.filter(r=>r.success).length} 次成功</span><small>${w.results.map(r=>r.action).join("・")}</small></article>`).join("")}</div>`:`<div class="tablet-empty"><span>✦</span><h3>第一頁還是空白</h3><p>完成第一週後，每日成果與重大選擇會整理在這裡。</p></div>`}</div>`}

const MAP_LOCATIONS={radio:{name:"星望廣播電臺",area:"傳媒區",icon:"聲",note:"節目錄音、主持與業界人士出入的地方。",effect:"可能認識主持人，提升口才或社交"},livehouse:{name:"月蝕 Live House",area:"舊城區",icon:"樂",note:"新人樂團與地下歌手聚集的小型展演空間。",effect:"獲得舞台經驗、歌藝或創作靈感"},park:{name:"星光河濱公園",area:"河岸區",icon:"休",note:"適合散步、慢跑與放空的公共空間。",effect:"降低疲勞並可能觸發日常事件"},studio:{name:"十七號攝影棚",area:"影視園區",icon:"影",note:"廣告與戲劇經常在此拍攝，目前尚未開放。",effect:"需要通告或業界關係才能進入",locked:true}};
function mapApp(){return `<div class="map-page"><div class="map-intro"><div><span>STARWISH CITY</span><h2>今天想去哪裡？</h2><p>${state.selectedDay!=null?`將為${DAYS[state.selectedDay]}安排自由活動。`:"選擇地點探索星望市。"}</p></div><b>交通費 $300</b></div><div class="city-map">${Object.entries(MAP_LOCATIONS).map(([id,l])=>`<button class="map-place ${l.locked?"locked":""} ${state.mapLocation===id?"selected":""}" ${l.locked?"disabled":""} data-map-location="${id}"><i>${l.icon}</i><span><small>${l.area}</small><b>${l.name}</b><em>${l.note}</em><strong>${l.effect}</strong></span>${l.locked?`<u>尚未解鎖</u>`:`<u>選擇地點 →</u>`}</button>`).join("")}</div><aside class="map-tip">自由活動必須先選擇地點；地點會影響可能遇見的人物、能力成長與事件。</aside></div>`}

function jobsApp(){const stage=state.jobStage;return `<div class="jobs-page"><div class="job-board-head"><div><span>CASTING BOARD / 001</span><h2>${JOB.title}</h2><p>${JOB.tagline}</p></div><strong class="job-status">${stage==="available"?"可接取":stage==="applied"?"等待試鏡":stage==="audition"?"試鏡進行中":stage==="active"?"合約執行中":stage==="completed"?"已完成":"試鏡通過"}</strong></div>${jobStageView(stage)}</div>`}
function jobWorkDaysText(){return JOB.workDays.map(i=>"週"+SHORT[i]).join("、")}
function jobRequirementsHtml(){return JOB.requirements.map(([n,min])=>`<span class="${state.stats[n]>=min?"met":"unmet"}">${n} ≥ ${min}${state.stats[n]>=min?" ✓":""}</span>`).join("")}
function jobStageView(stage){if(stage==="available")return `<div class="job-layout"><section class="job-sheet"><h3>通告資料</h3><dl><div><dt>委託品牌</dt><dd>${JOB.brand}</dd></div><div><dt>報酬</dt><dd>${money(JOB.pay)}</dd></div><div><dt>工作次數</dt><dd>${JOB.sessions} 次拍攝</dd></div><div><dt>指定工作日</dt><dd>每週${jobWorkDaysText()}</dd></div><div><dt>完成期限</dt><dd>第 ${state.jobDeadline} 週週日</dd></div><div class="req-row"><dt>資質需求</dt><dd class="req-list">${jobRequirementsHtml()}</dd></div></dl></section><section class="job-action"><span>目前評估</span><h3>值得一試</h3><p>品牌正在尋找自然、有朝氣的新人。接取後需要先通過試鏡，通過才會建立正式合約。</p><button data-job-action="apply">接取試鏡邀請 →</button></section></div>`;if(stage==="applied")return `<div class="audition-lobby"><span>AUDITION READY</span><h2>試鏡通知已確認</h2><p>試鏡不會立刻占用本週行程；先完成現場選擇，通過後再安排正式拍攝。</p><div><b>地點</b>十七號攝影棚・B 棚</div><div><b>資質需求</b><span class="req-list">${jobRequirementsHtml()}</span></div><div><b>提示</b>品牌喜歡自然的笑容，不需要用力過猛。</div><button data-job-action="start-audition">進入試鏡現場 →</button></div>`;if(stage==="audition")return `<div class="audition-room"><div><span>CAMERA TEST</span><h2>導演請你對鏡頭喝下一口汽水</h2><p>「不用照腳本，給我一個最像妳自己的反應。」</p></div><section><button data-audition-choice="natural"><b>自然笑著說：「好喝耶。」</b><small>親和力與鏡頭感判定・穩定</small></button><button data-audition-choice="bold"><b>即興演出被氣泡嗆到的反應</b><small>演技與膽識判定・高風險</small></button></section></div>`;if(stage==="passed")return `<div class="contract-result"><span>✓ AUDITION PASSED</span><h2>試鏡通過！</h2><p>導演記住了妳自然的鏡頭反應。簽約後需要在第 ${state.jobDeadline} 週以前完成 ${JOB.sessions} 次拍攝，並優先安排在每週${jobWorkDaysText()}。</p><button data-job-action="sign">簽署通告合約 →</button></div>`;if(stage==="active")return `<div class="contract-dashboard"><section><span>ACTIVE CONTRACT</span><h2>${JOB.title}</h2><p>請把「廣告拍攝」排入行程，每完成一天會扣除一次剩餘工作。</p><div class="contract-progress"><i><b style="width:${(JOB.sessions-state.jobRemaining)/JOB.sessions*100}%"></b></i><strong>已完成 ${JOB.sessions-state.jobRemaining}／${JOB.sessions} 次</strong></div></section><aside><b>剩餘 ${state.jobRemaining} 次</b><span>指定工作日：每週${jobWorkDaysText()}</span><span>第 ${state.jobDeadline} 週週日截止</span><button data-job-action="schedule">排入指定工作日 →</button></aside></div>`;if(stage==="breached")return `<div class="contract-result breached"><span>! CONTRACT BREACHED</span><h2>通告逾期</h2><p>期限內仍有 ${state.jobRemaining} 次拍攝未完成，品牌已終止合約。正式版將在此結算違約金、業界評價與後續事件。</p><button data-open-app="planner">回到行程表 →</button></div>`;return `<div class="contract-result"><span>★ CONTRACT COMPLETE</span><h2>通告完成！</h2><p>品牌已支付 ${money(JOB.pay)}，作品將成為妳的第一份正式履歷。</p><button data-open-app="planner">回到行程表 →</button></div>`}

function npcApp(){const ids=state.knownPeople;if(!ids.length)return `<div class="tablet-empty"><span>◈</span><h3>還沒有認識任何人</h3><p>第一輪沒有免費人脈。安排自由活動或參加工作，讓第一次相遇真的發生，對方才會出現在這裡。</p><button data-go-free>去安排自由活動</button></div>`;const current=ids.includes(state.selectedNpc)?state.selectedNpc:ids[0],npc=NPCS[current];return `<div class="npc-dossier"><nav class="npc-list">${ids.map(id=>{const n=NPCS[id];return `<button class="${id===current?"active":""}" data-select-npc="${id}"><i>${n.avatar}</i><span><b>${n.name}</b><small>${n.job}</small></span></button>`}).join("")}</nav><section class="npc-card"><div class="npc-card-head"><div class="npc-photo">${npc.avatar}</div><div><span>已認識</span><h2>${npc.name}</h2><p>${npc.bio}</p></div></div><dl><div><dt>職業</dt><dd>${npc.job}</dd></div><div><dt>常出沒地點</dt><dd>${npc.location}</dd></div><div><dt>關係階段</dt><dd>初識 08／100</dd></div><div><dt>可用互動</dt><dd>傳訊息・拜訪</dd></div></dl><button class="main-btn" disabled>傳送訊息（功能開發中）</button></section></div>`}

function decisionFor(id){if(id==="free"&&state.mapLocation){const l=MAP_LOCATIONS[state.mapLocation];return{title:`抵達${l.name}`,text:l.note,choices:[{id:"explore",label:"四處走走，主動探索",note:"提高遇見人物或事件的機會"},{id:"focus",label:"專注體驗這個地點",note:"較容易獲得能力或狀態成長"}]}}if(id==="audition")return{title:"導演臨時更換了台詞",text:"輪到你試鏡前，現場突然要求即興。你打算怎麼應對？",choices:[{id:"safe",label:"照原本準備穩穩演",note:"成功率較高，成果穩定"},{id:"bold",label:"順勢加入自己的設計",note:"風險較高，大成功時曝光更多"}]};if(id==="free")return{title:"午後還沒有安排",text:"星望市今天很熱鬧，你想把空閒時間花在哪裡？",choices:[{id:"radio",label:"去廣播電臺附近逛逛",note:"可能遇見業界人物"},{id:"livehouse",label:"鑽進巷子裡的 Live House",note:"可能獲得靈感與舞台經驗"}]};if(id==="street")return{title:"街頭的人比預期更多",text:"你選好位置，卻發現路人來去匆匆。要怎麼抓住注意力？",choices:[{id:"steady",label:"唱最熟悉的歌",note:"穩定演出，成功率較高"},{id:"interact",label:"主動邀請路人點歌",note:"考驗社交，收益波動更大"}]};return null}
function runnerView(){const i=state.runnerDay,a=ACTIONS[state.schedule[i]];return `<main class="event-screen"><img src="./assets/star-city-street.webp" alt="星望市娛樂街景"><div class="event-top"><div class="logo dark">✦ 星途未定</div><div>${state.week} 週・DAY ${i+1}　${DAYS[i]}</div><div>體力 ${state.stamina}　疲勞 ${state.fatigue}</div></div><div class="day-track">${DAYS.map((d,x)=>`<i class="${x<i?"done":x===i?"now":""}">${x<i?"✓":x+1}<small>${SHORT[x]}</small></i>`).join("")}</div><section class="story-box"><div class="story-action"><i>${a.icon}</i><span><small>今日行程</small><b>${a.label}</b><em>${a.note}</em></span></div>${state.runnerPhase==="loading"?`<div class="story-loading"><i></i><b>今天正在發生……</b></div>`:state.runnerPhase==="decision"?decisionView():resultView()} </section></main>`}
function decisionView(){const d=state.runnerDecision;return `<div class="decision"><span>CHOICE</span><h2>${d.title}</h2><p>${d.text}</p><div>${d.choices.map(c=>`<button data-choice="${c.id}"><b>${c.label}</b><small>${c.note}</small></button>`).join("")}</div></div>`}
function resultView(){const r=state.runnerResult;return `<div class="day-result ${r.success?"success":"fail"}"><span>${r.success?"RESULT・SUCCESS":"RESULT・EXPERIENCE"}</span><h2>${r.title}</h2><p>${r.text}</p><div><b>💰 ${money(state.money)}</b><b>★ 知名度 ${state.fame}</b><b>♡ 粉絲 ${state.fans}</b></div><button class="main-btn" id="next-day">${state.runnerDay===6?"查看本週總結":"前往"+DAYS[state.runnerDay+1]} →</button></div>`}

function applyGains(gains){const out=[];gains.forEach(([n,min,max])=>{let gain=random(min,max)+(state.focus==="growth"?1:0);state.stats[n]=Math.min(1000,state.stats[n]+gain);out.push(`<b>${n}＋${gain}</b>`)});return out.join("、")}
function startDay(){state.runnerResult=null;state.runnerDecision=null;state.runnerPhase="loading";render();setTimeout(()=>{const d=decisionFor(state.schedule[state.runnerDay]);if(d){state.runnerDecision=d;state.runnerPhase="decision";render()}else resolveDay(null)},650)}
function resolveDay(choice){const id=state.schedule[state.runnerDay],a=ACTIONS[id];let title="成功！",text="",success=true;state.money-=a.cost;
 if(a.type==="train"){text=`課程順利結束，${applyGains(a.gains)}。學費 <b>－${money(a.cost)}</b>。`;state.stamina=Math.max(0,state.stamina-a.stamina);state.fatigue+=a.fatigue}
 else if(id==="rest"){title="好好休息！";const reduced=Math.min(state.fatigue,18);state.fatigue-=reduced;state.stamina=Math.min(100,state.stamina+24);state.mood=Math.min(100,state.mood+3);text=`體力 <b>＋24</b>、疲勞 <b>－${reduced}</b>。專業躺平也是職涯管理。`}
 else if(id==="free"){state.fatigue+=3;state.stamina=Math.max(0,state.stamina-4);const loc=state.mapLocation||"park";if(loc==="radio"&&choice==="explore"&&!state.knownPeople.includes("jiqing")){state.knownPeople.push("jiqing");state.selectedNpc="jiqing";state.contract+=4;text="你幫忙撿回散落的訪綱，第一次認識主持人<b>紀晴</b>。簽約進度 <b>＋4%</b>。"}else if(loc==="livehouse"){const g=random(3,7);state.stats.靈感+=g;state.stats.歌藝+=2;text=`你看了一場新人演出，<b>靈感＋${g}、歌藝＋2</b>。`}else if(loc==="park"){const reduced=Math.min(state.fatigue,8);state.fatigue-=reduced;state.mood=Math.min(100,state.mood+5);text=`河邊散步讓妳喘了口氣，<b>疲勞－${reduced}、心情＋5</b>。`}else{const g=random(2,5);state.stats.口才+=g;text=`你在電臺旁觀摩錄影，<b>口才＋${g}</b>。`}}
 else if(id==="adshoot"){state.fatigue+=a.fatigue;state.stamina=Math.max(0,state.stamina-a.stamina);state.jobRemaining=Math.max(0,state.jobRemaining-1);const g=random(3,6);state.stats.鏡頭感=Math.min(1000,state.stats.鏡頭感+g);if(state.jobRemaining===0){state.jobStage="completed";state.money+=JOB.pay;state.fame+=18;state.fans+=120;text=`完成最後一次拍攝！<b>鏡頭感＋${g}、報酬＋${money(JOB.pay)}、知名度＋18、粉絲＋120</b>。`}else{text=`完成一階段拍攝，<b>鏡頭感＋${g}</b>。合約還剩 <b>${state.jobRemaining} 次</b>工作。`}}
 else if(a.gains){text=`自主安排留下成果，${applyGains(a.gains)}。`;state.fatigue+=a.fatigue;state.stamina=Math.max(0,state.stamina-a.stamina)}
 else{state.fatigue+=a.fatigue;state.stamina=Math.max(0,state.stamina-a.stamina);let power=id==="audition"?(state.stats.鏡頭感+state.stats.親和力+state.stats.口才)/3:(state.stats.歌藝+state.stats.肢體表現+state.stats.社交)/3;let chance=Math.max(10,Math.min(78,32+(power-75)*.24+(state.focus==="fame"?8:0)+(choice==="safe"||choice==="steady"?10:-4)));if(Math.random()*100<chance){if(id==="audition"){const f=choice==="bold"?8:4,g=random(5,9);state.stats.鏡頭感+=g;state.fame+=f+(state.focus==="fame"?2:0);state.fans+=random(15,55);state.contract+=choice==="bold"?18:13;text=`導演請你留下資料。<b>鏡頭感＋${g}、知名度＋${f}、簽約進度＋${choice==="bold"?18:13}%</b>。`}else{const earn=choice==="interact"?random(900,1800):random(500,1100);state.money+=earn;state.fame+=2+(state.focus==="fame"?2:0);state.fans+=random(8,35);text=`有人停下來替你鼓掌。小費 <b>＋${money(earn)}</b>，知名度與粉絲也增加了。`}}else{title="這次沒有成功";success=false;const n=id==="audition"?"鏡頭感":"歌藝",g=random(1,3);state.stats[n]+=g;text=`機會擦身而過，但實戰沒有白費，<b>${n}＋${g}</b>。`}}
 state.contract=Math.min(100,state.contract);state.runnerPhase="result";state.runnerResult={title,text,success};state.weekResults.push({day:DAYS[state.runnerDay],action:a.label,result:(title+" "+text.replace(/<[^>]+>/g,"")),success});render()}
function finishWeek(){const train=state.schedule.filter(id=>ACTIONS[id].type==="train").length,work=state.schedule.filter(id=>["work","job"].includes(ACTIONS[id].type)).length,done=train>=2&&work>=1&&state.fatigue<=60;state.reward=done?{title:"本週任務完成！",text:"妳的準備度受到注意。獲得 $1,500，簽約進度＋10%。"}:{title:"本週任務未完成",text:"訓練、工作或疲勞條件沒有同時達成，下週還能再挑戰。"};if(done){state.money+=1500;state.contract=Math.min(100,state.contract+10)}state.history.push({week:state.week,results:[...state.weekResults],reward:done});state.screen="summary";render()}
function summaryView(){const ok=state.weekResults.filter(r=>r.success).length;return `<main class="summary-screen"><img src="./assets/rookie-room.webp" alt="新人房間"><section class="summary-paper"><span>WEEK ${state.week} COMPLETE</span><h1>${state.reward.title}</h1><p>${state.reward.text}</p><div class="reward-status"><div><small>順利完成</small><b>${ok}/7</b></div><div><small>現有存款</small><b>${money(state.money)}</b></div><div><small>簽約進度</small><b>${state.contract}%</b></div><div><small>目前疲勞</small><b>${state.fatigue}</b></div></div><div class="week-recap">${state.weekResults.map(r=>`<div><span>${r.day}</span><b>${r.action}</b><em>${r.success?"成功":"累積經驗"}</em></div>`).join("")}</div><button class="main-btn" id="next-week">回到房間，開始第 ${state.week+1} 週 →</button></section></main>`}

function bind(){
 if(state.screen==="create"){document.querySelector("#player-name")?.addEventListener("input",e=>{state.name=e.target.value;document.querySelector("#to-stats").disabled=!state.name.trim()});document.querySelectorAll("[data-gender]").forEach(x=>x.onclick=()=>{const g=x.dataset.gender;state.gender=g==="自訂"?state.customGender||"自訂":g;render()});document.querySelector("#custom-gender")?.addEventListener("input",e=>{state.customGender=e.target.value;state.gender=e.target.value||"自訂"});document.querySelector("#to-stats")?.addEventListener("click",()=>{state.createStep=2;render()});document.querySelector("#back")?.addEventListener("click",()=>{state.createStep=1;render()});document.querySelector("#reroll")?.addEventListener("click",rollStats);document.querySelector("#start")?.addEventListener("click",()=>{state.screen="game";render()});return}
 if(state.screen==="runner"){document.querySelectorAll("[data-choice]").forEach(x=>x.onclick=()=>resolveDay(x.dataset.choice));document.querySelector("#next-day")?.addEventListener("click",()=>{if(state.runnerDay===6)finishWeek();else{state.runnerDay++;startDay()}});return}
 if(state.screen==="summary"){document.querySelector("#next-week")?.addEventListener("click",()=>{state.week++;if(state.jobStage==="active"&&state.week>state.jobDeadline&&state.jobRemaining>0){state.jobStage="breached";state.jobNotice=`逾期未完成 ${state.jobRemaining} 次拍攝`}state.screen="game";state.tab="planner";state.appOpen=null;state.reward=null;render()});return}
 document.querySelectorAll("[data-open-app]").forEach(x=>x.onclick=()=>{const target=x.dataset.openApp;if(target==="map"&&!state.drawerOpen){const openDay=state.schedule.findIndex(id=>id==="rest");if(openDay>=0)state.selectedDay=openDay}state.appOpen=target;state.drawerOpen=false;render()});
 document.querySelectorAll("[data-close-app]").forEach(x=>x.onclick=()=>{state.appOpen=null;state.drawerOpen=false;render()});
 document.querySelector("[data-open-job]")?.addEventListener("click",()=>{state.appOpen="jobs";state.drawerOpen=false;render()});
 document.querySelectorAll("[data-day]").forEach(x=>x.onclick=()=>{state.selectedDay=Number(x.dataset.day);state.drawerOpen=true;render()});
 document.querySelectorAll("[data-close-drawer]").forEach(x=>x.onclick=()=>{state.drawerOpen=false;render()});
 document.querySelectorAll("[data-filter]").forEach(x=>x.onclick=()=>{state.filter=x.dataset.filter;render()});
 document.querySelectorAll("[data-pick]").forEach(x=>x.onclick=()=>{const id=x.dataset.pick;if(id==="free"){state.drawerOpen=false;state.appOpen="map";render();return}state.schedule[state.selectedDay]=id;state.notice=`${DAYS[state.selectedDay]}已安排「${ACTIONS[id].label}」`;state.drawerOpen=false;render()});
 document.querySelectorAll("[data-map-location]").forEach(x=>x.onclick=()=>{state.mapLocation=x.dataset.mapLocation;state.schedule[state.selectedDay]="free";state.notice=`${DAYS[state.selectedDay]}將前往「${MAP_LOCATIONS[state.mapLocation].name}」`;state.appOpen="planner";render()});
 document.querySelectorAll("[data-focus]").forEach(x=>x.onclick=()=>{state.focus=x.dataset.focus;state.notice=`本週策略改為「${FOCUSES[state.focus].label}」`;render()});
 document.querySelector("#copy")?.addEventListener("click",()=>{if(state.lastSchedule){state.schedule=[...state.lastSchedule];state.notice="已複製上週行程";render()}});
 document.querySelector("#rest-all")?.addEventListener("click",()=>{state.schedule=Array(7).fill("rest");state.notice="本週已全部改為休息";render()});
 document.querySelector("[data-go-free]")?.addEventListener("click",()=>{state.selectedDay=state.schedule.findIndex(id=>id==="rest");if(state.selectedDay<0)state.selectedDay=6;state.appOpen="map";render()});
 document.querySelectorAll("[data-select-npc]").forEach(x=>x.onclick=()=>{state.selectedNpc=x.dataset.selectNpc;render()});
 document.querySelectorAll("[data-job-action]").forEach(x=>x.onclick=()=>{const a=x.dataset.jobAction;if(a==="apply")state.jobStage="applied";if(a==="start-audition")state.jobStage="audition";if(a==="sign"){state.jobStage="active";state.jobNotice="合約已成立"}if(a==="schedule"){let i=state.schedule.findIndex((id,idx)=>JOB.workDays.includes(idx)&&(id==="rest"||id==="free"));const onWorkDay=i>=0;if(i<0)i=state.schedule.findIndex(id=>id==="rest");if(i<0)i=6;state.schedule[i]="adshoot";state.selectedDay=i;state.notice=onWorkDay?`廣告拍攝已排入${DAYS[i]}（指定工作日）`:`本週指定工作日已無空檔，廣告拍攝改排入${DAYS[i]}`;state.appOpen="planner"}render()});
 document.querySelectorAll("[data-audition-choice]").forEach(x=>x.onclick=()=>{state.jobStage="passed";state.stats.鏡頭感=Math.min(1000,state.stats.鏡頭感+4);state.jobNotice=x.dataset.auditionChoice==="bold"?"即興表現令人印象深刻":"自然反應符合品牌形象";render()});
 document.querySelector("#begin-week")?.addEventListener("click",()=>{if(budget()>state.money){state.notice="預算不足，請先調整行程";render();return}state.lastSchedule=[...state.schedule];state.weekResults=[];state.runnerDay=0;state.screen="runner";state.appOpen=null;startDay()})
}
rollStats();
