const CACHE="star-game-runtime-v1.26.0";
const AUDIO_SHELL=["tap","open","close","back","confirm","schedule","warning","reward","message","paper","scroll","select","switch","tick"].map(name=>`./assets/audio/kenney-interface/${name}.ogg`);
const SHELL=["./","./index.html","./cascade.css","./legacy-foundation.css","./legacy-onboarding-settings.css","./legacy-career-agency.css","./legacy-people-wardrobe.css","./legacy-world-social.css","./legacy-career-feedback.css","./legacy-world-creative.css","./legacy-progression.css","./legacy-story-gallery.css","./legacy-late-passes.css","./ui-hardening.css","./design-system.css","./components-feedback.css","./a11y.css","./runner-flow.css","./audio.css","./browser-flow.css","./city-life.css","./src/main.js","./assets/rookie-room.webp","./assets/icons/app-icon.svg","./assets/icons/favicon-32.png","./assets/icons/apple-touch-icon.png","./assets/icons/icon-192.webp","./assets/icons/icon-512.webp","./manifest.webmanifest",...AUDIO_SHELL];
self.addEventListener("install",event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL))));
self.addEventListener("activate",event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener("message",event=>{if(event.data?.type==="SKIP_WAITING")self.skipWaiting()});
async function networkFirst(request){const cache=await caches.open(CACHE);try{const response=await fetch(request);if(response?.ok)cache.put(request,response.clone());return response}catch{const cached=await cache.match(request);if(cached)return cached;if(request.mode==="navigate")return cache.match("./index.html");throw new Error("offline")}}
async function staleWhileRevalidate(request,event){const cache=await caches.open(CACHE),cached=await cache.match(request),refresh=fetch(request).then(async response=>{if(response?.ok)await cache.put(request,response.clone());return response}).catch(()=>null);if(cached){event.waitUntil(refresh);return cached}const response=await refresh;if(response)return response;throw new Error("offline")}
function isCacheable(request,url){
 if(request.method!=="GET"||url.origin!==self.location.origin||request.headers.has("authorization"))return false;
 if(url.pathname.startsWith("/api/")||url.pathname.startsWith("/auth/"))return false;
 return request.mode==="navigate"||["script","style","image","audio","font","manifest"].includes(request.destination)||url.pathname.includes("/assets/")||url.pathname.endsWith(".json");
}
self.addEventListener("fetch",event=>{const url=new URL(event.request.url);if(!isCacheable(event.request,url))return;const dynamic=event.request.mode==="navigate"||["script","style"].includes(event.request.destination)||url.pathname.endsWith(".json");event.respondWith(dynamic?networkFirst(event.request):staleWhileRevalidate(event.request,event))});
