import test from "node:test";
import assert from "node:assert/strict";
import { initialState, hydrateState, state } from "../src/core/state.js";
import { normalizeCharacterMemories } from "../src/core/character-memory-state.js";
import { characterMemory, tellCharacterMemory, promiseCharacterCheckIn, recordCharacterMemory, canInitiateMemoryContact, memoryContactText, memoryInvitationDeferral } from "../src/logic/character-memory.js";
import { shortContact } from "../src/logic/short-contact.js";
import { tickNpcInvitation } from "../src/logic/lived-story-engine.js";
import { characterMemoryPanel } from "../src/views/character-memory.js";
const make = () => {
  const game = initialState();
  game.week = 26; game.screen = "game"; game.name = "小星";
  game.knownPeople = ["sufei"];
  game.relationships.sufei = { closeness: 45, trust: 40, affection: 10, hostility: 0, romance: "none" };
  return game;
};
test("偏好和界線由玩家明確說明，反映在措辭且不刷關係數值", () => {
  const game = make(), before = structuredClone(game.relationships);
  assert.equal(tellCharacterMemory("unknown", "drink", "tea", game).ok, false);
  assert.equal(tellCharacterMemory("sufei", "drink", "tea", game).ok, true);
  assert.equal(tellCharacterMemory("sufei", "drink", "tea", game).ok, false);
  assert.equal(game.npcMessages.length, 1);
  assert.match(memoryContactText("sufei", "day", "今天收工了。", game), /茶/);
  tellCharacterMemory("sufei", "notice", "advance", game);
  assert.equal(characterMemory("sufei", game).boundaries.notice, "advance");
  assert.deepEqual(game.relationships, before);
  assert.match(characterMemoryPanel("sufei", game), /data-memory-value="advance" aria-pressed="true"/);
});
test("敷衍會減少主動深談，實際履行下週約定才恢復分享", () => {
  hydrateState(make());
  recordCharacterMemory("sufei", { kind: "response", key: "support", value: "dismissed", text: "上次沒有聽完" });
  assert.equal(characterMemory("sufei").disclosure, "guarded");
  assert.match(memoryContactText("sufei", "work", "今天有很多想聊的事。"), /先說到這裡/);
  assert.equal(promiseCharacterCheckIn("sufei").ok, true);
  shortContact("sufei", "message", "work");
  assert.equal(characterMemory("sufei").promises[0].status, "pending");
  state.week++;
  assert.equal(shortContact("sufei", "message", "work").ok, true);
  assert.equal(characterMemory("sufei").promises[0].status, "fulfilled");
  assert.equal(characterMemory("sufei").disclosure, "open");
  assert.match(state.npcMessages.at(-1).text, /你還記得/);
});
test("暫放承諾沒有扣分或逾期懲罰，錯誤與失敗聯絡不會履約", () => {
  hydrateState(make());
  promiseCharacterCheckIn("sufei");
  state.week += 52;
  const before = structuredClone(state.relationships);
  state.relationships.sufei.hostility = 50;
  assert.equal(shortContact("sufei", "message", "work").ok, false);
  assert.equal(characterMemory("sufei").promises[0].status, "pending");
  state.relationships = before;
  assert.equal(promiseCharacterCheckIn("sufei", "release").ok, true);
  assert.equal(characterMemory("sufei").promises[0].status, "released");
  assert.deepEqual(state.relationships, before);
});
test("私人空間實際降低主動聯絡，玩家主動傳訊仍可往來", () => {
  hydrateState(make());
  tellCharacterMemory("sufei", "space", "ask");
  assert.equal(canInitiateMemoryContact("sufei"), false);
  state.week += 3;
  assert.equal(canInitiateMemoryContact("sufei"), false);
  state.week++;
  assert.equal(canInitiateMemoryContact("sufei"), true);
  assert.equal(shortContact("sufei", "message", "day").ok, true);
  assert.equal(canInitiateMemoryContact("sufei"), false);
});
test("提前邀約真的先發通知、隔週再進事件，拒絕與敷衍不被忽略", () => {
  hydrateState(make());
  tellCharacterMemory("sufei", "notice", "advance");
  const id = tickNpcInvitation();
  assert.ok(id);
  assert.equal(state.eventQueue.length, 0);
  assert.equal(state.queuedEvents.find(item => item.event.id === id).dueWeek, state.week + 1);
  assert.match(state.npcMessages.at(-1).text, /下一週/);
  assert.equal(tickNpcInvitation(), null);
  hydrateState(make());
  recordCharacterMemory("sufei", { kind: "response", key: "support", value: "dismissed" });
  assert.equal(tickNpcInvitation(), null);
});
test("記憶正規化可重複執行，未知人物與損壞紀錄不流入角色記憶", () => {
  const game = make();
  tellCharacterMemory("sufei", "place", "quiet", game);
  const value = normalizeCharacterMemories(game.characterMemories);
  assert.deepEqual(normalizeCharacterMemories(value), value);
  assert.deepEqual(normalizeCharacterMemories({ unknown: value.sufei }), {});
  assert.deepEqual(normalizeCharacterMemories({ sufei: { history: [null, { kind: "invented", key: "x" }] } }).sufei.history, []);
  hydrateState(game);
  assert.equal(characterMemory("sufei").preferences.place, "quiet");
});
test("已排入的提前邀約會尊重後來的私人空間，讀檔仍延後且不改記憶", () => {
  hydrateState(make());
  tellCharacterMemory("sufei", "notice", "advance");
  const id = tickNpcInvitation();
  const event = state.queuedEvents.find(item => item.event.id === id).event;
  tellCharacterMemory("sufei", "space", "ask");
  state.week++;
  const saved = structuredClone(state);
  assert.equal(memoryInvitationDeferral(event), 30);
  assert.deepEqual(state, saved);
  hydrateState(saved);
  assert.equal(memoryInvitationDeferral(state.queuedEvents[0].event), 30);
  state.week = 30;
  assert.equal(memoryInvitationDeferral(event), null);
});
test("新界線也攔下舊主動聯絡，但不阻擋新合法邀約、已接受邀約或改期後續", () => {
  const game = make(), old = { id: "npc-proactive:26:sufei" };
  game.npcMessages.push({ id: old.id, npcId: "sufei", week: 26, source: "proactive" });
  tellCharacterMemory("sufei", "space", "ask", game);
  assert.equal(memoryInvitationDeferral(old, game), 30);
  assert.equal(memoryInvitationDeferral({ id: "invitation:sufei:26:rescheduled" }, game), null);
  assert.equal(memoryInvitationDeferral({ id: "personal-story:sufei:26" }, game), null);
  const accepted = { id: "invitation:sufei:26" };
  game.npcInvitationHistory.push({ id: accepted.id, response: "accept" });
  assert.equal(memoryInvitationDeferral(accepted, game), null);
  game.eventHistory.push({ id: old.id, choice: "accept" });
  assert.equal(memoryInvitationDeferral(old, game), null);
  game.week = 30;
  game.npcMessages.push({ id: "npc-proactive:30:sufei", npcId: "sufei", week: 30, source: "proactive" });
  assert.equal(memoryInvitationDeferral({ id: "npc-proactive:30:sufei" }, game), null);
  game.week = 27;
  game.eventHistory = [];
  tellCharacterMemory("sufei", "space", "freely", game);
  assert.equal(memoryInvitationDeferral(old, game), null);
});
test("舊當晚邀約在新增提前通知偏好後至少延一週，既有合法提前邀約不反覆延後", () => {
  const game = make(), event = { id: "invitation:sufei:25" };
  tellCharacterMemory("sufei", "notice", "advance", game);
  assert.equal(memoryInvitationDeferral(event, game), 27);
  assert.equal(memoryInvitationDeferral({ id: "npc-proactive:26:sufei" }, game), 27);
  game.week = 27;
  assert.equal(memoryInvitationDeferral(event, game), null);
  assert.equal(memoryInvitationDeferral({ id: "invitation:sufei:27" }, game), null);
});
