import test from"node:test";
import assert from"node:assert/strict";
import{state,resetState}from"../src/core/state.js";
import{ABILITIES}from"../src/data/abilities.js";
import{setSeed,randomInt,chance}from"../src/core/rng.js";
import{tickNpcCareers}from"../src/logic/npc-ecosystem.js";
import{tickPublicOpinion}from"../src/logic/reputation-engine.js";
import{recordBrandOutcome,tickBrandRelations}from"../src/logic/brand-relations.js";
import{recordScandal,tickScandals,activeScandal}from"../src/logic/scandal-engine.js";
import{validateGameState}from"../src/core/save-schema.js";
function simulate(seed){resetState();setSeed(seed);state.name=`SIM-${seed}`;state.stats=Object.fromEntries(ABILITIES.map(n=>[n,randomInt(80,180)]));state.hidden={幽默:500,共情:500,洞察:500,膽識:500,品德:500,自律:500,野心:500,抗壓:500};state.schedule=Array(7).fill("rest");state.scheduledJobIds=Array(7).fill(null);state.scheduledActivityIds=Array(7).fill(null);state.freeLocations=Array(7).fill(null);let completed=0,scandals=0;for(let week=1;week<=260;week++){state.week=week;const stat=ABILITIES[randomInt(0,ABILITIES.length-1)];state.stats[stat]=Math.min(1000,(state.stats[stat]||0)+randomInt(2,8));state.fame=Math.min(1200,state.fame+(week%5===0?randomInt(0,5):0));state.rep.話題度=Math.max(0,Math.min(1000,(state.rep.話題度||0)+randomInt(-6,8)));state.rep.路人緣=Math.max(0,Math.min(1000,(state.rep.路人緣||500)+randomInt(-4,5)));state.rep.可信度=Math.max(0,Math.min(1000,(state.rep.可信度||500)+randomInt(-3,4)));if(week%4===0){const quality=randomInt(45,98);recordBrandOutcome(["晨露飲品","星河電視臺","巷口唱片"][randomInt(0,2)],"completed",{quality});completed++}if(!activeScandal()&&week>10&&chance(3)){const type=["misstatement","rumor","conduct"][randomInt(0,2)];recordScandal(type,randomInt(1,3),"五年模擬事件");state.rep.爭議度=Math.min(1000,state.rep.爭議度+randomInt(120,320));scandals++}if(activeScandal()){state.rep.爭議度=Math.max(0,state.rep.爭議度-randomInt(8,25));state.rep.可信度=Math.min(1000,state.rep.可信度+randomInt(1,5))}tickNpcCareers();tickPublicOpinion([{heat:randomInt(0,120)}]);tickScandals();tickBrandRelations();const valid=validateGameState(state);assert.equal(valid.ok,true,`${seed} 第 ${week} 週：${valid.errors.join("、")}`);for(const v of Object.values(state.stats))assert.ok(v>=0&&v<=1000);for(const v of Object.values(state.rep))assert.ok(v>=0&&v<=1000)}return{completed,scandals,brands:Object.keys(state.brandRelations).length,recovered:state.scandals.filter(s=>s.status==="recovered").length,npcLevels:Object.values(state.npcCareers).map(x=>x.level)}}
test("30 組 Seed 可完整跑完 260 週且核心數值不爆表",()=>{const results=Array.from({length:30},(_,i)=>simulate(`five-year-${i+1}`));assert.ok(results.every(r=>r.completed===65));assert.ok(results.some(r=>r.scandals>0));assert.ok(results.every(r=>r.brands>=3));assert.ok(results.some(r=>r.recovered>0));assert.ok(results.flatMap(r=>r.npcLevels).every(level=>level>=1&&level<=5))});
