import test from"node:test";import assert from"node:assert/strict";
import{initialState,hydrateState,state}from"../src/core/state.js";
import{ensurePlayableDepthState,buildWeeklyThread,maybeStartShortChain,tickShortChains,crewForWork,crewReunion,auditionIntelFor,recordAuditionFailure,tickFailureCallbacks,syncWorkLegacies,rememberRelationship,syncRelationshipMemories,managerIntervention,fameLifeTier,annualTentpoleStatus,competitionBeat,recordLoopKnowledge,ngPlusIntuition,recordSystemUse,telemetrySummary}from"../src/logic/playable-depth-engine.js";
import{recordScandal,tickScandals,syncScandalResponseFlags}from"../src/logic/scandal-engine.js";
import{resolveExploration}from"../src/logic/exploration.js";
function fresh(p={}){hydrateState({...initialState(),screen:"room",name:"測試藝人",...p});ensurePlayableDepthState();return state}
test("save v14 includes playable depth persistence",()=>{const s=fresh();assert.equal(s.saveVersion,14);for(const k of["weeklyThreads","eventChains","crewNetwork","industryMemories","relationshipMilestones","managerInterventions","scandalResponses","ngPlusKnowledge","playTelemetry"])assert.ok(k in s)});
test("weekly thread changes with work romance scandal",()=>{let s=fresh();assert.equal(buildWeeklyThread().type,"training");s.partnerId="jiqing";s.knownPeople=["jiqing"];s.relationships.jiqing={romance:"dating",visibility:"underground"};assert.equal(buildWeeklyThread().type,"romance");s.scandals=[{status:"active"}];assert.equal(buildWeeklyThread().type,"scandal")});
test("short chains wait for player choice then return weeks and a year later",()=>{const s=fresh({week:11});const c=maybeStartShortChain();assert.ok(c);assert.equal(c.choiceId,null);assert.ok(c.choices.length>=2);s.eventFlags.push(`depth-chain:${c.id}:${c.choices[0].id}`);s.week=c.nextWeek;assert.equal(tickShortChains().length,1);assert.equal(c.choiceId,c.choices[0].id);s.week=c.finalWeek;assert.equal(tickShortChains().length,1);assert.equal(c.done,true)});
test("works receive crew, legacy tags and can reuse crew",()=>{const s=fresh({fame:1000,completedWorks:[{id:"W1",title:"測試電影一",category:"電影",quality:90,stars:5},{id:"W2",title:"測試電影二",category:"電影",quality:88,stars:4}]});syncWorkLegacies();assert.ok(s.completedWorks[0].crew.length>=2);assert.ok(s.completedWorks[0].legacyTags.length>=1);assert.equal(crewForWork(s.completedWorks[0])[0].works[0],"W1");assert.ok(Array.isArray(crewReunion(s.completedWorks[1])))});
test("audition failure leaves callback instead of dead end",()=>{const s=fresh({week:10,activeJobs:{J001:{jobId:"J001",stage:"failed",lastAuditionWeek:10,notice:"這次沒有獲選"}}});assert.ok(auditionIntelFor("J001").prompt);const m=recordAuditionFailure("J001");assert.equal(recordAuditionFailure("J001").id,m.id);s.week=m.callbackWeek;assert.equal(tickFailureCallbacks()[0].title,"落選沒有白費");assert.match(s.activeJobs.J001.notice,/再次|回來|記得/);assert.ok(s.activeJobs.J001.lastAuditionWeek<=s.week-2)});
test("relationship memories include first meeting and first work",()=>{const s=fresh({knownPeople:["jiqing"],completedWorks:[{id:"W1",title:"同戲",category:"電影",quality:80,npcCast:["jiqing"]}]});syncRelationshipMemories();assert.ok(s.relationshipMilestones.some(x=>x.type==="firstMeet"));assert.ok(s.relationshipMilestones.some(x=>x.type==="firstWork"));rememberRelationship("jiqing","firstMeet");assert.equal(s.relationshipMilestones.filter(x=>x.type==="firstMeet").length,1)});
test("manager intervenes in overwork",()=>{fresh({fatigue:90,health:40});assert.match(managerIntervention().text,/行程|睡覺/)});
test("fame changes ordinary life and exploration has friction",()=>{const s=fresh({fame:1500,week:17});assert.equal(fameLifeTier().label,"爆紅生活");const before=s.fatigue;const r=resolveExploration("park","focus");assert.ok(r.text.length>0);assert.ok(s.fatigue>=before)});
test("actual scandal engine offers response and applies chosen flag",()=>{const s=fresh({partnerId:"jiqing",knownPeople:["jiqing"],relationships:{jiqing:{romance:"dating",visibility:"underground"}}});const sc=recordScandal("rumor",2,"深夜同車被拍");tickScandals();const queued=s.eventQueue.find(x=>x.event?.id===`scandal-choice:${sc.id}`);assert.ok(queued);assert.ok(queued.event.choices.some(x=>x.id==="publicLove"));s.eventFlags.push(`scandal-response:${sc.id}:publicLove`);syncScandalResponseFlags();assert.equal(sc.response,"publicLove");assert.equal(s.relationships.jiqing.visibility,"public")});
test("annual tentpoles are visible at their configured lead time",()=>{fresh({week:5});const t=annualTentpoleStatus();assert.equal(t.title,"春季平台招商");assert.equal(t.delta,3)});
test("third year can surface rival pressure",()=>{fresh({week:117,competitors:{rival:{name:"同期對手",momentum:80}}});const beat=competitionBeat();assert.ok(beat);assert.match(beat.text,/比較表|第三年/)});
test("new game plus keeps knowledge not stats",()=>{fresh({completedWorks:[{id:"J001",category:"電影",quality:90,legacyTags:["突破作"]}]});recordLoopKnowledge();assert.ok(ngPlusIntuition());assert.equal(state.ngPlusKnowledge.loops,1);assert.ok(state.ngPlusKnowledge.unlocked.includes("電影"))});
test("telemetry records actual app usage",()=>{fresh();recordSystemUse("jobs");recordSystemUse("jobs");recordSystemUse("map");const t=telemetrySummary();assert.deepEqual(t.most[0],["jobs",2])});
