import test from"node:test";import assert from"node:assert/strict";import{initialState,hydrateState,state}from"../src/core/state.js";import{ensurePlayableDepthState,buildWeeklyThread,maybeStartShortChain,tickShortChains,crewForWork,auditionIntelFor,recordAuditionFailure,tickFailureCallbacks,syncWorkLegacies,rememberRelationship,managerIntervention,fameLifeTier,scandalResponseOptions,respondToScandal,annualTentpoleStatus,recordLoopKnowledge,ngPlusIntuition}from"../src/logic/playable-depth-engine.js";
function fresh(p={}){hydrateState({...initialState(),screen:"room",name:"測試藝人",...p});ensurePlayableDepthState();return state}
test("save v14 includes playable depth persistence",()=>{const s=fresh();assert.equal(s.saveVersion,14);for(const k of["weeklyThreads","eventChains","crewNetwork","industryMemories","relationshipMilestones","managerInterventions","scandalResponses","ngPlusKnowledge","playTelemetry"])assert.ok(k in s)});
test("weekly thread changes with work romance scandal",()=>{let s=fresh();assert.equal(buildWeeklyThread().type,"training");s.partnerId="jiqing";s.knownPeople=["jiqing"];s.relationships.jiqing={romance:"dating",visibility:"underground"};assert.equal(buildWeeklyThread().type,"romance");s.publicOpinion.scandalLevel=2;assert.equal(buildWeeklyThread().type,"scandal")});
test("short chains have delayed and year-later callbacks",()=>{const s=fresh({week:11});const c=maybeStartShortChain();assert.ok(c);s.week=c.nextWeek;assert.equal(tickShortChains().length,1);s.week=c.finalWeek;assert.equal(tickShortChains().length,1);assert.equal(c.done,true)});
test("works receive crew and legacy tags",()=>{const s=fresh({fame:1000,completedWorks:[{id:"J999",title:"測試電影",category:"電影",quality:90,stars:5}]});syncWorkLegacies();assert.ok(s.completedWorks[0].crew.length>=2);assert.ok(s.completedWorks[0].legacyTags.length>=1);assert.equal(crewForWork(s.completedWorks[0])[0].works[0],"J999")});
test("audition failure leaves callback instead of dead end",()=>{const s=fresh({week:10});assert.ok(auditionIntelFor("J001").prompt);const m=recordAuditionFailure("J001");s.week=m.callbackWeek;assert.equal(tickFailureCallbacks()[0].title,"落選沒有白費")});
test("relationship milestones are unique memories",()=>{const s=fresh({knownPeople:["jiqing"]});rememberRelationship("jiqing","firstMeet");rememberRelationship("jiqing","firstMeet");assert.equal(s.relationshipMilestones.length,1)});
test("manager intervenes in overwork",()=>{fresh({fatigue:90,health:40});assert.match(managerIntervention().text,/行程|睡覺/)});
test("fame changes ordinary life tier",()=>{fresh({fame:1500});assert.equal(fameLifeTier().label,"爆紅生活")});
test("scandal response supports public relationship",()=>{const s=fresh({partnerId:"jiqing",knownPeople:["jiqing"],relationships:{jiqing:{romance:"dating",visibility:"underground"}}});assert.ok(scandalResponseOptions().some(x=>x.id==="publicLove"));respondToScandal("publicLove");assert.equal(s.relationships.jiqing.visibility,"public")});
test("annual tentpoles are visible before event week",()=>{fresh({week:3});const t=annualTentpoleStatus();assert.equal(t.title,"春季平台招商");assert.ok(t.delta>0)});
test("new game plus keeps knowledge not stats",()=>{fresh({completedWorks:[{id:"J001",category:"電影",quality:90}]});recordLoopKnowledge();assert.ok(ngPlusIntuition());assert.equal(state.ngPlusKnowledge.loops,1)});
