import test from"node:test";import assert from"node:assert/strict";import{state,resetState}from"../src/core/state.js";import{setSeed}from"../src/core/rng.js";import{AGENCIES}from"../src/data/agencies.js";import{JOB_BY_ID}from"../src/data/jobs-catalog.js";import{ensureWorldMarket,tickWorldMarket,marketHeat}from"../src/logic/world-market.js";import{evaluatePersona}from"../src/logic/persona-engine.js";import{ensureCompetitors,competitionPressure,tickCompetitors}from"../src/logic/competitors.js";import{tickWorkLifecycles}from"../src/logic/work-lifecycle.js";import{syncFandom}from"../src/logic/fandom.js";import{workTags,roleOptions}from"../src/logic/work-profile.js";import{ensureJobState,setJobRole,selectedJobRole,marketAdjustedPay}from"../src/logic/job-engine.js";import{addCompletedWork}from"../src/logic/portfolio.js";import{baseAgencyTerms,negotiateAgencyTerms}from"../src/logic/contract-negotiation.js";import{acceptAgencyOffer,calculateJobIncome}from"../src/logic/agency.js";
function fresh(){resetState();state.name="世界測試";state.stats={口才:700};state.hidden={};state.schedule=Array(7).fill("rest");state.freeLocations=Array(7).fill(null);state.scheduledJobIds=Array(7).fill(null);state.scheduledActivityIds=Array(7).fill(null);setSeed("world-test")}
test("市場狀態會初始化並逐週演化",()=>{fresh();const m=ensureWorldMarket();assert.equal(m.categoryHeat.電影,50);tickWorldMarket();assert.ok(marketHeat("電影")>=15&&marketHeat("電影")<=95);assert.equal(m.history.length,1)});
test("公眾人設由玩家狀態自然形成",()=>{fresh();state.rep.國民度=800;state.rep.路人緣=800;const p=evaluatePersona();assert.equal(p.id,"national");assert.ok(state.flags.some(f=>f.label.includes("公眾形象形成")))});
test("輕量競爭者會形成同領域競爭壓力",()=>{fresh();const rivals=ensureCompetitors();assert.ok(rivals.length>=10);assert.ok(competitionPressure("電影")>=0);tickCompetitors();assert.ok(rivals.every(r=>r.momentum>=10))});
test("完成作品會進入上映與長尾生命週期",()=>{fresh();state.completedWorks=[{id:"W1",title:"夜城",category:"電影",stars:4,quality:90,completedWeek:0,original:false}];state.week=1;tickWorkLifecycles();const life=state.completedWorks[0].lifecycle;assert.equal(life.stage,"opening");assert.equal(life.ageWeeks,1);state.week=6;tickWorkLifecycles();assert.ok(["theatrical","longtail","catalog"].includes(life.stage))});
test("粉絲會拆成核心粉、作品粉、CP 粉與黑粉",()=>{fresh();state.fans=10000;state.rep.爭議度=300;state.completedWorks=[{id:"W1"},{id:"W2"}];state.relationships={x:{closeness:80,trust:70}};const f=syncFandom();assert.ok(f.core>0);assert.ok(f.workFans>0);assert.ok(f.cpFans>0);assert.ok(f.haters>0)});
test("作品可取得類型標籤與角色版本",()=>{const job={category:"電影",title:"青春夜城",stars:3,tagline:"新人演員"};assert.ok(workTags(job).includes("青春"));assert.ok(workTags(job).includes("懸疑"));assert.ok(roleOptions(job).some(r=>r.id==="lead"));assert.ok(roleOptions(job).some(r=>r.id==="guest"))});
test("影視角色選擇會保存到作品並改變獎項權重",()=>{fresh();const job=JOB_BY_ID.J021||Object.values(JOB_BY_ID).find(j=>j.category==="電影");assert.ok(job);const record=ensureJobState(job.id);record.stage="passed";const roles=roleOptions(job);const role=roles.find(r=>r.id==="support")||roles[0];assert.equal(setJobRole(job.id,role.id),true);assert.equal(selectedJobRole(job.id).id,role.id);const work=addCompletedWork(job,{quality:90,role});assert.equal(work.roleId,role.id);assert.equal(work.awardMultiplier,role.award)});
test("市場需求會改變通告實際行情",()=>{fresh();const job=JOB_BY_ID.J001,m=ensureWorldMarket();m.categoryHeat[job.category]=90;m.categoryDemand[job.category]=1.3;assert.equal(marketAdjustedPay(job),Math.round(job.pay*1.3));m.categoryDemand[job.category]=.8;assert.equal(marketAdjustedPay(job),Math.round(job.pay*.8))});
test("談妥的經紀抽成會成為正式合約並影響實領",()=>{fresh();const agency=Object.values(AGENCIES)[0];state.agencyApplications[agency.id]={status:"offer"};state.agencyOffer={agencyId:agency.id,negotiatedTerms:{...baseAgencyTerms(agency),commissionRate:.1}};acceptAgencyOffer();assert.equal(state.agencyContractTerms.commissionRate,.1);const income=calculateJobIncome(10000);assert.equal(income.commission,1000);assert.equal(income.net,9000)});
test("合約談判每輪最多兩次並保存結果",()=>{fresh();const agency=Object.values(AGENCIES)[0];state.agencyOffer={agencyId:agency.id};state.contractNegotiations=[];negotiateAgencyTerms(agency,"creative");negotiateAgencyTerms(agency,"commission");const third=negotiateAgencyTerms(agency,"term");assert.equal(state.contractNegotiations.length,2);assert.equal(third.locked,true)});
