import test from"node:test";import assert from"node:assert/strict";import{state,resetState}from"../src/core/state.js";import{setSeed}from"../src/core/rng.js";import{AGENCIES}from"../src/data/agencies.js";import{JOB_BY_ID}from"../src/data/jobs.js";import{NPC_RELATION_EDGES}from"../src/data/npc-network.js";import{ensureWorldMarket,tickWorldMarket,marketHeat}from"../src/logic/world-market.js";import{evaluatePersona}from"../src/logic/persona-engine.js";import{ensureCompetitors,competitionPressure,tickCompetitors}from"../src/logic/competitors.js";import{tickWorkLifecycles}from"../src/logic/work-lifecycle.js";import{syncFandom}from"../src/logic/fandom.js";import{roleProfile,roleRequirements,roleTrainingRequirement}from"../src/logic/work-profile.js";import{selectedJobRole,qualification,marketAdjustedPay}from"../src/logic/job-engine.js";import{addCompletedWork}from"../src/logic/portfolio.js";import{baseAgencyTerms,negotiateAgencyTerms}from"../src/logic/contract-negotiation.js";import{acceptAgencyOffer,calculateJobIncome}from"../src/logic/agency.js";import{ensureNpcSocialRelation}from"../src/logic/npc-ecosystem.js";import{npcSocialStage}from"../src/logic/npc-dynamics.js";import{recordRumor,respondToRumor,rumorLevelLabel}from"../src/logic/rumor-engine.js";
function fresh(){resetState();state.name="世界測試";state.stats={口才:700};state.hidden={};state.schedule=Array(7).fill("rest");state.freeLocations=Array(7).fill(null);state.scheduledJobIds=Array(7).fill(null);state.scheduledActivityIds=Array(7).fill(null);setSeed("world-test")}
test("市場狀態會初始化並逐週演化",()=>{fresh();const m=ensureWorldMarket();assert.equal(m.categoryHeat.電影,50);tickWorldMarket();assert.ok(marketHeat("電影")>=15&&marketHeat("電影")<=95);assert.equal(m.history.length,1)});
test("公眾人設由玩家狀態自然形成",()=>{fresh();state.rep.國民度=800;state.rep.路人緣=800;const p=evaluatePersona();assert.equal(p.id,"national");assert.ok(state.flags.some(f=>f.label.includes("公眾形象形成")))});
test("輕量競爭者會形成同領域競爭壓力",()=>{fresh();const rivals=ensureCompetitors();assert.ok(rivals.length>=10);assert.ok(competitionPressure("電影")>=0);tickCompetitors();assert.ok(rivals.every(r=>r.momentum>=10))});
test("完成作品會進入上映與長尾生命週期",()=>{fresh();state.completedWorks=[{id:"W1",title:"夜城",category:"電影",stars:4,quality:90,completedWeek:0,original:false}];state.week=1;tickWorkLifecycles();const life=state.completedWorks[0].lifecycle;assert.equal(life.stage,"opening");assert.equal(life.ageWeeks,1);state.week=6;tickWorkLifecycles();assert.ok(["theatrical","longtail","catalog"].includes(life.stage))});
test("粉絲會拆成核心粉、作品粉、CP 粉與黑粉",()=>{fresh();state.fans=10000;state.rep.爭議度=300;state.completedWorks=[{id:"W1"},{id:"W2"}];state.relationships={x:{closeness:80,trust:70}};const f=syncFandom();assert.ok(f.core>0);assert.ok(f.workFans>0);assert.ok(f.cpFans>0);assert.ok(f.haters>0)});
test("影視通告在試鏡前就固定角色位階",()=>{const lead={category:"電影",title:"年度電影主演",stars:4,tagline:"主演",synopsis:"飾演主角",requirements:[["演技",500]],minTrainingSessions:30};const guest={category:"電視劇",title:"單集咖啡店員",stars:1,tagline:"單集客串",synopsis:"小角色",requirements:[["演技",500]],minTrainingSessions:30};assert.equal(roleProfile(lead).id,"lead");assert.equal(roleProfile(guest).id,"guest");assert.ok(roleRequirements(lead)[0][1]>500);assert.ok(roleRequirements(guest)[0][1]<500);assert.ok(roleTrainingRequirement(lead)>roleTrainingRequirement(guest))});
test("固定角色會直接寫入作品並影響獎項權重",()=>{fresh();const job=Object.values(JOB_BY_ID).find(j=>j.category==="電影");assert.ok(job);const role=selectedJobRole(job.id);const work=addCompletedWork(job,{quality:90,role});assert.equal(work.roleId,role.id);assert.equal(work.awardMultiplier,role.award)});
test("角色位階門檻會進入正式資格判定",()=>{fresh();const job={category:"電影",title:"主演測試",stars:4,tagline:"主演",synopsis:"主角",requirements:[["口才",600]],minTrainingSessions:20,reputationSignals:[],softTraits:[],client:"測試",pay:1};state.stats.口才=650;state.trainingSessionsCompleted=20;const q=qualification(job);assert.ok(q.rows[0].required>600);assert.ok(q.trainingRequired>20);assert.equal(q.met,false)});
test("市場需求會改變通告實際行情",()=>{fresh();const job=JOB_BY_ID.J001,m=ensureWorldMarket();m.categoryHeat[job.category]=90;m.categoryDemand[job.category]=1.3;assert.equal(marketAdjustedPay(job),Math.round(job.pay*1.3));m.categoryDemand[job.category]=.8;assert.equal(marketAdjustedPay(job),Math.round(job.pay*.8))});
test("談妥的經紀抽成會成為正式合約並影響實領",()=>{fresh();const agency=Object.values(AGENCIES)[0];state.agencyApplications[agency.id]={status:"offer"};state.agencyOffer={agencyId:agency.id,negotiatedTerms:{...baseAgencyTerms(agency),commissionRate:.1}};acceptAgencyOffer();assert.equal(state.agencyContractTerms.commissionRate,.1);const income=calculateJobIncome(10000);assert.equal(income.commission,1000);assert.equal(income.net,9000)});
test("合約談判每輪最多兩次並保存結果",()=>{fresh();const agency=Object.values(AGENCIES)[0];state.agencyOffer={agencyId:agency.id};state.contractNegotiations=[];negotiateAgencyTerms(agency,"creative");negotiateAgencyTerms(agency,"commission");const third=negotiateAgencyTerms(agency,"term");assert.equal(state.contractNegotiations.length,2);assert.equal(third.locked,true)});
test("NPC 彼此關係會依原始關係類型與強度形成階段",()=>{fresh();const positive=NPC_RELATION_EDGES.find(e=>e.type==="friend"),tense=NPC_RELATION_EDGES.find(e=>e.type==="tense");assert.ok(positive&&tense);assert.ok(["steady","close","bonded"].includes(npcSocialStage(positive,ensureNpcSocialRelation(positive)).id));assert.ok(["cooled","tense","rivalry","feud"].includes(npcSocialStage(tense,ensureNpcSocialRelation(tense)).id))});
test("緋聞會保存證據等級，回應方式改變熱度與可信度",()=>{fresh();state.rep.可信度=500;const rumor=recordRumor({npcId:"jiqing",evidence:2});assert.equal(rumorLevelLabel(rumor.evidence),"同框傳聞");const heat=rumor.heat;respondToRumor(rumor.id,"deny");assert.ok(rumor.heat<heat);assert.ok(state.rep.可信度>=500);const strong=recordRumor({npcId:"guchengxi",evidence:4});const trust=state.rep.可信度;respondToRumor(strong.id,"deny");assert.equal(strong.evidence,5);assert.ok(state.rep.可信度<trust)});
