import{state}from"../core/state.js";
import{reroll,initializeHiddenStats}from"../core/stats.js";
import{saveState}from"../core/persistence.js";
import{swapImageWhenReady}from"../core/images.js";
import{AVATARS,portraitAsset,isAvatarLocked,defaultAvatarForGender}from"../data/wardrobe.js";
import{render}from"../render.js";
const MONTH_DAYS=[31,28,31,30,31,30,31,31,30,31,30,31];
function syncIdentityFromDom(){const name=document.querySelector("#player-name")?.value??state.name,month=Number(document.querySelector("#birth-month")?.value)||state.birthMonth,day=Number(document.querySelector("#birth-day")?.value)||state.birthDay;state.name=name;state.birthMonth=Math.max(1,Math.min(12,month));state.birthDay=Math.max(1,Math.min(MONTH_DAYS[state.birthMonth-1],day));const custom=document.querySelector("#custom-gender")?.value;if(custom!==undefined){state.customGender=custom;if(!["女性","男性","非二元"].includes(state.gender))state.gender=custom||"自訂"}}
export function bindCreateScreen(){const nameInput=document.querySelector("#player-name");const syncName=()=>{state.name=nameInput?.value||"";document.querySelector("#to-stats")?.classList.toggle("needs-name",!state.name.trim())};for(const evt of["input","change","keyup"])nameInput?.addEventListener(evt,syncName);document.querySelector("#birth-month")?.addEventListener("input",e=>{state.birthMonth=Math.max(1,Math.min(12,Number(e.target.value)||1))});document.querySelector("#birth-day")?.addEventListener("input",e=>{state.birthDay=Math.max(1,Math.min(31,Number(e.target.value)||1))});document.querySelectorAll("[data-gender]").forEach(x=>x.onclick=()=>{const g=x.dataset.gender;state.gender=g==="自訂"?state.customGender||"自訂":g;if(isAvatarLocked(AVATARS[state.avatarId],state.gender))state.avatarId=defaultAvatarForGender(state.gender).id;render()});document.querySelectorAll("[data-avatar]").forEach(x=>x.onclick=async()=>{const id=x.dataset.avatar;if(!AVATARS[id]||isAvatarLocked(AVATARS[id],state.gender))return;state.avatarId=id;document.querySelectorAll("[data-avatar]").forEach(button=>{const selected=button===x;button.classList.toggle("active",selected);button.querySelector("span").textContent=selected?"✓ 已選擇":"選擇"});saveState(state);await swapImageWhenReady(document.querySelector(".create-avatar-preview img"),portraitAsset(id,"newcomer"),()=>state.avatarId===id)});document.querySelector("#custom-gender")?.addEventListener("input",e=>{state.customGender=e.target.value;state.gender=e.target.value||"自訂"});document.querySelector("#to-stats")?.addEventListener("click",()=>{syncIdentityFromDom();if(!state.name.trim()){state.notice="請先輸入姓名／藝名。";render();return}state.notice="";state.createStep=2;render()});document.querySelector("#back")?.addEventListener("click",()=>{state.createStep=1;render()});document.querySelector("#reroll")?.addEventListener("click",reroll);document.querySelector("#start")?.addEventListener("click",()=>{initializeHiddenStats();state.screen="game";render()})}
