import{ACTIONS}from"../data/actions.js";import{FOCUSES}from"../data/focuses.js";import{DAYS}from"../data/calendar.js";import{state}from"../core/state.js";import{cancelAgencyInterview}from"../logic/agency.js";import{cancelActivity}from"../logic/scheduled-activities.js";import{startDay}from"../logic/runner.js";import{budget}from"../views/planner.js";import{render}from"../render.js";
export function bindPlanner(){
 const forced=state.forcedRestWeek===state.week;
 document.querySelectorAll("[data-day]").forEach(x=>x.onclick=()=>{if(forced)return;state.selectedDay=Number(x.dataset.day);render()});
 document.querySelectorAll("[data-filter]").forEach(x=>x.onclick=()=>{if(forced)return;state.filter=x.dataset.filter;render()});
 document.querySelectorAll("[data-pick]").forEach(x=>x.onclick=()=>{if(forced)return;const id=x.dataset.pick,day=state.selectedDay;if(id==="free"){state.appOpen="map";render();return}if(state.agencyInterview&&state.agencyInterview.dayIndex===day)cancelAgencyInterview();if(state.schedule[day]==="personal_task")cancelActivity(day);state.schedule[day]=id;state.freeLocations[day]=null;state.scheduledJobIds[day]=null;state.scheduledActivityIds[day]=null;state.notice=`${DAYS[day]}已安排「${ACTIONS[id].label}」${day===6?"；游標已停在本週最後一天":""}`;state.selectedDay=Math.min(day+1,6);render()});
 document.querySelectorAll("[data-focus]").forEach(x=>x.onclick=()=>{if(forced)return;state.focus=x.dataset.focus;state.notice=`本週策略改為「${FOCUSES[state.focus].label}」`;render()});
 document.querySelector("#copy")?.addEventListener("click",()=>{if(forced)return;if(state.lastSchedule){if(state.agencyInterview)cancelAgencyInterview();for(let i=0;i<7;i++)if(state.schedule[i]==="personal_task")cancelActivity(i);state.schedule=state.lastSchedule.map((id,index)=>(id==="job_session"&&state.activeJobs[state.lastScheduledJobIds?.[index]]?.stage!=="active")||["agency_interview","personal_task"].includes(id)?"rest":id);state.freeLocations=state.schedule.map((id,i)=>id==="free"?(state.lastFreeLocations?.[i]||null):null);state.scheduledJobIds=state.schedule.map((id,i)=>id==="job_session"?(state.lastScheduledJobIds?.[i]||null):null);state.scheduledActivityIds=Array(7).fill(null);state.notice="已複製上週可重複的行程；一次性個人安排不會被複製";render()}});
 document.querySelector("#rest-all")?.addEventListener("click",()=>{if(forced)return;if(state.agencyInterview)cancelAgencyInterview();for(let i=0;i<7;i++)if(state.schedule[i]==="personal_task")cancelActivity(i);state.schedule=Array(7).fill("rest");state.freeLocations=Array(7).fill(null);state.scheduledJobIds=Array(7).fill(null);state.scheduledActivityIds=Array(7).fill(null);state.notice="本週已全部改為休息";render()});
 document.querySelector("#begin-week")?.addEventListener("click",()=>{if(forced){state.schedule=Array(7).fill("rest");state.freeLocations=Array(7).fill(null);state.scheduledJobIds=Array(7).fill(null);state.scheduledActivityIds=Array(7).fill(null)}const invalidAssigned=state.schedule.findIndex((id,index)=>id==="job_session"&&!state.scheduledJobIds[index]||id==="personal_task"&&!state.scheduledActivityIds[index]);if(invalidAssigned>=0){state.notice=`${DAYS[invalidAssigned]}的預約資料已失效，請重新安排`;render();return}if(budget()>state.money){state.notice="預算不足，請先調整行程";render();return}state.lastSchedule=[...state.schedule];state.lastFreeLocations=[...state.freeLocations];state.lastScheduledJobIds=[...state.scheduledJobIds];state.lastScheduledActivityIds=[...state.scheduledActivityIds];state.weekResults=[];state.runnerDay=0;state.screen="runner";state.appOpen=null;startDay()})
}
