import{ACTIONS}from"../data/actions.js";import{FOCUSES}from"../data/focuses.js";import{DAYS}from"../data/calendar.js";import{state}from"../core/state.js";import{cancelAgencyInterview}from"../logic/agency.js";import{cancelActivity}from"../logic/scheduled-activities.js";import{startDay}from"../logic/runner.js";import{budget}from"../views/planner.js";import{render,renderUi}from"../render.js";
import{captureWeekStart}from"../logic/career-memory.js";
import{applySchedulePreset,scheduleDueWork}from"../logic/schedule-assistant.js";
import{signJob,scheduleJobSession,jobScheduleOptions}from"../logic/job-engine.js";
import{scheduleChange}from"../logic/schedule-transaction.js";
import{setUndo}from"../core/undo.js";
import{capturePlannerTransaction,restoreStateFields}from"../core/state-transaction.js";
import{openApp}from"../core/app-navigation.js";
const scheduleSnapshot=()=>capturePlannerTransaction(state);
const restoreSchedule=snapshot=>restoreStateFields(state,snapshot);
const offerUndo=(message,snapshot)=>setUndo(message,()=>restoreSchedule(snapshot));
export function bindPlanner(){
 const forced=state.forcedRestWeek===state.week;
 document.querySelector("[data-clear-day]")?.addEventListener("click",event=>{if(forced)return;const snapshot=scheduleSnapshot(),day=Number(event.currentTarget.dataset.clearDay);if(state.agencyInterview?.dayIndex===day)cancelAgencyInterview();if(state.schedule[day]==="personal_task")cancelActivity(day);const result=scheduleChange(state,day,{type:"rest",allowStandardAction:true});state.notice=result.ok?`${DAYS[day]}已清空並改為休息`:result.message;if(result.ok)offerUndo(state.notice,snapshot);render()});
 document.querySelectorAll("[data-day]").forEach(x=>x.onclick=()=>{if(forced)return;state.selectedDay=Number(x.dataset.day);renderUi()});
 document.querySelectorAll("[data-filter]").forEach(x=>x.onclick=()=>{if(forced)return;state.filter=x.dataset.filter;renderUi()});
 document.querySelectorAll("[data-planner-sign-job]").forEach(x=>x.onclick=()=>{if(forced)return;const ok=signJob(x.dataset.plannerSignJob);state.notice=ok?"合約已成立；這份通告已加入下方「工作」清單。":"合約目前無法成立，請查看合作檔期。";state.filter="工作";render()});
 document.querySelectorAll("[data-planner-job]").forEach(x=>x.onclick=()=>{if(forced)return;const result=scheduleJobSession(x.dataset.plannerJob,Number(x.dataset.jobDay));state.notice=result.message;render()});
 document.querySelectorAll("[data-planner-focus-job]").forEach(x=>x.onclick=()=>{if(forced)return;state.filter="工作";const id=x.dataset.plannerFocusJob,job=state.activeJobs[id],preferred=jobScheduleOptions(id)[0]?.day;if(preferred!=null)state.selectedDay=preferred;state.notice=!job?"通告資料已失效。":preferred==null?"已切到工作分類，但本週沒有符合合約與共演檔期的空位。":"已切到工作分類並選好第一個可用日期。";render()});
 document.querySelectorAll("[data-pick]").forEach(x=>x.onclick=()=>{if(forced)return;const id=x.dataset.pick,day=state.selectedDay;if(id==="free"){openApp(state,"map");render();return}if(state.agencyInterview&&state.agencyInterview.dayIndex===day)cancelAgencyInterview();if(state.schedule[day]==="personal_task")cancelActivity(day);const result=scheduleChange(state,day,{type:id,allowStandardAction:true});if(!result.ok){state.notice=result.message;render();return}state.notice=`${DAYS[day]}已安排「${ACTIONS[id].label}」${day===6?"；游標已停在本週最後一天":""}`;state.selectedDay=Math.min(day+1,6);render()});
 document.querySelectorAll("[data-focus]").forEach(x=>x.onclick=()=>{if(forced)return;state.focus=x.dataset.focus;state.notice=`本週策略改為「${FOCUSES[state.focus].label}」`;render()});
 document.querySelectorAll("[data-schedule-preset]").forEach(x=>x.onclick=()=>{if(forced)return;const snapshot=scheduleSnapshot(),result=applySchedulePreset(x.dataset.schedulePreset);state.notice=result.message;if(result.ok!==false)offerUndo(state.notice,snapshot);render()});
 document.querySelector("[data-schedule-work]")?.addEventListener("click",()=>{if(forced)return;const snapshot=scheduleSnapshot(),result=scheduleDueWork();state.notice=result.message;if(result.ok!==false)offerUndo(state.notice,snapshot);render()});
 document.querySelector("#copy")?.addEventListener("click",()=>{if(forced)return;if(state.lastSchedule){const snapshot=scheduleSnapshot();if(state.agencyInterview)cancelAgencyInterview();for(let i=0;i<7;i++)if(state.schedule[i]==="personal_task")cancelActivity(i);state.schedule=state.lastSchedule.map((id,index)=>(id==="job_session"&&state.activeJobs[state.lastScheduledJobIds?.[index]]?.stage!=="active")||["agency_interview","personal_task"].includes(id)?"rest":id);state.freeLocations=state.schedule.map((id,i)=>id==="free"?(state.lastFreeLocations?.[i]||null):null);state.scheduledJobIds=state.schedule.map((id,i)=>id==="job_session"?(state.lastScheduledJobIds?.[i]||null):null);state.scheduledActivityIds=Array(7).fill(null);state.notice="已複製上週可重複的行程；一次性個人安排不會被複製";offerUndo(state.notice,snapshot);render()}});
 document.querySelector("#rest-all")?.addEventListener("click",()=>{if(forced)return;const snapshot=scheduleSnapshot();if(state.agencyInterview)cancelAgencyInterview();for(let i=0;i<7;i++)if(state.schedule[i]==="personal_task")cancelActivity(i);state.schedule=Array(7).fill("rest");state.freeLocations=Array(7).fill(null);state.scheduledJobIds=Array(7).fill(null);state.scheduledActivityIds=Array(7).fill(null);state.notice="本週已全部改為休息";offerUndo(state.notice,snapshot);render()});
 document.querySelector("#begin-week")?.addEventListener("click",()=>{if(forced){state.schedule=Array(7).fill("rest");state.freeLocations=Array(7).fill(null);state.scheduledJobIds=Array(7).fill(null);state.scheduledActivityIds=Array(7).fill(null)}const invalidAssigned=state.schedule.findIndex((id,index)=>id==="job_session"&&!state.scheduledJobIds[index]||id==="personal_task"&&!state.scheduledActivityIds[index]);if(invalidAssigned>=0){state.notice=`${DAYS[invalidAssigned]}的預約資料已失效，請重新安排`;render();return}if(budget()>state.money){state.notice="預算不足，請先調整行程";render();return}state.lastSchedule=[...state.schedule];state.lastFreeLocations=[...state.freeLocations];state.lastScheduledJobIds=[...state.scheduledJobIds];state.lastScheduledActivityIds=[...state.scheduledActivityIds];state.weekResults=[];captureWeekStart();state.runnerDay=0;state.screen="runner";state.appOpen=null;startDay()})
}
