// 畫面層：經紀公司 App（列表、資格比對、面談狀態、合約卡片、已簽約／已到期儀表板）。只讀 state 與 logic/agency.js 的判定結果。
import{AGENCIES,AGENCY_LIST}from"../data/agencies.js";
import{DAYS}from"../data/calendar.js";
import{state}from"../core/state.js";
import{esc}from"../core/utils.js";
import{agencyRequirementRows,checkAgencyEligibility,isAgencyContractActive}from"../logic/agency.js";

export function agencyOverallStatusText(){if(isAgencyContractActive()){const agency=AGENCIES[state.currentAgencyId],remain=Math.max(0,state.agencyContractEndWeek-state.week+1);return `${agency.name}旗下新人・合約剩餘 ${remain} 週`}if(state.agencyOffer)return `收到 ${AGENCIES[state.agencyOffer.agencyId].name} 的合約，尚未決定`;const eligible=AGENCY_LIST.filter(a=>checkAgencyEligibility(a).met).length;if(state.agencyStatus==="expired")return `自由藝人・目前可投遞 ${eligible}／${AGENCY_LIST.length} 間公司`;return `未簽約新人・目前可投遞 ${eligible}／${AGENCY_LIST.length} 間公司`}
export function agencyStatusLabel(agency){if(isAgencyContractActive()&&state.currentAgencyId===agency.id)return"已正式簽約";if(state.agencyOffer&&state.agencyOffer.agencyId===agency.id)return"收到合約";const app=state.agencyApplications[agency.id];if(app&&app.status==="expired")return"合約已到期";if(!app)return checkAgencyEligibility(agency).met?"尚未投遞":"尚未符合投遞資格";if(app.status==="applied")return"已投遞，等待安排面談";if(app.status==="interview_scheduled")return `面談已排入${DAYS[state.agencyInterview.dayIndex]}`;if(app.status==="rejected")return"未獲錄取";if(app.status==="declined")return"已拒絕合約";return"查看中"}
export function agencyIneligibleBlock(eligibility){return `<p>目前尚未符合投遞資格，還缺：</p><ul class="agency-missing">${eligibility.missing.map(m=>`<li>${esc(m.label)}（目前 ${m.current}${m.unit}／需求 ${m.required}${m.unit}）</li>`).join("")}</ul><button class="main-btn" disabled>目前尚未符合投遞資格</button>`}
export function agencyContractCard(agency){return `<section class="agency-action agency-contract-card"><span>OFFICIAL CONTRACT</span><h3>${esc(agency.name)}正式合約</h3><dl><div><dt>合約期間</dt><dd>${agency.contract.durationWeeks} 週（約 ${Math.round(agency.contract.durationWeeks/52*10)/10} 年）</dd></div><div><dt>起始週</dt><dd>第 ${state.week} 週</dd></div><div><dt>到期週</dt><dd>第 ${state.week+agency.contract.durationWeeks-1} 週</dd></div><div><dt>經紀抽成</dt><dd>${Math.round(agency.contract.commissionRate*100)}%</dd></div><div><dt>合約定位</dt><dd>${esc(agency.contract.description)}</dd></div><div><dt>公司擅長領域</dt><dd>${agency.specialties.map(esc).join("、")}</dd></div><div><dt>簽約後身分</dt><dd>${esc(agency.shortName)}・旗下新人</dd></div></dl><p>請詳閱條款；一旦簽約，將無法再投遞其他經紀公司。</p><div class="agency-contract-actions"><button class="main-btn" data-agency-action="accept-offer">接受合約</button><button class="ghost-btn" data-agency-action="decline-offer">婉拒合約</button></div></section>`}
export function agencySignedDashboard(agency){const remain=Math.max(0,state.agencyContractEndWeek-state.week+1);return `<section class="agency-action agency-signed"><span>目前公司狀態</span><h3>${esc(agency.name)}・旗下新人</h3><div class="agency-signed-grid"><div><small>合約起始週</small><b>第 ${state.agencySignedWeek} 週</b></div><div><small>合約到期週</small><b>第 ${state.agencyContractEndWeek} 週</b></div><div><small>剩餘週數</small><b>${remain} 週</b></div><div><small>經紀抽成</small><b>${Math.round(agency.contract.commissionRate*100)}%</b></div></div><p>擅長領域：${agency.specialties.map(esc).join("、")}</p><div class="agency-upcoming"><span>後續開放</span>${["聯絡經紀人","公司內部通告","公司培訓"].map(t=>`<em>${t}・後續開放</em>`).join("")}</div></section>`}
export function agencyExpiredDashboard(agency){const hist=[...state.agencyHistory].reverse().find(h=>h.agencyId===agency.id);const endWeek=hist?hist.endWeek:state.agencyContractEndWeek;return `<section class="agency-action agency-expired"><span>合約狀態</span><h3>合約已到期</h3><p>你與${esc(agency.name)}的合約已於第 ${endWeek} 週到期，目前恢復自由藝人身分，可以投遞其他經紀公司。</p><div class="agency-upcoming"><span>後續開放</span><em>與${esc(agency.name)}續約・後續開放</em><em>另尋新公司・後續開放</em></div></section>`}
export function agencyActionPanel(agency,eligibility,app){if(isAgencyContractActive()&&state.currentAgencyId!==agency.id)return `<section class="agency-action"><span>目前申請狀態</span><h3>已與其他公司簽約</h3><p>你已是${esc(AGENCIES[state.currentAgencyId].name)}的旗下新人，暫時無法投遞其他經紀公司。</p></section>`;if(app&&app.status==="declined")return `<section class="agency-action"><span>目前申請狀態</span><h3>已拒絕合約</h3><p>你先前婉拒了${esc(agency.name)}的合約，暫時不會再收到相同邀約。可以持續累積能力與作品，等待日後的機會。</p></section>`;if(app&&app.status==="interview_scheduled")return `<section class="agency-action"><span>目前申請狀態</span><h3>面談已排入${DAYS[state.agencyInterview.dayIndex]}</h3><p>開始這一週後，面談當天會出現在逐日行程中，屆時可以選擇如何應對這場面談。</p></section>`;if(app&&app.status==="applied")return `<section class="agency-action"><span>目前申請狀態</span><h3>已投遞，等待安排面談</h3><p>公司已收到新人資料。投遞本身不會占用行程，接下來請把面談排入本週行程。</p><button class="main-btn" data-agency-action="schedule-interview">排入本週行程 →</button></section>`;if(app&&app.status==="rejected")return `<section class="agency-action"><span>目前申請狀態</span><h3>未獲錄取</h3><p>這次面談沒有成功，但仍是寶貴的實戰經驗。可以持續訓練，符合條件後再重新投遞。</p>${eligibility.met?`<button class="main-btn" data-agency-action="apply">重新投遞新人資料 →</button>`:agencyIneligibleBlock(eligibility)}</section>`;if(eligibility.met)return `<section class="agency-action"><span>目前申請狀態</span><h3>尚未投遞</h3><p>你已符合${esc(agency.name)}的簽約需求，可以投遞新人資料。</p><button class="main-btn" data-agency-action="apply">投遞新人資料 →</button></section>`;return `<section class="agency-action"><span>目前申請狀態</span><h3>尚未符合投遞資格</h3>${agencyIneligibleBlock(eligibility)}</section>`}
export function agencyDetailView(agency){const rows=agencyRequirementRows(agency),eligibility=checkAgencyEligibility(agency),isSigned=isAgencyContractActive()&&state.currentAgencyId===agency.id,offerHere=state.agencyOffer&&state.agencyOffer.agencyId===agency.id,app=state.agencyApplications[agency.id],isExpiredHere=!isSigned&&!offerHere&&app&&app.status==="expired";return `<header class="agency-detail-head"><div><span>${esc(agency.type)}・${esc(agency.scale)}</span><h2>${esc(agency.name)}</h2><p>${esc(agency.description)}</p></div><div class="agency-tags">${agency.specialties.map(s=>`<em>${esc(s)}</em>`).join("")}</div></header><section class="agency-requirements"><h3>簽約需求</h3><div class="req-list">${rows.map(r=>`<span class="${r.current>=r.required?"met":"unmet"}"><b>${esc(r.label)}</b><small>目前 ${r.current}${r.unit}／需求 ${r.required}${r.unit}</small><em>${r.current>=r.required?"符合":"未達"}</em></span>`).join("")}</div></section><section class="agency-contract-terms"><h3>合約條件</h3><dl><div><dt>合約期間</dt><dd>${agency.contract.durationWeeks} 週（約 ${Math.round(agency.contract.durationWeeks/52*10)/10} 年）</dd></div><div><dt>經紀抽成</dt><dd>${Math.round(agency.contract.commissionRate*100)}%</dd></div><div><dt>合約定位</dt><dd>${esc(agency.contract.description)}</dd></div></dl></section>${isSigned?agencySignedDashboard(agency):offerHere?agencyContractCard(agency):isExpiredHere?agencyExpiredDashboard(agency):agencyActionPanel(agency,eligibility,app)}`}
export function agencyApp(){const selectedId=state.selectedAgencyId||AGENCY_LIST[0].id,agency=AGENCIES[selectedId]||AGENCY_LIST[0];return `<div class="agency-page"><div class="agency-status-bar"><span>目前狀態</span><b>${agencyOverallStatusText()}</b></div><div class="agency-layout"><nav class="agency-list">${AGENCY_LIST.map(a=>`<button class="${a.id===agency.id?"active":""}" data-select-agency="${a.id}"><b>${esc(a.name)}</b><small>${esc(a.type)}</small><em>${agencyStatusLabel(a)}</em></button>`).join("")}</nav><section class="agency-detail">${agencyDetailView(agency)}</section></div></div>`}
