import{state}from"../core/state.js";
import{CREATIVE_TYPES}from"../logic/creative.js";
import{eligibleCreativeCollaborators,CREATIVE_BUDGETS}from"../logic/creative-team.js";
import{INDUSTRY_LIST}from"../data/industry.js";
import{NPCS}from"../data/npcs.js";
import{esc,money}from"../core/utils.js";
const STATUS={draft:"創作中",ready:"可投稿",rejected:"退件待修改",contracted:"已簽約",production:"製作中",ready_release:"待發行",released:"已發行"};
function teamPanel(p){if(!["contracted","production","ready_release"].includes(p.status))return"";const eligible=eligibleCreativeCollaborators(p),selected=new Set(p.team||[]),budget=CREATIVE_BUDGETS[p.budgetTier||"standard"];return`<div class="creative-team"><b>製作團隊與規格</b><p>自己參與：<button data-creative-self="${p.id}">${p.selfParticipation!==false?"✓ 親自參與":"幕後主創"}</button></p><div class="creative-budget">${Object.entries(CREATIVE_BUDGETS).map(([id,b])=>`<button ${p.productionSessions>0?"disabled":""} class="${(p.budgetTier||"standard")===id?"active":""}" data-creative-budget="${p.id}" data-tier="${id}">${esc(b.label)}・${money(b.cost)}</button>`).join("")}</div><small>${esc(budget.note)}${p.budgetSpent?`・已投入 ${money(p.budgetSpent)}`:""}</small><div>${eligible.length?eligible.map(n=>`<button class="${selected.has(n.id)?"active":""}" data-creative-team="${p.id}" data-npc="${n.id}">${selected.has(n.id)?"✓ ":""}${esc(n.name)}・${esc(n.field)} Lv.${n.level}</button>`).join(""):`<small>目前沒有關係與專業都適合的合作 NPC。多認識業界人士後會出現在這裡。</small>`}</div>${selected.size?`<div class="creative-roles">${[...selected].map(id=>`<button data-creative-role="${p.id}" data-npc="${id}">${esc(NPCS[id]?.name||id)}：${esc(p.roleAssignments?.[id]||"待分工")} ↻</button>`).join("")}</div><small>目前合作：${[...selected].map(id=>esc(NPCS[id]?.name||id)).join("、")}</small>`:""}</div>`}
function actionArea(p,companies){if(p.status==="ready")return`<div>${companies.map(c=>`<button data-creative-submit="${p.id}" data-company="${c.id}">投稿 ${c.name}</button>`).join("")}</div>`;if(["draft","rejected"].includes(p.status))return`<button data-creative-work="${p.id}">${p.status==="rejected"?"重新修改":"繼續創作"}</button>`;if(["contracted","production"].includes(p.status))return`<button data-creative-produce="${p.id}">安排製作工作</button>`;if(p.status==="ready_release")return`<button data-creative-release="${p.id}">安排正式發行</button>`;return""}
function projectCard(p){const def=CREATIVE_TYPES[p.type],companies=INDUSTRY_LIST.filter(c=>c.type===def.companyType||(p.type==="script"&&c.type==="電視公司")),company=INDUSTRY_LIST.find(c=>c.id===p.acceptedCompanyId);return`<article class="creative-card"><span>${def.label}・${STATUS[p.status]||p.status}</span><h3>${esc(p.title)}</h3><p>創作完成度 ${p.progress}%・品質 ${p.quality}・修改 ${p.revisions} 次</p>${["contracted","production","ready_release","released"].includes(p.status)?`<p>合作方 ${esc(company?.name||"-")}・製作 ${p.productionProgress||0}%（${p.productionSessions||0}/${p.requiredProductionSessions||def.baseSessions} 次）</p>`:""}${teamPanel(p)}${p.status==="released"?`<p><b>市場評分 ${p.marketScore}</b>・累積收入 ${money(p.revenue||0)}・第 ${p.releaseWeek} 週發行</p>`:""}${actionArea(p,companies)}${p.submissions?.length?`<small>${p.submissions.map(s=>`${INDUSTRY_LIST.find(c=>c.id===s.companyId)?.name}：${s.result}`).join("・")}</small>`:""}</article>`}
export function creativeApp(){const projects=state.creativeProjects||[];return`<div class="creative-page"><header><span>CREATIVE STUDIO</span><h2>從一張草稿，做到真正發行</h2><p>創作 → 投稿 → 簽約 → 分配職位與預算 → 製作 → 發行 → 市場表現與獎季。合作 NPC 也必須有真實檔期。</p></header><div class="creative-new"><input id="creative-title" maxlength="30" placeholder="作品名稱">${Object.entries(CREATIVE_TYPES).map(([id,d])=>`<button data-creative-new="${id}">開始${d.label}</button>`).join("")}</div><section>${projects.length?projects.map(projectCard).join(""):`<p>目前還沒有自己的創作。先從一首 Demo、一份劇本或節目企劃開始。</p>`}</section></div>`}
