// 畫面層：角色建立流程（STEP 1 姓名／性別、STEP 2 能力擲骰）。開場唯一畫面，通過後才進入 roomView。
import{ABILITY_GROUPS}from"../data/abilities.js";
import{KNOWN_GENDERS,GENDER_OPTIONS}from"../data/genders.js";
import{AVATAR_LIST,portraitAsset,portraitThumbAsset}from"../data/wardrobe.js";
import{state}from"../core/state.js";
import{esc,width}from"../core/utils.js";

export function createView(){const best=Object.entries(state.stats).sort((a,b)=>b[1]-a[1]).slice(0,3);return `<main class="create-screen"><section class="create-art"><div class="logo">✦ 星途未定</div><img src="./assets/new-start-box.webp" alt="裝著表演用品的搬家紙箱"><div class="opening-copy"><span>序章｜18 歲的夏天</span><h1>帶著一箱夢想，<br>住進星望市。</h1><p>五年時間。沒有公司、沒有作品、沒有人脈。妳的明星人生，從這間小房間開始。</p></div></section><section class="create-form">${state.createStep===1?identityStep():statsStep(best)}</section></main>`}
export function identityStep(){const selected=AVATAR_LIST.find(a=>a.id===state.avatarId)||AVATAR_LIST[0];return `<div class="form-card identity-card"><div class="step-mark">STEP 1 / 2</div><h2>這位新人是誰？</h2><p>姓名、性別與立繪可以自由搭配，不會限制發展路線。</p><div class="identity-layout"><div class="identity-fields"><label><span>姓名／藝名</span><input id="player-name" maxlength="16" placeholder="輸入名字" value="${esc(state.name)}"></label><fieldset><legend>性別／稱呼</legend><div class="gender-options">${GENDER_OPTIONS.map(g=>`<button class="${(g==="自訂"?!KNOWN_GENDERS.includes(state.gender):state.gender===g)?"active":""}" data-gender="${g}">${g}</button>`).join("")}</div></fieldset><label class="${KNOWN_GENDERS.includes(state.gender)?"hidden":""}"><span>自訂性別</span><input id="custom-gender" maxlength="20" value="${esc(state.customGender)}" placeholder="自由輸入"></label><div class="selected-avatar-copy"><b>已選擇此人物立繪</b><small>立繪不會限制性別、能力或發展路線。</small></div></div><div class="create-avatar-preview"><img src="${portraitAsset(selected.id,"newcomer")}" width="512" height="1024" decoding="async" fetchpriority="high" alt="目前選擇的玩家立繪"></div></div><fieldset><legend>玩家立繪</legend><div class="avatar-picker">${AVATAR_LIST.map((a,index)=>`<button class="${a.id===selected.id?"active":""}" data-avatar="${a.id}" aria-label="選擇第 ${index+1} 款人物立繪"><img src="${portraitThumbAsset(a.id,"newcomer")}" width="160" height="320" loading="lazy" decoding="async" alt=""><span aria-hidden="true">${a.id===selected.id?"✓ 已選擇":"選擇"}</span></button>`).join("")}</div></fieldset><button class="main-btn full" id="to-stats" ${state.name.trim()?"":"disabled"}>擲出初始能力 →</button></div>`}
export function statsStep(best){return `<div class="form-card wide"><div class="roll-title"><div><div class="step-mark">STEP 2 / 2</div><h2>命運發了這副牌</h2><p>21 項固定公開能力各自隨機 0～150。不滿意就繼續骰，重骰次數不限。</p></div><button class="reroll" id="reroll">↻ 全部重骰</button></div><div class="best-tags">${best.map(([n,v],i)=>`<span>目前強項 ${i+1}<b>${n} ${v}</b></span>`).join("")}<em>所有能力進入遊戲後的上限皆為 1000</em></div><div class="rolled-grid">${Object.entries(ABILITY_GROUPS).map(([group,names])=>`<section><h3>${group}</h3>${names.map(n=>`<div class="mini-stat"><span>${n}</span><i><b style="width:${width(state.stats[n])}%"></b></i><strong>${state.stats[n]}</strong></div>`).join("")}</section>`).join("")}</div><div class="form-actions"><button class="back-btn" id="back">← 修改身分</button><button class="main-btn" id="start">就用這組，搬進星望市 →</button></div></div>`}
