import{state}from"../core/state.js";
import{CG_GALLERY_ITEMS}from"../data/story-art.js";
import{NPC_LONGFORM_CHAPTERS}from"../data/longform-content.js";
import{HIDDEN_ROUTE_CHAPTERS}from"../logic/hidden-route.js";
import{esc}from"../core/utils.js";
const chapters=[...Object.values(NPC_LONGFORM_CHAPTERS).flat(),...HIDDEN_ROUTE_CHAPTERS.map(chapter=>({...chapter,id:`silver-route-${chapter.id}`}))];
const historyText=()=>JSON.stringify([state.eventHistory,state.npcStoryHistory,state.careerMemories,state.flags]);
export function galleryUnlocked(item){if(item.kind==="route"){const id=item.id.split(":")[1];return Boolean(state.relationships[id]?.romance&&state.relationships[id].romance!=="none")}if(item.kind==="milestone"){const relationships=Object.values(state.relationships||{}),text=historyText();return({"milestone:proposal":relationships.some(r=>["engaged","married"].includes(r.romance)),"milestone:wedding":relationships.some(r=>r.romance==="married"),"milestone:breakup":relationships.some(r=>r.romance==="broken")||/分手|分開|breakup/.test(text),"milestone:renewal":/續約|renewal|renew-/.test(text),"milestone:integrated":state.careerDoctrine?.year5?.id==="integrated","milestone:flagship":state.eventFlags?.some(x=>/^flagship:.*:signature$/.test(x))}[item.id]||false)}return Boolean(state.contentExposure?.[item.id]||historyText().includes(item.id))}
function replay(item){const chapter=chapters.find(x=>x.id===item.id);if(!chapter)return`<p>這張畫面記錄了已發生的關鍵時刻；完整細節保存在星途時間線。</p>`;return`<div class="gallery-replay"><p>${esc(chapter.text)}</p>${chapter.beats.map(beat=>`<section><small>${esc(beat.label)}</small><p>${esc(beat.text)}</p></section>`).join("")}</div>`}
export function galleryApp(){const filter=state.galleryFilter||"all",items=CG_GALLERY_ITEMS.filter(item=>filter==="all"||item.kind===filter),selected=CG_GALLERY_ITEMS.find(item=>item.id===state.gallerySelection),unlocked=CG_GALLERY_ITEMS.filter(galleryUnlocked).length;if(selected&&galleryUnlocked(selected))return`<div class="gallery-page"><button class="gallery-back" data-gallery-back>← 返回收藏</button><figure class="gallery-feature"><img src="${selected.art.src}" alt="${esc(selected.art.alt)}"><figcaption><span>STORY REPLAY</span><h2>${esc(selected.title)}</h2>${replay(selected)}</figcaption></figure></div>`;return`<div class="gallery-page"><header class="gallery-hero"><div><span>MEMORY ARCHIVE</span><h2>星途影像館</h2><p>CG 只會在你親自走過相應劇情後解鎖；點開已收藏畫面可重讀故事。</p></div><strong>${unlocked}／${CG_GALLERY_ITEMS.length}<small>已解鎖</small></strong></header><nav class="gallery-tabs" aria-label="影像分類">${[["all","全部"],["chapter","人物章節"],["route","關係路線"],["milestone","人生節點"]].map(([id,label])=>`<button class="${filter===id?"active":""}" data-gallery-filter="${id}" aria-pressed="${filter===id}">${label}</button>`).join("")}</nav><div class="gallery-grid">${items.map(item=>{const open=galleryUnlocked(item);return`<button class="${open?"unlocked":"locked"}" data-gallery-item="${item.id}" ${open?"":"disabled"}><img src="${item.art.src}" alt="" loading="lazy"><span>${open?esc(item.title):"尚未解鎖"}</span></button>`}).join("")}</div></div>`}
