import{JOB_BY_ID,JOB_CATALOG,JOB_CATEGORIES}from"../data/jobs-catalog.js";
import{state}from"../core/state.js";
import{money,esc,effectiveStat,outfitBonus}from"../core/utils.js";
import{availableJobs,jobState,qualification,auditionChance}from"../logic/job-engine.js";
import{successRateLabel}from"../core/utils.js";

export const jobWorkDaysText=(job=JOB_BY_ID[state.selectedJobId]||JOB_BY_ID.J001)=>job.workDays.map(i=>"一二三四五六日"[i]).join("、");

function requirementRows(job){return qualification(job).rows.map(row=>{const bonus=outfitBonus(row.name);return`<span class="${row.met?"met":"unmet"}"><b>${row.name}</b><small>目前 ${row.current}${bonus?`（服裝＋${bonus}）`:""}／需求 ${row.required}</small><em>${row.met?"符合":"未達"}</em></span>`}).join("")}

function listCard(job){const record=jobState(job.id),selected=state.selectedJobId===job.id,status={available:"可接取",applied:"待試鏡",audition:"試鏡中",failed:"未獲選",passed:"可簽約",active:"執行中",completed:"已完成",breached:"已違約"}[record.stage];return`<button class="job-catalog-card ${selected?"active":""}" data-select-job="${job.id}"><span>${"★".repeat(job.stars)}・${job.category}</span><b>${esc(job.title)}</b><small>${esc(job.client)}・${money(job.pay)}</small><em>${status}</em></button>`}

function actionPanel(job,record){const q=qualification(job);if(record.stage==="available")return`<button data-job-action="apply" data-job-id="${job.id}" ${q.training<q.trainingRequired?"disabled":""}>接取試鏡邀請</button>`;if(record.stage==="applied")return`<button data-job-action="start-audition" data-job-id="${job.id}">進入試鏡現場</button>`;if(record.stage==="audition")return`<div class="audition-room"><p>${esc(job.audition.prompt)}</p>${job.audition.choices.map(choice=>`<button data-audition-choice="${choice.id}" data-job-id="${job.id}"><b>${esc(choice.label)}</b><small>${esc(choice.note)}・${successRateLabel(auditionChance(job,choice.id))}</small></button>`).join("")}</div>`;if(record.stage==="failed")return`<button data-job-action="retry" data-job-id="${job.id}">重新準備試鏡</button>`;if(record.stage==="passed")return`<button data-job-action="sign" data-job-id="${job.id}">簽署通告合約</button>`;if(record.stage==="active")return`<div class="contract-dashboard"><p>剩餘 <b>${record.remainingSessions}</b> 次・第 ${record.deadlineWeek} 週截止</p><button data-job-action="schedule" data-job-id="${job.id}">排入下一個指定工作日</button></div>`;if(record.stage==="completed")return`<div class="contract-result"><h3>作品已完成</h3><p>已收錄進作品履歷，可在星途紀錄查看成果與獎項。</p></div>`;return`<div class="contract-result breached"><h3>通告已違約</h3><p>${esc(record.notice||"期限內未完成工作。")}</p></div>`}

export function jobsApp(){const unlocked=new Set(availableJobs().map(job=>job.id)),jobs=JOB_CATALOG.filter(job=>unlocked.has(job.id)||state.activeJobs[job.id]),job=JOB_BY_ID[state.selectedJobId]&& (unlocked.has(state.selectedJobId)||state.activeJobs[state.selectedJobId])?JOB_BY_ID[state.selectedJobId]:jobs[0],record=jobState(job.id),q=qualification(job);return`<div class="jobs-page multi-jobs"><aside class="job-catalog"><header><h3>通告中心</h3><small>${jobs.length} 份目前可查看・完成作品可解鎖更高星級</small></header><nav>${JOB_CATEGORIES.map(category=>`<span>${category}</span>`).join("")}</nav>${jobs.map(listCard).join("")}</aside><section class="job-detail"><div class="job-board-head"><div><span>${job.id}・${"★".repeat(job.stars)}・${job.category}</span><h2>${esc(job.title)}</h2><p>${esc(job.synopsis)}</p></div><strong>${money(job.pay)}</strong></div><dl class="job-sheet"><div><dt>委託方</dt><dd>${esc(job.client)}</dd></div><div><dt>執行次數</dt><dd>${job.sessions} 次</dd></div><div><dt>指定工作日</dt><dd>每週${jobWorkDaysText(job)}</dd></div><div><dt>期限</dt><dd>簽約後 ${job.deadlineWeeks} 週</dd></div><div><dt>最低訓練</dt><dd>${q.training}／${q.trainingRequired} 次</dd></div></dl><section class="qualification-panel"><div><span>試鏡資質需求</span><h3>${q.met?"資質完整":"仍有能力尚未達標"}</h3><p>${esc(job.audition.tip)}</p></div><div class="req-list">${requirementRows(job)}</div></section>${record.notice?`<div class="job-notice">${esc(record.notice)}</div>`:""}<div class="job-action">${actionPanel(job,record)}</div></section></div>`}
