import{state}from"../core/state.js";
import{esc}from"../core/utils.js";
import{careerRoute}from"../logic/career.js";
import{rumorLevelLabel}from"../logic/rumor-engine.js";
import{workArtFor}from"../data/work-art.js";

const list=items=>`<div class="log-list">${items.join("")}</div>`;
const marketBlock=()=>{const m=state.worldMarket;if(!m)return"";const rows=Object.entries(m.categoryHeat||{}).sort((a,b)=>b[1]-a[1]);return`<div class="inside-title"><div><span>INDUSTRY MARKET</span><h3>本週市場</h3></div><p>${esc(m.headline||"市場平穩")}</p></div>${list(rows.map(([name,heat])=>`<article><b>${esc(name)}</b><span>熱度 ${Math.round(heat)}</span><small>${heat>=70?"需求旺盛・機會多，但競爭也更激烈":heat<=35?"市場冷卻・案量偏少":"供需平穩"}</small></article>`))}`};
const ecosystemBlock=()=>{const persona=state.publicPersona?.label||"仍在形成中的公眾形象",rivals=[...(state.competitors||[])].filter(r=>r.status==="active").sort((a,b)=>(b.fame+b.momentum)-(a.fame+a.momentum)).slice(0,5),f=state.fandom,rumors=(state.rumors||[]).filter(r=>["active","confirmed"].includes(r.status));return`<div class="inside-title"><div><span>PUBLIC IMAGE</span><h3>市場眼中的你</h3></div><p>${esc(persona)}</p></div>${f?list([`<article><b>粉圈結構</b><span>總粉絲 ${state.fans}</span><small>核心粉 ${f.core}・一般粉 ${f.casual}・作品粉 ${f.workFans}・CP 粉 ${f.cpFans}・黑粉 ${f.haters}</small></article>`]):""}${rumors.length?`<div class="inside-title"><div><span>RUMOR WATCH</span><h3>目前傳聞</h3></div><p>${rumors.length} 則仍有討論度</p></div>${list(rumors.map(r=>`<article><b>${r.type==="romance"?"緋聞":"傳聞"}</b><span>${esc(rumorLevelLabel(r.evidence))}・熱度 ${r.heat}</span><small>${r.status==="confirmed"?"已確認":r.response?`已採取回應：${esc(r.response)}`:"尚未正式回應"}</small></article>`))}`:""}${rivals.length?`<div class="inside-title"><div><span>RIVAL WATCH</span><h3>同期競爭者</h3></div><p>目前聲勢前 ${rivals.length} 名</p></div>${list(rivals.map(r=>`<article><b>${esc(r.name)}</b><span>${esc(r.field)}・人氣 ${r.fame}</span><small>作品 ${r.works}・獎項 ${r.awards}・動能 ${r.momentum}</small></article>`))}`:""}`};
const weeklyMemory=week=>{const memory=week.memory||(state.careerMemories||[]).find(item=>item.week===week.week),resultText=week.results.map(result=>result.result).filter(Boolean);return`<details class="career-week" data-disclosure-key="career-week:${week.week}"><summary><b>第 ${week.week} 週・${esc(memory?.headline||"一週行程完成")}</b><span>${week.hospitalized?"住院／休養":week.results.filter(result=>result.success).length+" 次順利完成"}</span></summary><div><p>${esc(resultText.join(" ｜ ")||"這週以休養為主。")}</p>${memory?.newFlags?.length?`<ul>${memory.newFlags.map(flag=>`<li><b>${esc(flag.label)}</b>・${esc(flag.note)}</li>`).join("")}</ul>`:""}${memory?.relationships?.length?`<small>人物變化：${memory.relationships.map(rel=>esc(rel.name)).join("、")}</small>`:""}</div></details>`};
export function logApp(){
 const works=state.completedWorks||[],awards=state.awards||[];
 return `<div class="inside-page"><div class="inside-title"><div><span>CAREER LOG</span><h2>星途紀錄</h2></div><p>目前路線：${esc(careerRoute())}</p></div>
 ${marketBlock()}${ecosystemBlock()}
 ${works.length?`<div class="inside-title"><div><span>PORTFOLIO</span><h3>作品履歷</h3></div><p>${works.length} 部作品</p></div>${list([...works].reverse().map(work=>{const art=workArtFor(work);return`<article class="${art?"portfolio-work-card":""}">${art?`<img src="${art.src}" alt="${esc(art.alt)}" loading="lazy">`:""}<div><b>${"★".repeat(work.stars)} ${esc(work.title)}</b><span>品質 ${work.quality}</span><small>${esc(work.category)}・${esc(work.role)}${work.tags?.length?`・${work.tags.map(esc).join("／")}`:""}${work.careerLabels?.length?`・${work.careerLabels.map(esc).join("／")}`:""}・第 ${work.completedWeek} 週完成${work.lifecycle?`・${({opening:"首週上映",theatrical:"上映期",longtail:"長尾發酵",catalog:"片庫長尾"}[work.lifecycle.stage]||work.lifecycle.stage)}`:""}</small></div></article>`}))}`:""}
 ${awards.length?`<div class="inside-title"><div><span>AWARDS</span><h3>獎項紀錄</h3></div><p>${awards.length} 項</p></div>${list([...awards].reverse().map(award=>`<article><b>${esc(award.name)}</b><span>${esc(award.result)}</span><small>${esc(award.category)}・第 ${award.week} 週</small></article>`))}`:""}
 ${state.flags.length?`<div class="inside-title"><div><span>BUTTERFLY FLAGS</span><h3>重要旗標</h3></div><p>${state.flags.length} 項</p></div>${list([...state.flags].reverse().map(flag=>`<article><b>第 ${flag.week} 週</b><span>旗標</span><small>${esc(flag.label)}｜${esc(flag.note)}</small></article>`))}`:""}
 ${state.history.length?`<div class="inside-title"><div><span>WEEKLY LOG</span><h3>每週紀錄</h3></div><p>每一週的選擇、事件與改變都會留在這裡。</p></div><div class="career-weeks">${[...state.history].reverse().map(weeklyMemory).join("")}</div>`:`<div class="tablet-empty"><span>✦</span><h3>第一頁還是空白</h3><p>完成作品、獲得獎項或跑完第一週後，成果會整理在這裡。</p></div>`}</div>`;
}
