import { MAP_LOCATIONS, MAP_CATEGORIES } from "../data/map-locations.js";
import { DAYS } from "../data/calendar.js";
import { state } from "../core/state.js";
import { overseasEligibility } from "../logic/overseas.js";

MAP_LOCATIONS.airport.note="第二年後可展開海外發展；抵達後選『主動探索』挑戰徵選，選『專注體驗』參加影展／音樂節交流。";
const PURPOSES={全部:{label:"全部地點",test:()=>true},work:{label:"找試鏡／通告",test:l=>l.industry||/試鏡|通告|Casting|工作/.test(l.effect+l.note)},people:{label:"認識人物",test:l=>!!l.encounter},recover:{label:"恢復狀態",test:l=>!!l.recover},growth:{label:"能力成長",test:l=>!!l.gain}};
export function mapApp(){
 const selected=state.freeLocations[state.selectedDay],filter=state.mapFilter||"全部",purpose=state.mapPurpose||"全部",overseas=overseasEligibility(),favorites=new Set(state.favoriteLocations||[]);
 const locations=Object.entries(MAP_LOCATIONS).filter(([,l])=>(filter==="全部"||l.category===filter)&&(PURPOSES[purpose]?.test(l)??true));
 const available=Object.entries(MAP_LOCATIONS).filter(([id,l])=>!l.locked||id==="airport"&&overseas.unlocked).length,recent=(state.recentLocations||[]).filter(id=>MAP_LOCATIONS[id]).slice(0,4);
 return `<div class="map-page"><div class="map-intro"><div><span>STARWISH CITY・${available} 個可探索地點</span><h2>${DAYS[state.selectedDay]}想完成什麼？</h2><p>先選目的，再挑地點；產業公司會在行程當天真正打開工作／試鏡清單。</p></div><b>基本交通費 $300</b></div><section class="map-purpose"><span>依目的找地點</span>${Object.entries(PURPOSES).map(([id,p])=>`<button class="${purpose===id?"active":""}" data-map-purpose="${id}">${p.label}</button>`).join("")}</section>${recent.length?`<section class="map-recent"><span>最近前往</span>${recent.map(id=>`<button data-map-location="${id}">${MAP_LOCATIONS[id].icon} ${MAP_LOCATIONS[id].name}</button>`).join("")}</section>`:""}<nav class="map-filters">${MAP_CATEGORIES.map(c=>`<button class="${filter===c?"active":""}" data-map-filter="${c}">${c}</button>`).join("")}</nav><div class="city-map">${locations.map(([id,l])=>{const locked=l.locked&&!(id==="airport"&&overseas.unlocked),effect=id==="airport"?(overseas.unlocked?"海外影展、音樂節與公開徵選":overseas.requirements.filter(x=>!x.met).map(x=>`${x.label}（目前 ${x.current}）`).join("・")):l.effect;return`<article class="map-place ${locked?"locked":""} ${selected===id?"selected":""}"><button class="map-favorite ${favorites.has(id)?"active":""}" data-map-favorite="${id}" aria-label="收藏${l.name}">${favorites.has(id)?"★":"☆"}</button><button class="map-place-main" ${locked?"disabled":""} data-map-location="${id}"><i>${l.icon}</i><span><small>${l.area}・${l.category}</small><b>${l.name}</b><em>${l.note}</em><strong>${effect}</strong></span>${locked?`<u>完成條件後開放</u>`:`<u>${l.industry?"安排並在當天開啟工作櫃台":"選擇地點"} →</u>`}</button></article>`}).join("")}</div><aside class="map-tip">產業地點不是能力訓練的替代品：實際跑到公司時，會先進入該公司的 Casting Desk，再由你選要查看／申請的工作。</aside></div>`;
}
