import{NPCS}from"../data/npcs.js";
import{state}from"../core/state.js";
import{esc}from"../core/utils.js";

export function npcApp(){
 const ids=state.knownPeople.filter(id=>NPCS[id]);
 if(!ids.length)return `<div class="tablet-empty"><span>◈</span><h3>還沒有認識任何人</h3><p>人物檔案不會預先劇透。安排自由活動並選擇「主動探索」，真正相遇後才會收錄資料。</p><button data-go-free>去安排自由活動</button></div>`;
 const current=ids.includes(state.selectedNpc)?state.selectedNpc:ids[0],npc=NPCS[current],rel=state.relationships[current]||{closeness:0,trust:0,romance:"none"},familiar=state.familiarNpcs.includes(current);
 return `<div class="npc-dossier"><nav class="npc-list">${ids.map(id=>{const n=NPCS[id];return `<button class="${id===current?"active":""}" data-select-npc="${id}"><i style="--npc-accent:${n.accent}">${n.avatar}<img class="portrait-img" src="${n.thumb}" alt="" loading="lazy" onerror="this.remove()"></i><span><b>${esc(n.name)}</b><small>${esc(n.job)}</small></span></button>`}).join("")}</nav><section class="npc-profile"><div class="npc-figure" style="--npc-accent:${npc.accent}"><img src="${npc.portrait}" alt="${esc(npc.name)}立繪" loading="lazy"><span>已認識${familiar?"・似曾相識":""}</span></div><div class="npc-profile-copy"><header><span>PERSONAL FILE・${npc.age} 歲</span><h2>${esc(npc.name)}</h2><p>${esc(npc.bio)}</p></header><blockquote>「${esc(npc.speech)}」</blockquote><dl><div><dt>職業</dt><dd>${esc(npc.job)}</dd></div><div><dt>生日</dt><dd>${npc.birthday}</dd></div><div><dt>常出沒地點</dt><dd>${esc(npc.location)}</dd></div><div><dt>個性</dt><dd>${esc(npc.personality)}</dd></div><div><dt>喜歡</dt><dd>${esc(npc.likes)}</dd></div><div><dt>不喜歡</dt><dd>${esc(npc.dislikes)}</dd></div></dl><section class="relationship-panel"><div><span>好感</span><i><b style="width:${rel.closeness}%"></b></i><strong>${rel.closeness}／100</strong></div><div><span>信任</span><i><b style="width:${rel.trust}%"></b></i><strong>${rel.trust}／100</strong></div><small>戀愛狀態：${rel.romance==="none"?"尚未發展":esc(rel.romance)}・後續可透過行程、事件與合作推進</small></section></div></section></div>`;
}
