// 畫面層：行程規劃 App——本週任務提示、預算／疲勞預估、七天行事曆格子，以及常駐在同一頁的活動選單。
// 活動選單不再是要點某一天才彈出的抽屜：`state.selectedDay` 現在同時身兼「目前要排入哪一天」的游標，
// 點行事曆某一天可以把游標移過去，點活動選單則是直接套用到游標那天，套用後游標會自動往後移一天
// （見 bind/planner.js），所以連續點同一個活動可以依序把接下來的幾天填滿，不必每天都重新點一次日期。
import{ACTIONS}from"../data/actions.js";
import{FOCUSES}from"../data/focuses.js";
import{JOB}from"../data/job.js";
import{AGENCIES}from"../data/agencies.js";
import{MAP_LOCATIONS}from"../data/map-locations.js";
import{DAYS,SHORT}from"../data/calendar.js";
import{state}from"../core/state.js";
import{esc,money}from"../core/utils.js";
import{isAgencyContractActive}from"../logic/agency.js";
import{jobWorkDaysText}from"./jobs.js";

// 未簽約／自由藝人仍在累積簽約準備度；已簽約且合約有效則改成公司新人任務，獎勵不再是簽約進度。
export function weeklyTaskInfo(){if(isAgencyContractActive())return{label:"公司新人任務",desc:"訓練 2 天＋工作 1 次＋週末疲勞 ≤ 60",rewardText:"$2,000・業界評價＋2"};return{label:"準備簽約面談",desc:"訓練 2 天＋工作 1 次＋週末疲勞 ≤ 60",rewardText:"$1,500・簽約＋10%"}}
export function budget(){return state.schedule.reduce((s,id)=>s+ACTIONS[id].cost,0)}
export function forecastFatigue(){return state.schedule.reduce((s,id)=>Math.max(0,s+ACTIONS[id].fatigue),state.fatigue)}
export function plannerApp(){const spend=budget(),fat=forecastFatigue(),train=state.schedule.filter(id=>ACTIONS[id].type==="train").length,work=state.schedule.filter(id=>["work","job"].includes(ACTIONS[id].type)).length,task=weeklyTaskInfo();return `<div class="planner-app">${state.jobStage==="active"?`<button class="contract-alert" data-open-app="jobs"><span>進行中通告</span><b>晨露汽水形象廣告</b><strong>剩餘 ${state.jobRemaining} 次・第 ${state.jobDeadline} 週截止</strong><small>指定執行日：每週${jobWorkDaysText()}</small><em>查看合約 →</em></button>`:""}<div class="week-brief"><div><span>本週任務</span><b>${task.label}</b><small>${task.desc}</small></div><strong>獎勵<br><b>${task.rewardText}</b></strong></div><div class="focus-row"><span>本週策略</span>${Object.entries(FOCUSES).map(([id,f])=>`<button class="${state.focus===id?"active":""}" data-focus="${id}" title="${f.note}">${f.icon} ${f.label}</button>`).join("")}</div><div class="calendar-head"><div><b>八月・第 ${state.week} 週</b><small>點活動直接套用到下方游標所在的那天；也可以先點某一天把游標移過去</small></div><div><button id="copy" ${state.lastSchedule?"":"disabled"}>複製上週</button><button id="rest-all">全部休息</button></div></div><div class="ipad-calendar">${state.schedule.map((id,i)=>calendarDay(id,i)).join("")}</div><div class="week-check"><span>訓練 <b>${train}/2</b></span><span>工作 <b>${work}/1</b></span><span>預估疲勞 <b class="${fat>60?"bad":""}">${fat}</b></span><span>本週支出 <b class="${spend>state.money?"bad":""}">${money(spend)}</b></span><em>${spend>state.money?"預算不足，請調整行程":fat>60?"任務可能因疲勞過高而失敗":"本週任務條件可達成"}</em></div>${state.notice?`<div class="mini-toast">✓ ${esc(state.notice)}</div>`:""}${activityPicker()}</div>`}
export function calendarDay(id,i){const a=ACTIONS[id],freePlace=id==="free"&&state.mapLocation?MAP_LOCATIONS[state.mapLocation].name:null,interviewLabel=id==="agency_interview"&&state.agencyInterview?`${AGENCIES[state.agencyInterview.agencyId].shortName}面談`:null,dueDay=state.jobStage==="active"&&JOB.workDays.includes(i);return `<button class="calendar-cell ${state.selectedDay===i?"selected":""} ${dueDay?"due-day":""} ${id==="agency_interview"?"important-day":""}" data-day="${i}" ${dueDay?`title="通告指定工作日"`:id==="agency_interview"?`title="重要行程・經紀公司面談"`:""}><span>${i+1}<small>週${SHORT[i]}</small></span><i class="${a.type}">${a.icon}</i><b>${interviewLabel||freePlace||a.short}</b><em>${id==="agency_interview"?"不收費・重要行程":a.cost?money(a.cost):"免費"}${id==="adshoot"&&state.jobStage==="active"?`・剩 ${state.jobRemaining} 次`:""}</em></button>`}
export function activityPicker(){const entries=Object.entries(ACTIONS).filter(([id,a])=>id!=="agency_interview"&&(id!=="adshoot"||state.jobStage==="active")&&(state.filter==="全部"||a.group===state.filter));return `<section class="activity-picker"><header><div><span>接下來排入</span><b>${DAYS[state.selectedDay]}</b></div><nav>${["全部","訓練","工作","生活","休息"].map(f=>`<button class="${state.filter===f?"active":""}" data-filter="${f}">${f}</button>`).join("")}</nav></header><div class="picker-list">${entries.map(([id,a])=>{const unavailable=id==="adshoot"&&!JOB.workDays.includes(state.selectedDay);return `<button class="${state.schedule[state.selectedDay]===id?"active":""} ${unavailable?"unavailable":""}" data-pick="${id}" ${unavailable?"disabled":""}><i class="${a.type}">${a.icon}</i><span><b>${a.label}</b><small>${unavailable?`此通告僅能排在每週${jobWorkDaysText()}`:a.note}</small></span><em>${a.cost?money(a.cost):"免費"}<small>疲勞 ${a.fatigue>0?"+":""}${a.fatigue}</small></em></button>`}).join("")}</div></section>`}
