// 畫面層：新人房間（主畫面）——玩家資訊列、桌面捷徑、平板首頁／底部 Dock，以及點開任一 App 的彈出視窗。
// appWindow() 是唯一知道「App id → 對應畫面函式」對照表的地方，是本檔案匯入其他所有 App 畫面模組的原因。
import{AGENCIES,AGENCY_LIST}from"../data/agencies.js";
import{state}from"../core/state.js";
import{esc,money,yearOf,weekInYear}from"../core/utils.js";
import{portraitThumbAsset}from"../data/wardrobe.js";
import{isAgencyContractActive,checkAgencyEligibility}from"../logic/agency.js";
import{budget,plannerApp}from"./planner.js";
import{statsApp}from"./stats-app.js";
import{peopleApp}from"./people.js";
import{logApp}from"./log.js";
import{mapApp}from"./map.js";
import{jobsApp}from"./jobs.js";
import{npcApp}from"./npc.js";
import{agencyApp}from"./agency.js";
import{wardrobeApp}from"./wardrobe.js";

export function playerIdentityLabel(){if(isAgencyContractActive())return`${esc(AGENCIES[state.currentAgencyId].name)}・旗下新人`;if(state.agencyStatus==="expired")return"自由藝人";return"未簽約新人"}
export function roomView(){return `<main class="room-screen"><img class="room-bg" src="./assets/rookie-room.webp" width="1536" height="1024" decoding="async" fetchpriority="high" alt="新人租屋處的工作桌"><header class="room-hud"><div class="player-chip"><div>${esc(state.name.slice(0,1))}<img class="portrait-img" src="${portraitThumbAsset(state.avatarId,state.outfitId)}" width="160" height="320" decoding="async" alt="玩家目前造型"></div><span><b>${esc(state.name)}</b><small>18 歲・${playerIdentityLabel()}</small></span></div><div class="hud-stats"><span>💰 <b>${money(state.money)}</b></span><span>★ 知名度 <b>${state.fame}</b></span><span>♡ 粉絲 <b>${state.fans}</b></span><span>☁ 疲勞 <b>${state.fatigue}</b></span></div></header><button class="desk-pin phone-pin" data-open-app="people"><i>1</i><b>手機</b><small>${state.knownPeople.length?"查看聯絡人":"新的城市，空白通訊錄"}</small></button><button class="desk-pin mail-pin" data-open-job><i>!</i><b>通告信封</b><small>新人廣告試鏡・本週截止</small></button><section class="tablet"><div class="tablet-camera"></div><div class="tablet-screen">${tabletHome()}${tabletDock()}</div></section>${state.appOpen?appWindow():""}</main>`}
export function agencyHomeCard(){if(isAgencyContractActive()){const agency=AGENCIES[state.currentAgencyId],remain=Math.max(0,state.agencyContractEndWeek-state.week+1);return `<button class="agency-entry" data-open-app="agency"><div><span>所屬經紀公司</span><b>${esc(agency.name)}</b></div><small>合約剩餘 <b>${remain}</b> 週・經紀抽成 <b>${Math.round(agency.contract.commissionRate*100)}%</b></small><small class="agency-entry-cta">查看公司資料 →</small></button>`}const eligible=AGENCY_LIST.filter(a=>checkAgencyEligibility(a).met).length;if(state.agencyStatus==="expired")return `<button class="agency-entry" data-open-app="agency"><div><span>經紀公司</span><b>自由藝人</b></div><small>合約已到期・目前身分：自由藝人</small><small class="agency-entry-cta">可查看／投遞 ${eligible}／${AGENCY_LIST.length} 間公司 →</small></button>`;return `<button class="agency-entry" data-open-app="agency"><div><span>經紀公司</span><b>${state.contract}%</b></div><i><b style="width:${state.contract}%"></b></i><small>簽約準備度・目前身分：未簽約新人</small><small class="agency-entry-cta">可查看／投遞 ${eligible}／${AGENCY_LIST.length} 間公司 →</small></button>`}
export function tabletHome(){return `<div class="tablet-home"><header><span>第 ${yearOf()} 年・第 ${weekInYear()} 週</span><b>${esc(state.name)}，早安！</b><small>今天先從安排這一週開始吧。</small></header>${agencyHomeCard()}<button class="next-action" data-open-app="planner"><span>下一步</span><b>安排第 ${state.week} 週行程</b><small>7 天尚未開始・預計支出 ${money(budget())}</small><i>→</i></button><div class="home-launchers"><button data-open-app="map"><b>⌖ 星望市地圖</b><small>選擇自由活動地點</small></button><button data-open-app="jobs"><b>▤ 通告中心</b><small>${state.jobStage==="available"?"1 份新邀約":state.jobStage==="active"?`剩餘 ${state.jobRemaining} 次拍攝`:"查看試鏡進度"}</small></button><button data-open-app="npc"><b>◈ 人物檔案</b><small>已認識人物的資料與關係</small></button><button data-open-app="wardrobe"><b>♢ 造型衣櫃</b><small>換裝並調整能力加成</small></button></div><button class="retire-link" data-retire>結束這一輪，查看星途結算（測試用）→</button></div>`}
export function tabletDock(){return `<nav class="tablet-dock">${[["planner","▦","行程"],["stats","◫","能力"],["wardrobe","♢","衣櫃"],["people","♡","人際"],["log","≡","紀錄"]].map(([id,icon,label])=>`<button data-open-app="${id}"><i>${icon}</i>${label}</button>`).join("")}</nav>`}
export function appWindow(){const meta={planner:["▦","行程與工作","安排七天行程、策略與預算"],stats:["◫","能力資料","檢視 21 項公開能力與隱藏特質線索"],wardrobe:["♢","造型衣櫃","切換人物立繪、購買服裝與套用能力加成"],people:["♡","手機與人際","查看聯絡人和關係進度"],log:["≡","星途紀錄","回顧每週成果與重大選擇"],map:["⌖","星望市地圖","選擇自由活動要前往的地點"],jobs:["▤","通告中心","接取邀約、參加試鏡與管理合約"],npc:["◈","人物檔案","已認識人物的資料與關係"],agency:["◆","經紀公司","查看公司資料、投遞、面談與簽約進度"]}[state.appOpen];const views={planner:plannerApp,stats:statsApp,wardrobe:wardrobeApp,people:peopleApp,log:logApp,map:mapApp,jobs:jobsApp,npc:npcApp,agency:agencyApp};const body=views[state.appOpen]();return `<div class="app-backdrop" data-close-app></div><section class="app-window ${state.appOpen}"><header class="window-bar"><div class="window-icon">${meta[0]}</div><div><h2>${meta[1]}</h2><p>${meta[2]}</p></div>${state.appOpen==="planner"?`<button class="window-start" id="begin-week">開始這週 →</button>`:""}<button class="window-close" data-close-app aria-label="關閉">×</button></header><div class="window-body">${body}</div></section>`}
