// 畫面層：逐日事件畫面。一般行程會自動從 loading → result → 下一天；需要選擇時才暫停。
import{ACTIONS}from"../data/actions.js";
import{DAYS,SHORT}from"../data/calendar.js";
import{state}from"../core/state.js";
import{money}from"../core/utils.js";
export function runnerView(){const i=state.runnerDay,a=ACTIONS[state.schedule[i]];return `<main class="event-screen"><img src="./assets/star-city-street.webp" alt="星望市娛樂街景"><div class="event-top"><div class="logo dark">✦ 星途未定</div><div>${state.week} 週・DAY ${i+1}　${DAYS[i]}</div><div>體力 ${state.stamina}　疲勞 ${state.fatigue}</div></div><div class="day-track">${DAYS.map((d,x)=>`<i class="${x<i?"done":x===i?"now":""}">${x<i?"✓":x+1}<small>${SHORT[x]}</small></i>`).join("")}</div><section class="story-box"><div class="story-action"><i>${a.icon}</i><span><small>今日行程</small><b>${a.label}</b><em>${a.note}</em></span></div>${state.runnerPhase==="loading"?`<div class="story-loading"><i></i><b>今天正在發生……</b><small>一般行程會自動結算並進入下一天</small></div>`:state.runnerPhase==="decision"?decisionView():resultView()}</section></main>`}
function relationshipCues(data){return data?.relationshipCues?.length?`<div class="relationship-float-layer" aria-live="polite">${data.relationshipCues.map((cue,index)=>`<span class="${cue.kind}" style="--cue-delay:${index*.18}s" aria-label="${cue.label}" title="${cue.label}"><i>${cue.symbol}</i><small>${cue.label}</small></span>`).join("")}</div>`:""}
function npcArt(data){return data?.portrait?`<figure class="runner-npc-art" style="--npc-accent:${data.accent||"#c77880"}"><img src="${data.portrait}" alt="${data.npcName||"NPC"}半身立繪" loading="eager">${relationshipCues(data)}<figcaption>${data.npcName||""}</figcaption></figure>`:""}
export function decisionView(){const d=state.runnerDecision;return `<div class="decision ${d.kind==="npc_interaction"?"npc-interaction-decision":""}">${npcArt(d)}<div class="runner-scene-copy"><span>CHOICE・自動播放暫停</span><h2>${d.title}</h2><p>${d.text}</p><div>${d.choices.map(c=>`<button data-choice="${c.id}"><b>${c.label}</b><small>${c.note}</small></button>`).join("")}</div></div></div>`}
export function resultView(){const r=state.runnerResult,next=state.runnerDay===6?"本週總結":DAYS[state.runnerDay+1],note=r.portrait?"閱讀完這段相處，再親自決定繼續。":`即將自動進入${next}……`;return `<div class="day-result ${r.success?"success":"fail"} ${r.portrait?"npc-interaction-result":""}">${npcArt(r)}<div class="runner-scene-copy"><span>${r.success?"RESULT・SUCCESS":"RESULT・EXPERIENCE"}</span><h2>${r.title}</h2><div class="day-result-copy">${r.text}</div><div class="day-result-stats"><b>💰 ${money(state.money)}</b><b>★ 知名度 ${state.fame}</b><b>♡ 粉絲 ${state.fans}</b></div><p class="runner-auto-note">${note}</p><button class="main-btn" id="next-day">${state.runnerDay===6?"查看本週總結":"進入"+next} →</button></div></div>`}
