import{state}from"../core/state.js";
import{getPreferences}from"../core/preferences.js";
import{TUTORIALS}from"../logic/tutorial.js";
import{saveSlotCards}from"./save.js";
import{esc}from"../core/utils.js";
const option=(kind,id,current,icon,title,note)=>`<button class="setting-option ${current===id?"active":""}" data-${kind}="${id}"><i>${icon}</i><span><b>${title}</b><small>${note}</small></span>${current===id?"<em>使用中</em>":""}</button>`;
const slider=(name,label,value)=>`<label class="audio-slider"><span>${label}<b>${Math.round(value*100)}%</b></span><input type="range" min="0" max="100" value="${Math.round(value*100)}" data-audio-volume="${name}"></label>`;
export function settingsApp(){
 const prefs=getPreferences(),seen=new Set(state.tutorialSeen||[]),confirm=state.settingsConfirmReset;
 return`<div class="inside-page settings-page"><div class="inside-title"><div><span>GAME SETTINGS</span><h2>遊戲設定</h2></div><p>顯示與播放偏好會保留在這台裝置，不受讀檔影響</p></div>${state.saveNotice?`<div class="wardrobe-notice">${esc(state.saveNotice)}</div>`:""}<section class="settings-section"><header><span>DISPLAY</span><h3>字體大小</h3><p>全介面使用一致的中文黑體，敘事標題使用同一套中文襯線字。</p></header><div class="setting-options">${option("font-size","standard",prefs.fontSize,"A","標準","原始排版")}${option("font-size","comfortable",prefs.fontSize,"A+","舒適","內文至少 16px")}${option("font-size","large",prefs.fontSize,"A++","大字","內文至少 18px")}</div></section><section class="settings-section"><header><span>THEME</span><h3>介面主題</h3><p>保留水彩素材，只調整平板、視窗與按鈕色調。</p></header><div class="setting-options themes">${option("theme","warm",prefs.theme,"☀","奶油晨光","原始米白與珊瑚粉")}${option("theme","rose",prefs.theme,"❀","櫻花手帳","柔粉紙張與莓果色")}${option("theme","night",prefs.theme,"☾","夜幕星光","深藍灰低亮度介面")}</div></section><section class="settings-section"><header><span>PLAYBACK</span><h3>自動播放速度</h3><p>需要選擇或有人物立繪時仍會暫停。</p></header><div class="setting-options playback-speeds">${option("auto-speed","x1",prefs.autoSpeed,"1×","舒緩閱讀","每段停留 10 秒")}${option("auto-speed","x2",prefs.autoSpeed,"2×","快速播放","每段仍保留 5 秒")}</div></section><section class="settings-section"><header><span>AUDIO</span><h3>音樂與音效</h3><p>音樂會依房間、事件、行程與結局切換；首次點擊後開始播放。</p></header>${slider("musicVolume","背景音樂",prefs.musicVolume)}${slider("sfxVolume","操作音效",prefs.sfxVolume)}<button class="settings-link" data-audio-muted>${prefs.audioMuted?"開啟聲音":"全部靜音"}</button></section><section class="settings-section"><header><span>SAVE / LOAD</span><h3>快速存檔與讀檔</h3><p>讀檔前會自動建立安全備份；匯出、匯入與備份還原請進完整管理。</p></header>${saveSlotCards()}<button class="settings-link" data-open-save-manager>開啟完整存檔管理 →</button></section><section class="settings-section"><header><span>TUTORIAL</span><h3>新手教學</h3><p>目前已看過 ${seen.size}／${TUTORIALS.length} 則教學提示。</p></header><div class="settings-inline-actions"><button data-tutorial-mode="restart">重新顯示所有教學</button><button data-tutorial-mode="skip">關閉所有後續教學</button></div></section><section class="settings-section danger-zone"><header><span>NEW GAME</span><h3>從頭開始</h3><p>目前進度會先放進安全備份，再回到角色建立畫面；手動存檔與顯示設定不會刪除。</p></header>${confirm?`<div class="reset-confirm"><b>確定要結束 ${esc(state.name)} 的目前進度嗎？</b><p>自動存檔將被新的角色進度取代，但仍可從安全備份或手動槽位找回。</p><div><button data-cancel-reset>取消</button><button class="danger" data-confirm-reset>確認從頭開始</button></div></div>`:`<button class="reset-game" data-request-reset>從頭開始建立角色</button>`}</section></div>`;
}
