import{OFFICIAL_SOCIAL_POSTS,NPC_SOCIAL_COPY,SOCIAL_POST_TEMPLATES}from"../data/social.js";
import{NPCS}from"../data/npcs.js";
import{DAYS}from"../data/calendar.js";
import{state}from"../core/state.js";
import{esc}from"../core/utils.js";
import{publicOpinionLabel,publicOpinionSnapshot}from"../logic/reputation-engine.js";
import{socialReplyOptions}from"../logic/community-interactions.js";
function postCard(post){const liked=state.likedSocialPosts.includes(post.id),comments=post.comments||[],replied=post.npcId&&state.socialReplies?.[`${state.week}:${post.npcId}`];return `<article class="social-post ${post.pending?"pending":""}"><header><i>${post.image?`<img src="${post.image}" alt="" loading="lazy">`:esc(post.avatar||"✦")}</i><div><b>${esc(post.name)}</b><small>${post.badge}・第 ${post.week||state.week} 週</small></div>${post.pending?`<em>排程中</em>`:""}</header><p>${esc(post.text)}</p><footer>${post.pending?`<span>◷ 將於行程執行後正式發布</span>`:`<button class="${liked?"liked":""}" data-social-like="${post.id}">♡ ${(post.likes||0)+(liked?1:0)}</button><span>回覆 ${comments.length}</span>`}</footer>${post.npcId?`<div class="social-reply-actions">${replied?`<span>✓ 已用「${esc(socialReplyOptions()[replied]?.label||"回覆")}」和對方互動</span>`:Object.entries(socialReplyOptions()).map(([id,option])=>`<button data-social-reply="${post.npcId}" data-reply-type="${id}">${esc(option.label)}</button>`).join("")}</div>`:""}${comments.length?`<div class="social-comments">${comments.slice(0,3).map(c=>`<p><b>${esc(typeof c==="string"?"網友":c.name)}</b> ${esc(typeof c==="string"?c:c.text)}</p>`).join("")}</div>`:""}</article>`}
function feed(){const scheduled=Object.values(state.scheduledActivities||{}).filter(a=>a.week===state.week&&a.status==="scheduled"&&a.kind==="social_post").map(a=>{const t=SOCIAL_POST_TEMPLATES[a.payload?.type];return{id:`scheduled-${a.id}`,name:state.name,badge:`預定發布・${DAYS[a.day]}`,avatar:state.name.slice(0,1),week:state.week,text:t?.text||a.label,comments:[],pending:true}});const own=state.socialPosts.map(p=>({...p,name:state.name,badge:"本人",avatar:state.name.slice(0,1)}));const news=(state.industryNews||[]).slice(0,8).map(n=>({id:`social-${n.id}`,name:"星望娛樂快訊",badge:n.category,avatar:"✦",week:n.week,text:`${n.title}｜${n.body}`,likes:Math.max(30,Math.round((n.heat||50)/2)),comments:["這週娛樂圈好多事。","先卡，等後續。"]}));const npc=state.knownPeople.filter(id=>NPCS[id]&&NPC_SOCIAL_COPY[id]).map((id,i)=>{const n=NPCS[id],career=state.npcCareers?.[id],suffix=career?.trend==="up"?" 最近的新工作似乎進展得很順利。":career?.trend==="down"?" 這週先把步調放慢一點。":"";return{id:`npc-${id}`,npcId:id,name:n.name,badge:n.job,avatar:n.avatar,image:n.head,text:NPC_SOCIAL_COPY[id]+suffix,likes:86+i*37+state.week*3,comments:["工作辛苦了！","期待下次更新。"]}});return[...scheduled,...own,...news,...npc,...OFFICIAL_SOCIAL_POSTS]}
export function socialApp(){const estimated=Math.max(12,state.fans+state.fame*4),op=publicOpinionSnapshot();return `<div class="social-page"><header class="social-profile"><i>${esc(state.name.slice(0,1))}</i><div><span>@star_${esc(state.name.toLowerCase().replace(/\s/g,""))||"newcomer"}</span><h2>${esc(state.name)}</h2><p>新人藝人・${publicOpinionLabel()}・品牌信任 ${op.brandTrust}</p></div><dl><div><b>${state.socialPosts.length}</b><small>貼文</small></div><div><b>${estimated}</b><small>追蹤者</small></div><div><b>${op.heat}</b><small>話題熱度</small></div></dl></header><section class="social-compose"><b>分享近況</b><div>${Object.entries(SOCIAL_POST_TEMPLATES).map(([id,t])=>`<button data-social-post="${id}"><i>${t.icon}</i><span><b>${t.label}</b><small>${t.text}</small></span></button>`).join("")}</div>${state.socialNotice?`<p>${esc(state.socialNotice)}</p>`:""}</section><div class="social-feed">${feed().map(postCard).join("")}</div></div>`}
