import{NPCS}from"../data/npcs.js";import{state}from"../core/state.js";import{money,esc}from"../core/utils.js";import{isAgencyContractActive}from"../logic/agency.js";import{romanceStageLabel}from"../logic/romance-engine.js";import{memoryForWeek}from"../logic/career-memory.js";import{yearTransitionForWeek}from"../data/season-art.js";
import{workArtFor}from"../data/work-art.js";
const delta=value=>`${value>0?"＋":""}${value}`;
function changeChips(memory){if(!memory)return"";const items=[...memory.metrics,...memory.stats.slice(0,4),...memory.reputation.slice(0,3)].filter(item=>item.value);return items.length?`<div class="week-change-chips">${items.map(item=>`<span class="${item.value<0?"down":"up"}">${item.label} <b>${delta(item.value)}</b></span>`).join("")}</div>`:`<p class="week-no-change">這週沒有明顯數值變化，但時間與選擇仍被記進星途紀錄。</p>`}
export function eventRecapText(event){const parts=[event.choiceLabel,event.outcome].filter(value=>typeof value==="string"&&value.trim());return parts.length?parts.map(esc).join("・"):"這段經歷已寫入本輪紀錄。"}
function storyRecap(memory){if(!memory)return"";const stories=[];memory.newEvents.forEach(event=>stories.push(`<article><i>✦</i><div><small>事件結果</small><b>${esc(event.title)}</b><p>${eventRecapText(event)}</p></div></article>`));memory.relationships.forEach(rel=>stories.push(`<article><i>♡</i><div><small>人物關係</small><b>${esc(rel.name)}</b><p>${rel.romanceFrom!==rel.romanceTo?"關係進入新的階段":"這週的相處改變了彼此的距離與信任"}</p></div></article>`));memory.newWorks.forEach(work=>{const art=workArtFor(work);stories.push(`<article class="${art?"week-work-unlock":""}">${art?`<img src="${art.src}" alt="${esc(art.alt)}">`:`<i>★</i>`}<div><small>${art?"NEW KEY ART UNLOCKED":"作品履歷"}</small><b>《${esc(work.title)}》</b><p>${esc(work.category)}・${esc(work.role)}・品質 ${work.quality}</p></div></article>`)});memory.newAwards.forEach(award=>stories.push(`<article><i>♛</i><div><small>獎項</small><b>${esc(award.name)}</b><p>《${esc(state.completedWorks.find(work=>work.id===award.workId)?.title||"作品")}》${esc(award.result)}</p></div></article>`));return stories.length?`<section class="week-story-recap"><h2>這週真正留下的事</h2>${stories.join("")}</section>`:""}
function yearCard(transition){return transition?`<section class="year-transition-card"><img src="${transition.art.src}" alt="${transition.art.alt}"><div><span>YEAR ${transition.year} COMPLETE</span><h2>${transition.title}</h2><p>${transition.text}</p></div></section>`:""}
export function summaryView(){const ok=state.weekResults.filter(r=>r.success).length,nextWeek=state.week+1,forced=state.forcedRestWeek===nextWeek,memory=memoryForWeek(),transition=yearTransitionForWeek(state.week),background=transition?.art||{src:"./assets/rookie-room.webp",alt:"新人房間"},thirdStat=isAgencyContractActive()?`<div><small>合約剩餘</small><b>${Math.max(0,state.agencyContractEndWeek-state.week+1)} 週</b></div>`:state.agencyStatus==="expired"?`<div><small>目前身分</small><b>自由藝人</b></div>`:`<div><small>簽約進度</small><b>${state.contract}%</b></div>`;return`<main class="summary-screen"><img src="${background.src}" alt="${background.alt}"><section class="summary-paper rich-summary">${yearCard(transition)}<span>WEEK ${state.week} COMPLETE・${esc(memory?.focusLabel||"本週回顧")}</span><h1>${esc(state.reward.title)}</h1><p>${esc(state.reward.text)}</p><div class="reward-status"><div><small>順利完成</small><b>${ok}/7</b></div><div><small>現有存款</small><b>${money(state.money)}</b></div>${thirdStat}<div><small>目前疲勞</small><b>${state.fatigue}</b></div></div>${changeChips(memory)}<div class="week-recap detailed">${state.weekResults.map(r=>`<details data-disclosure-key="week-result:${state.week}:${esc(r.day)}"><summary><span>${esc(r.day)}</span><b>${esc(r.action)}</b><em>${r.success?"順利完成":"累積經驗"}</em></summary><p>${esc(r.result||"這天的經歷已經記錄。")}</p></details>`).join("")}</div>${storyRecap(memory)}<button class="main-btn" id="next-week">${forced?`進入第 ${nextWeek} 週強制休養`:`回到房間，開始第 ${nextWeek} 週`} →</button></section></main>`}
export function relationshipSummary(){const entries=Object.entries(state.relationships).filter(([id,r])=>state.knownPeople.includes(id)&&r.romance&&r.romance!=="none");return entries.length?entries.map(([id,r])=>`${NPCS[id].name}｜${romanceStageLabel(r.romance)}${r.visibility==="public"?"（公開）":r.visibility==="underground"?"（地下戀）":""}`).join("・"):"尚未建立戀愛關係"}
