import{state}from"../core/state.js";
import{AGENCIES}from"../data/agencies.js";
import{managerForAgency}from"../data/managers.js";
import{availableJobs,jobState}from"./job-engine.js";
import{randomInt}from"../core/rng.js";
const agencyCategoryMap={戲劇:["電影","電視劇"],廣告:["廣告"],綜藝:["綜藝"],音樂:["歌曲"]};
function yearlyGuaranteedTarget(){return Math.max(0,state.agencyContractTerms?.guaranteedAuditions||0)}
function guaranteedOffersThisContractYear(){const start=state.agencySignedWeek||state.week,yearStart=start+Math.floor(Math.max(0,state.week-start)/52)*52;return(state.agencyJobOffers||[]).filter(o=>o.agencyId===state.currentAgencyId&&o.guaranteed&&o.offeredWeek>=yearStart).length}
export function refreshAgencyJobOffers(){state.agencyJobOffers=(state.agencyJobOffers||[]).filter(o=>o.expiresWeek>=state.week&&!['completed','breached'].includes(jobState(o.jobId).stage));if(!state.currentAgencyId||state.week>state.agencyContractEndWeek)return state.agencyJobOffers;const agency=AGENCIES[state.currentAgencyId];if(!agency)return state.agencyJobOffers;const manager=managerForAgency(agency.id),support=manager?.support||{},range=support.offerRange||[2,4],expiry=Math.max(1,support.offerExpiryWeeks||1),existing=new Set(state.agencyJobOffers.filter(o=>o.expiresWeek>=state.week).map(o=>o.jobId)),favored=new Set((agency.specialties||[]).flatMap(x=>agencyCategoryMap[x]||[x]));const pool=availableJobs().filter(j=>jobState(j.id).stage==="available"&&!existing.has(j.id)).sort((a,b)=>(favored.has(b.category)?2:0)-(favored.has(a.category)?2:0)||b.stars-a.stars);const target=yearlyGuaranteedTarget(),used=guaranteedOffersThisContractYear(),remaining=Math.max(0,target-used),weeksLeft=Math.max(1,52-((state.week-(state.agencySignedWeek||state.week))%52)),mustGuarantee=remaining>0&&(remaining>=weeksLeft||randomInt(1,weeksLeft)<=remaining),baseCount=randomInt(range[0],range[1]),count=Math.min(pool.length,Math.max(baseCount,mustGuarantee?1:0));for(const[jobIndex,job]of pool.slice(0,count).entries())state.agencyJobOffers.push({jobId:job.id,agencyId:agency.id,managerId:manager?.id||null,offeredWeek:state.week,expiresWeek:state.week+expiry,guaranteed:Boolean(mustGuarantee&&jobIndex===0)});return state.agencyJobOffers}
export function activeAgencyOffer(jobId){return(state.agencyJobOffers||[]).find(o=>o.jobId===jobId&&o.expiresWeek>=state.week)||null}
