import{state}from"../core/state.js";
const ROUTES={歌曲:"唱作歌手",電影:"電影演員",電視劇:"國民演員",綜藝:"綜藝主持",廣告:"商業明星"};
export const ENDING_ARCHETYPES=Object.freeze([
 {id:"death",label:"燃盡的星光"},{id:"storm_icon",label:"風暴中心"},{id:"whole_life",label:"完整人生"},{id:"legacy_builder",label:"把門留在身後"},{id:"people_first",label:"散場後仍有人等你"},{id:"masterpiece_vow",label:"五年只為這一幕"},{id:"creative_auteur",label:"自己的名字就是片頭"},{id:"award_collector",label:"獎櫃放不下的人"},{id:"national_darling",label:"國民記憶"},{id:"commercial_king",label:"品牌爭奪戰"},{id:"soulmate",label:"星光之外的重要的人"},{id:"power_couple",label:"並肩站上紅毯"},{id:"multi_hyphenate",label:"斜槓巨星"},{id:"cult_artist",label:"圈內人的圈內人"},{id:"wealthy_exit",label:"漂亮轉身"},{id:"workhorse",label:"片尾名單裡總有你"},{id:"breakout",label:"下一站，一線"},{id:"steady",label:"站穩腳步"},{id:"unfinished",label:"未完待續"}
]);
export function careerRoute(){const entries=Object.entries(state.careerProgress||{}).sort((a,b)=>b[1]-a[1]);const[a,b]=entries;if(!a||a[1]<150)return"仍在尋找方向的新人";if(b&&b[1]>=a[1]*.82)return`${ROUTES[a[0]]} × ${ROUTES[b[0]]}`;return ROUTES[a[0]]}
export function recordCareerRoute(){const route=careerRoute(),last=state.careerRouteHistory.at(-1);if(!last||last.route!==route)state.careerRouteHistory.push({week:state.week,route});return route}
export function endingSnapshot(trigger=state.endingType||"fiveyear"){const relEntries=Object.entries(state.relationships||{}).sort(([aId,a],[bId,b])=>Number(bId===state.partnerId)-Number(aId===state.partnerId)||(b.affection||0)-(a.affection||0)||(b.closeness+b.trust)-(a.closeness+a.trust));return structuredClone({trigger,week:state.week,name:state.name,realName:state.realName,stageName:state.stageName,route:careerRoute(),money:state.money,fame:state.fame,fans:state.fans,rep:state.rep,completedWorks:state.completedWorks,awards:state.awards,careerProgress:state.careerProgress,careerRouteHistory:state.careerRouteHistory,careerDoctrine:state.careerDoctrine,majorDecisionHistory:state.majorDecisionHistory,bestRelationship:relEntries[0]?{npcId:relEntries[0][0],...relEntries[0][1]}:null,flags:state.flags,eventFlags:state.eventFlags})}
function endingArchetype({trigger,snapshot,portfolio,awardWins,score,route,bestRel}){const originals=portfolio.originals,rep=snapshot.rep||{},legacy=snapshot.careerDoctrine?.year5?.id;if(trigger==="death")return"death";if((rep.爭議度||0)>=650&&(snapshot.fame>=450||snapshot.fans>=100000))return"storm_icon";if(legacy==="integrated"&&portfolio.works>=10)return"whole_life";if(legacy==="legacy" && (rep.可信度||0)>=700)return"legacy_builder";if(legacy==="people" && bestRel?.closeness>=30)return"people_first";if(legacy==="masterpiece" && portfolio.bestWork?.quality>=90)return"masterpiece_vow";if(originals>=5&&portfolio.works>=8&&(rep.業界評價||0)>=450)return"creative_auteur";if(awardWins>=5)return"award_collector";if((rep.國民度||0)>=750&&(rep.路人緣||0)>=700)return"national_darling";if((rep.商業價值||0)>=800&&snapshot.money>=1500000)return"commercial_king";if(["committed","engaged","married"].includes(bestRel?.romance)&&bestRel.closeness>=85&&bestRel.trust>=75&&(bestRel.affection||0)>=78)return snapshot.fame>=500?"power_couple":"soulmate";if(route.includes("×")&&portfolio.works>=12)return"multi_hyphenate";if((rep.業界評價||0)>=750&&snapshot.fans<120000)return"cult_artist";if(trigger==="retire"&&snapshot.money>=2000000)return"wealthy_exit";if(portfolio.works>=18)return"workhorse";if(score>=560)return"breakout";if(score>=220)return"steady";return"unfinished"}
const ENDING_COPY={
 death:["燃盡的星光","你追著每一盞燈跑，最後才發現身體不是可以無限續杯的資源。"],
 whole_life:["完整人生","你沒有把作品、關係與制度拆成互相犧牲的三道題。五年後，它們共同成為你願意繼續生活的答案。"],
 legacy_builder:["把門留在身後","你的名字不只留在作品上，也留在更透明的合約、被照顧的新人與不必再獨自摸索的路上。"],
 people_first:["散場後仍有人等你","最後一年，你沒有讓陪伴只剩成功故事的註腳。燈暗下來後，那些關係仍有自己的生活。"],
 masterpiece_vow:["五年只為這一幕","你拒絕用數量回答五年。最後留下的那部作品，讓所有繞路都突然有了方向。"],
 storm_icon:["風暴中心・誰都無法忽略你","愛你的人很愛，討厭你的人也天天替你貢獻流量。五年後，你仍站在所有鏡頭正中央。"],
 creative_auteur:["自己的名字就是片頭","你不再只等待別人遞來角色或歌曲。從某一年開始，市場開始等你的下一個作品。"],
 award_collector:["獎櫃真的放不下了","曾經每一次入圍都緊張得睡不著，後來工作人員已經知道頒獎夜要替你多準備一個位置。"],
 national_darling:["國民記憶","你不一定每週都在熱搜第一，但許多人看到你的臉，就會想起某段屬於自己的生活。"],
 commercial_king:["品牌爭奪戰","從第一次試鏡還要自己找棚，到後來品牌主動卡你的檔期。你的名字本身已經是一種商業保證。"],
 soulmate:["星光之外的重要的人","五年留下的不只履歷。在沒有鏡頭的地方，也有人知道你真正累的時候長什麼樣。"],
 power_couple:["並肩站上紅毯","外界喜歡替你們下標題，但真正重要的，是你們知道這段關係並不是為了任何版面。"],
 multi_hyphenate:["斜槓巨星","唱歌、演戲、主持、品牌——別人忙著替你分類，你忙著把分類表撕掉。"],
 cult_artist:["圈內人的圈內人","你未必是最吵的名字，卻成為創作者最想合作的人。每一份邀請都帶著一句：這個角色只有你可以。"],
 wealthy_exit:["漂亮轉身","你沒有把離開當失敗。存款、作品與自由都在手上，這次換你決定下一幕什麼時候開始。"],
 workhorse:["片尾名單裡總有你","不是每一部都是爆款，但一年又一年，片場、錄音室與棚內總有人說：找你最放心。"],
 breakout:["下一站，一線","五年不是句點。你已經從『那個新人』變成製作方會主動討論的名字。"],
 steady:["站穩腳步","沒有神話式爆紅，但你真的留了下來。這個圈子已經開始替你保留位置。"],
 unfinished:["未完待續","五年到了，你還沒有得到最想要的答案。但至少現在的你，已經知道下一步想往哪裡走。"]
};
export function evaluateEnding(trigger=state.endingType||"fiveyear"){const snapshot=state.endingSnapshot||endingSnapshot(trigger),originals=snapshot.completedWorks.filter(w=>w.original).length,portfolio={works:snapshot.completedWorks.length,originals,awards:snapshot.awards.length,bestWork:[...snapshot.completedWorks].sort((a,b)=>b.quality-a.quality)[0]||null},route=snapshot.route,bestRel=snapshot.bestRelationship,awardWins=snapshot.awards.filter(a=>a.result!=="入圍").length;const careerScore=Math.min(400,snapshot.fame*.12+(snapshot.rep.業界評價||0)*.25+portfolio.works*12+awardWins*35);const lifeScore=Math.min(250,Math.max(0,snapshot.money)/20000+(bestRel?bestRel.closeness+bestRel.trust:0));const publicScore=Math.min(250,snapshot.fans/5000+(snapshot.rep.路人緣||0)*.12+(snapshot.rep.可信度||0)*.12-(snapshot.rep.爭議度||0)*.1);const score=Math.round(careerScore+lifeScore+publicScore),rank=score>=750?"傳奇":score>=560?"巨星":score>=380?"一線":score>=220?"站穩腳步":"未完待續",endingId=endingArchetype({trigger,snapshot,portfolio,awardWins,score,route,bestRel}),[baseTitle,baseSummary]=ENDING_COPY[endingId],title=trigger==="retire"&&endingId==="steady"?`${route}・轉身之後`:baseTitle,legacy=snapshot.careerDoctrine?.year5,legacyText=legacy?` 最後一年，你選擇「${legacy.label}」；五年因此不只用成績結算，也用你刻意留下的東西作答。`:"",summary=baseSummary+legacyText;const badges=[];if(portfolio.works>=10)badges.push("作品豐收");if(originals>=3)badges.push("原創主義");if(awardWins)badges.push("獎項肯定");if(snapshot.money>=1000000)badges.push("財務自由");if(bestRel?.closeness>=80)badges.push("重要羈絆");if((snapshot.rep.爭議度||0)>=500)badges.push("風暴中心");if(legacy?.label)badges.push(legacy.label);return{trigger,endingId,title,rank,route,score,badges,portfolio,awardWins,relationship:bestRel||null,snapshot,summary}}
export function lockEnding(trigger){state.endingType=trigger;state.endingSnapshot=endingSnapshot(trigger);state.endingResult=evaluateEnding(trigger);return state.endingResult}
