import{state}from"../core/state.js";
import{portfolioSummary}from"./portfolio.js";

const ROUTES={歌曲:"唱作歌手",電影:"電影演員",電視劇:"國民演員",綜藝:"綜藝主持",廣告:"商業明星"};
export function careerRoute(){const entries=Object.entries(state.careerProgress||{}).sort((a,b)=>b[1]-a[1]);const[a,b]=entries;if(!a||a[1]<150)return"仍在尋找方向的新人";if(b&&b[1]>=a[1]*.82)return`${ROUTES[a[0]]} × ${ROUTES[b[0]]}`;return ROUTES[a[0]]}
export function recordCareerRoute(){const route=careerRoute(),last=state.careerRouteHistory.at(-1);if(!last||last.route!==route)state.careerRouteHistory.push({week:state.week,route});return route}
export function endingSnapshot(trigger=state.endingType||"fiveyear"){const relEntries=Object.entries(state.relationships||{}).sort(([,a],[,b])=>(b.closeness+b.trust)-(a.closeness+a.trust));return structuredClone({trigger,week:state.week,name:state.name,route:careerRoute(),money:state.money,fame:state.fame,fans:state.fans,rep:state.rep,completedWorks:state.completedWorks,awards:state.awards,careerProgress:state.careerProgress,careerRouteHistory:state.careerRouteHistory,bestRelationship:relEntries[0]?{npcId:relEntries[0][0],...relEntries[0][1]}:null,flags:state.flags,eventFlags:state.eventFlags})}
export function evaluateEnding(trigger=state.endingType||"fiveyear"){const snapshot=state.endingSnapshot||endingSnapshot(trigger),portfolio={works:snapshot.completedWorks.length,awards:snapshot.awards.length,bestWork:[...snapshot.completedWorks].sort((a,b)=>b.quality-a.quality)[0]||null},route=snapshot.route,bestRel=snapshot.bestRelationship,awardWins=snapshot.awards.filter(a=>a.result!=="入圍").length;const careerScore=Math.min(400,snapshot.fame*.12+(snapshot.rep.業界評價||0)*.25+portfolio.works*12+awardWins*35);const lifeScore=Math.min(250,Math.max(0,snapshot.money)/20000+(bestRel?bestRel.closeness+bestRel.trust:0));const publicScore=Math.min(250,snapshot.fans/5000+(snapshot.rep.路人緣||0)*.12+(snapshot.rep.可信度||0)*.12-(snapshot.rep.爭議度||0)*.1);const score=Math.round(careerScore+lifeScore+publicScore),rank=score>=750?"傳奇":score>=560?"巨星":score>=380?"一線":score>=220?"站穩腳步":"未完待續";const title=trigger==="death"?"燃盡的星光":trigger==="retire"?`${route}・轉身之後`:`${rank}之路・${route}`;const badges=[];if(portfolio.works>=10)badges.push("作品豐收");if(awardWins)badges.push("獎項肯定");if(snapshot.money>=1000000)badges.push("財務自由");if(bestRel?.closeness>=80)badges.push("重要羈絆");if((snapshot.rep.爭議度||0)>=500)badges.push("風暴中心");return{trigger,title,rank,route,score,badges,portfolio,awardWins,relationship:bestRel||null,snapshot,summary:trigger==="death"?"你用盡力氣追逐星光，卻忘了身體不是可以無限續杯的資源。":`五年的選擇讓你走到「${route}」。這一輪由作品、關係與聲望共同寫下結果。`}}
export function lockEnding(trigger){state.endingType=trigger;state.endingSnapshot=endingSnapshot(trigger);state.endingResult=evaluateEnding(trigger);return state.endingResult}
