import { titleTag } from "../core/utils.js";
import{state}from"../core/state.js";
import{NPCS}from"../data/npcs.js";
import{NPC_CAREER_PROFILES}from"../data/npc-network.js";
import{ensureNpcCareer,isNpcBusy,reserveNpcExternalSlot,completeNpcExternalSlot,releaseNpcExternalSlots}from"./npc-ecosystem.js";
export const CREATIVE_BUDGETS={lean:{label:"精簡製作",cost:0,multiplier:.88,note:"控制成本，靠創意與團隊硬實力撐成品。"},standard:{label:"標準製作",cost:3500,multiplier:1,note:"基本錄音、場地與後製資源完整。"},premium:{label:"高規製作",cost:9000,multiplier:1.18,note:"提高製作規格與宣傳素材品質。"}};
export const CREATIVE_ROLES={song:["製作人","主唱／演唱","編曲／樂手"],script:["導演／統籌","主演／演員","表演／劇本顧問"],show:["製作人","主持／演出","企劃／造型"]};
export function eligibleCreativeCollaborators(project){if(!project?.category)return[];return(state.knownPeople||[]).filter(id=>NPCS[id]&&NPC_CAREER_PROFILES[id]?.specialties?.includes(project.category)).map(id=>{const rel=state.relationships?.[id]||{},career=ensureNpcCareer(id);return{id,name:NPCS[id].name,field:NPC_CAREER_PROFILES[id].field,level:career.level,trust:rel.trust||0,closeness:rel.closeness||0,eligible:(rel.trust||0)>=12||(rel.closeness||0)>=20}}).filter(x=>x.eligible).sort((a,b)=>b.level-a.level||b.trust-a.trust)}
function defaultRole(project,npcId){const roles=CREATIVE_ROLES[project.type]||[],field=NPC_CAREER_PROFILES[npcId]?.field||"";if(field.includes("導演")||field.includes("製作"))return roles[0];if(field.includes("歌手")||field.includes("演員")||field.includes("主持"))return roles[1]||roles[0];return roles[2]||roles[0]}
export function toggleCreativeCollaborator(projectId,npcId){const p=state.creativeProjects?.find(x=>x.id===projectId);if(!p||!["contracted","production","ready_release"].includes(p.status))return{ok:false,message:"目前不能調整製作團隊。"};if(!eligibleCreativeCollaborators(p).some(x=>x.id===npcId))return{ok:false,message:"目前關係或專業領域還不足以邀請這位人物。"};p.team??=[];p.roleAssignments??={};const i=p.team.indexOf(npcId);if(i>=0){p.team.splice(i,1);delete p.roleAssignments[npcId];return{ok:true,message:`已將${NPCS[npcId].name}移出這份作品。`}}if(p.team.length>=3)return{ok:false,message:"同一份原創作品最多邀請三位主要合作夥伴。"};p.team.push(npcId);p.roleAssignments[npcId]=defaultRole(p,npcId);return{ok:true,message:`${NPCS[npcId].name}加入${titleTag(p.title)}製作團隊。`}}
export function cycleCreativeRole(projectId,npcId){const p=state.creativeProjects?.find(x=>x.id===projectId);if(!p||!p.team?.includes(npcId))return null;p.roleAssignments??={};const roles=CREATIVE_ROLES[p.type]||[];const current=p.roleAssignments[npcId],index=Math.max(-1,roles.indexOf(current));p.roleAssignments[npcId]=roles[(index+1)%roles.length];return p.roleAssignments[npcId]}
export function setCreativeBudget(projectId,tier){const p=state.creativeProjects?.find(x=>x.id===projectId),def=CREATIVE_BUDGETS[tier];if(!p||!def||p.productionSessions>0)return{ok:false,message:"製作開始後就不能再改預算規格。"};p.budgetTier=tier;return{ok:true,message:`${titleTag(p.title)}改為${def.label}。`}}
export function toggleSelfParticipation(projectId){const p=state.creativeProjects?.find(x=>x.id===projectId);if(!p)return false;p.selfParticipation=!p.selfParticipation;return p.selfParticipation}
function roleFit(project,id){const role=project.roleAssignments?.[id]||"",field=NPC_CAREER_PROFILES[id]?.field||"";if((role.includes("製作")&&field.includes("製作"))||(role.includes("導演")&&field.includes("導演"))||(role.includes("演唱")&&field.includes("歌手"))||(role.includes("演員")&&field.includes("演員"))||(role.includes("主持")&&field.includes("主持"))||(role.includes("造型")&&field.includes("時尚"))||(role.includes("企劃")&&field.includes("企劃")))return 18;return 4}
export function creativeTeamPower(project){const team=(project.team||[]).map(id=>ensureNpcCareer(id));const relation=(project.team||[]).reduce((sum,id)=>{const r=state.relationships?.[id]||{};return sum+(r.trust||0)+(r.closeness||0)*.5+roleFit(project,id)},0);const budget=CREATIVE_BUDGETS[project.budgetTier||"standard"]||CREATIVE_BUDGETS.standard;return(team.reduce((sum,c)=>sum+c.level*18+c.momentum*.35,0)+relation*.3)*budget.multiplier}
export function creativeBudgetCost(project){return(CREATIVE_BUDGETS[project.budgetTier||"standard"]||CREATIVE_BUDGETS.standard).cost}
export function reserveCreativeTeam(project,week,day){const key=`creative:${project.id}`;for(const id of project.team||[])if(isNpcBusy(id,week,day,key))return{ok:false,message:`${NPCS[id]?.name||"合作夥伴"}這天已有其他工作，請換一天。`};const reserved=[];for(const id of project.team||[]){if(reserveNpcExternalSlot(id,{key,week,day,label:`${titleTag(project.title)}製作`}))reserved.push(id);else{releaseNpcExternalSlots(key);return{ok:false,message:"合作團隊檔期無法成立。"}}}return{ok:true,key,reserved}}
export function completeCreativeTeamDay(project,week,day){const key=`creative:${project.id}`;for(const id of project.team||[])completeNpcExternalSlot(id,key,week,day)}
export function releaseCreativeTeam(projectId){releaseNpcExternalSlots(`creative:${projectId}`)}
