import { recordAgencyWorkDelivery } from "./agency-agreements.js";
import{state}from"../core/state.js";import{titleTag,effectiveStat}from"../core/utils.js";import{randomInt,chance}from"../core/rng.js";import{INDUSTRY_COMPANIES}from"../data/industry.js";import{registerAwardCandidate}from"./portfolio.js";import{creativeTeamPower,creativeBudgetCost}from"./creative-team.js";
export const CREATIVE_TYPES={song:{label:"歌曲 Demo",companyType:"唱片公司",stats:["創作","作詞","作曲"],productionStats:["歌藝","作曲","聲線"],baseSessions:2},script:{label:"影視劇本",companyType:"電影公司",stats:["編劇","創作","學識"],productionStats:["編劇","演技","鏡頭感"],baseSessions:3},show:{label:"節目企劃",companyType:"電視公司",stats:["創作","口才","學識"],productionStats:["主持","口才","社交"],baseSessions:2}};
export const CREATIVE_DIRECTIONS={
 song:{heart:{label:"真心敘事",note:"重視歌詞、情緒與作品粉",stat:"作詞",rep:"業界評價"},stage:{label:"舞台爆發",note:"重視副歌、表演與話題傳播",stat:"歌藝",rep:"話題度"},experimental:{label:"實驗聲響",note:"重視編曲、辨識度與創作自主",stat:"作曲",rep:"業界評價"}},
 script:{character:{label:"人物驅動",note:"讓角色選擇推動故事",stat:"編劇",rep:"業界評價"},commercial:{label:"商業類型",note:"節奏明確、容易接觸大眾",stat:"創作",rep:"商業價值"},arthouse:{label:"作者表達",note:"風格強烈、獎季潛力較高",stat:"學識",rep:"業界評價"}},
 show:{warm:{label:"溫暖陪伴",note:"強調真誠交流與路人緣",stat:"口才",rep:"路人緣"},viral:{label:"話題爆點",note:"設計易傳播的單元與挑戰",stat:"主持",rep:"話題度"},observational:{label:"生活觀察",note:"靠人物反應與洞察建立口碑",stat:"創作",rep:"可信度"}}
};
import { creativePhaseCopy } from "../data/creative-story-content.js";
export { CREATIVE_DIRECTION_STORIES } from "../data/creative-story-content.js";
const categoryFor=(p,company)=>p.type==="song"?"歌曲":p.type==="show"?"綜藝":company?.type==="電視公司"?"電視劇":"電影";
const creativeFreedomBonus=()=>Math.max(0,((state.agencyContractTerms?.creativeFreedom??50)-50)/5);
export function createCreativeProject(type,title){const def=CREATIVE_TYPES[type];if(!def||!title?.trim())return null;state.creativeProjects??=[];const direction=Object.keys(CREATIVE_DIRECTIONS[type])[0],p={id:`CP-${Date.now()}-${state.creativeProjects.length}`,type,title:title.trim(),direction,status:"draft",progress:0,quality:0,revisions:0,createdWeek:state.week,submissions:[],productionProgress:0,productionSessions:0,requiredProductionSessions:def.baseSessions,acceptedCompanyId:null,category:null,releaseWeek:null,marketScore:0,revenue:0,team:[],selfParticipation:true,budgetTier:"standard",budgetSpent:0,roleAssignments:{},distributionMode:null,storyHistory:[]};state.creativeProjects.push(p);return p}
export function setCreativeDirection(id,direction){const p=state.creativeProjects?.find(x=>x.id===id),def=p&&CREATIVE_DIRECTIONS[p.type]?.[direction];if(!p||!def||!["draft","rejected","ready"].includes(p.status))return{ok:false,message:"作品進入製作後就不能再改核心方向。"};p.direction=direction;return{ok:true,message:`${titleTag(p.title)}的創作方向改為「${def.label}」。`}}
export function creativeStory(project,phase){return creativePhaseCopy(project,phase)}
export function creativeGrade(value){const score=Math.max(0,Math.min(100,Number(value)||0));return score>=92?{grade:"S",stars:5,label:"年度代表作"}:score>=82?{grade:"A",stars:4,label:"強勢佳作"}:score>=70?{grade:"B",stars:3,label:"完成度良好"}:score>=55?{grade:"C",stars:2,label:"具潛力作品"}:{grade:"D",stars:1,label:"仍顯生澀"}}
export function chooseIndependentProduction(id){const p=state.creativeProjects?.find(x=>x.id===id);if(!p||p.status!=="ready")return{ok:false,message:"目前不能改為自主製作。"};const def=CREATIVE_TYPES[p.type];p.status="contracted";p.distributionMode="independent";p.acceptedCompanyId=null;p.category=p.type==="song"?"歌曲":p.type==="show"?"綜藝":"電影";p.requiredProductionSessions=def.baseSessions+1+(p.quality>=700?1:0);p.storyHistory.push({week:state.week,phase:"production-choice",text:"你保留完整權利，也必須自行承擔製作與發行風險。"});state.flags.push({week:state.week,label:`自主製作：${p.title}`,note:"保留完整權利，自行負擔製作成本與市場風險。"});return{ok:true,message:`${titleTag(p.title)}改為自主製作；你保留完整權利，也要自己負擔成本與發行。`}}
export function sellCreativeRights(id,companyId){const p=state.creativeProjects?.find(x=>x.id===id),company=INDUSTRY_COMPANIES[companyId];if(!p||!company||p.status!=="ready")return null;const def=CREATIVE_TYPES[p.type];if(company.type!==def.companyType&&!(p.type==="script"&&company.type==="電視公司"))return null;const direction=CREATIVE_DIRECTIONS[p.type][p.direction],value=Math.max(3000,Math.round(p.quality*(p.type==="script"?18:12)+(state.rep.業界評價||0)*6+state.knownPeople.length*500));p.status="sold";p.distributionMode="rights-sale";p.acceptedCompanyId=companyId;p.saleValue=value;p.saleWeek=state.week;p.finalGrade=creativeGrade(Math.min(100,p.quality/10));state.money+=value;state.rep.業界評價=Math.min(1000,(state.rep.業界評價||0)+8);p.storyHistory.push({week:state.week,phase:"rights-sale",text:`${company.name}買下企劃權利；你獲得一次性收入，但不再主導後續成品。`});state.flags.push({week:state.week,label:`售出企劃：${p.title}`,note:`以「${direction.label}」方向將企劃售予${company.name}，收入 ${value}。`});return{ok:true,project:p,company,value,grade:p.finalGrade}}
export function workOnCreativeProject(id){const p=state.creativeProjects?.find(x=>x.id===id);if(!p||!["draft","revising","rejected"].includes(p.status))return null;const def=CREATIVE_TYPES[p.type],direction=CREATIVE_DIRECTIONS[p.type]?.[p.direction],base=def.stats.reduce((s,n)=>s+effectiveStat(n),0)/def.stats.length,directionPower=direction?effectiveStat(direction.stat):base,power=base*.68+directionPower*.32,gain=randomInt(12,22)+Math.floor(power/150);p.progress=Math.min(100,p.progress+gain);p.quality=Math.min(1000,Math.max(p.quality,Math.round(power*.75+p.progress*2+randomInt(-20,30))));p.status=p.progress>=100?"ready":"draft";p.storyHistory??=[];p.storyHistory.push({week:state.week,phase:"development",text:creativeStory(p,"development")});p.storyHistory=p.storyHistory.slice(-12);return{project:p,gain,direction,story:creativeStory(p,"development")}}
export function reviseCreativeProject(id){const p=state.creativeProjects?.find(x=>x.id===id);if(!p||!["ready","rejected"].includes(p.status))return null;p.revisions+=1;p.quality=Math.min(1000,p.quality+randomInt(15,45));p.status="ready";return p}
export function submitCreativeProject(id,companyId){const p=state.creativeProjects?.find(x=>x.id===id),company=INDUSTRY_COMPANIES[companyId];if(!p||!company||p.status!=="ready")return null;const def=CREATIVE_TYPES[p.type];if(company.type!==def.companyType&&!(p.type==="script"&&company.type==="電視公司"))return null;const freedom=creativeFreedomBonus(),pct=Math.max(8,Math.min(92,20+p.quality/14+(state.rep.業界評價||0)/80+(state.knownPeople.length*1.5)+freedom)),accepted=chance(pct);p.submissions.push({companyId,week:state.week,result:accepted?"accepted":"rejected",chance:Math.round(pct),creativeFreedomBonus:freedom});p.status=accepted?"contracted":"rejected";if(accepted){p.acceptedCompanyId=companyId;p.category=categoryFor(p,company);p.requiredProductionSessions=def.baseSessions+(p.quality>=700?1:0);const advance=Math.round((p.type==="song"?2500:4000)*(1+freedom/100));state.money+=advance;p.advance=advance;state.rep.業界評價=Math.min(1000,(state.rep.業界評價||0)+5);state.flags.push({week:state.week,label:`創作簽約：${p.title}`,note:`${company.name}採用了你的${def.label}，作品進入正式製作。`})}return{accepted,pct:Math.round(pct),project:p,company}}
export function startCreativeProduction(id){const p=state.creativeProjects?.find(x=>x.id===id);if(!p||!["contracted","production"].includes(p.status))return null;const cost=creativeBudgetCost(p);if(p.productionSessions===0&&!p.budgetSpent&&cost){if(state.money<cost)return{project:p,error:"budget",cost};state.money-=cost;p.budgetSpent=cost}const def=CREATIVE_TYPES[p.type],own=def.productionStats.reduce((s,n)=>s+effectiveStat(n),0)/def.productionStats.length,team=creativeTeamPower(p),direction=CREATIVE_DIRECTIONS[p.type]?.[p.direction],directionPower=direction?effectiveStat(direction.stat):0,power=(p.selfParticipation?own:own*.35)+team+directionPower*.12;p.status="production";p.productionSessions+=1;const gain=Math.max(18,Math.min(55,Math.round(20+power/85+randomInt(-4,8))));p.productionProgress=Math.min(100,p.productionProgress+gain);p.quality=Math.min(1000,p.quality+Math.max(5,Math.round(power/55)+randomInt(0,12)));p.storyHistory??=[];p.storyHistory.push({week:state.week,phase:"production",text:creativeStory(p,"production")});if(p.productionSessions>=p.requiredProductionSessions||p.productionProgress>=100){p.productionProgress=100;p.status="ready_release"}return{project:p,gain,teamPower:team,costPaid:p.productionSessions===1?p.budgetSpent:0,story:creativeStory(p,"production")}}
export function releaseCreativeProject(id){const p=state.creativeProjects?.find(x=>x.id===id);if(!p||p.status!=="ready_release")return null;const company=INDUSTRY_COMPANIES[p.acceptedCompanyId],teamBoost=creativeTeamPower(p),direction=CREATIVE_DIRECTIONS[p.type]?.[p.direction],directionRep=direction?(state.rep[direction.rep]||0):0,buzz=(state.rep.話題度||0)+(state.rep.業界評價||0)*.5+state.fame*1.8+teamBoost*.6+directionRep*.12,modeBonus=p.distributionMode==="independent"?((state.rep.可信度||0)/100-2):4,score=Math.max(20,Math.min(100,Math.round(p.quality/12+buzz/40+modeBonus+randomInt(-10,14))));p.status="released";p.releaseWeek=state.week;p.marketScore=score;p.finalGrade=creativeGrade(score);const freedom=creativeFreedomBonus(),ownership=p.distributionMode==="independent"?1.45:1,revenue=Math.max(2500,Math.round((p.quality*8+score*180+teamBoost*30)*(p.type==="script"?1.5:1)*(1+freedom/200)*ownership));p.revenue=revenue;state.money+=revenue;const fameGain=Math.max(4,Math.round(score/8)),fanGain=Math.max(20,Math.round(score*6));state.fame+=fameGain;state.fans+=fanGain;state.rep.商業價值=Math.min(1000,(state.rep.商業價值||0)+Math.round(score/12));state.rep.業界評價=Math.min(1000,(state.rep.業界評價||0)+Math.round(p.quality/120));if(direction)state.rep[direction.rep]=Math.min(1000,(state.rep[direction.rep]||0)+Math.max(2,Math.round(score/18)));if(p.type==="show"&&p.direction==="viral")state.rep.爭議度=Math.min(1000,(state.rep.爭議度||0)+Math.max(0,Math.round((70-score)/8)));p.storyHistory??=[];p.storyHistory.push({week:state.week,phase:"release",text:creativeStory(p,"release")});const work={id:`creative-${p.id}`,jobId:null,creativeProjectId:p.id,title:p.title,category:p.category,tags:["原創",direction?.label||"自主創作",p.distributionMode==="independent"?"自主發行":"公司合作",p.type==="song"?"音樂":p.type==="show"?"綜藝":"戲劇"],stars:p.finalGrade.stars,grade:p.finalGrade.grade,role:p.selfParticipation?"原創／參與演出":"原創／幕後主創",client:company?.name||"自主發行",quality:Math.min(100,Math.round(p.quality/10)),completedWeek:state.week,completedYear:Math.ceil(state.week/52),fame:fameGain,fans:fanGain,npcCast:[...(p.team||[])],roleAssignments:{...(p.roleAssignments||{})},budgetTier:p.budgetTier,budgetSpent:p.budgetSpent||0,direction:p.direction,directionLabel:direction?.label||null,awards:[],original:true,marketScore:score,selfParticipation:p.selfParticipation,distributionMode:p.distributionMode||"company"};if(!state.completedWorks.some(w=>w.id===work.id)){state.completedWorks.push(work);state.careerProgress[p.category]=(state.careerProgress[p.category]||0)+work.stars*work.quality;registerAwardCandidate(work);recordAgencyWorkDelivery(work)}state.flags.push({week:state.week,label:`原創發行：${p.title}`,note:`以「${direction?.label||"自主創作"}」方向正式推出，成品 ${p.finalGrade.grade} 級／${p.finalGrade.stars} 星，市場評分 ${score}。`});return{project:p,work,score,revenue,fameGain,fanGain:fanGain+(work.agencyPromotion?.fansBonus||0),direction,grade:p.finalGrade,story:creativeStory(p,"release")}}
