import{state}from"../core/state.js";
import{NPCS}from"../data/npcs.js";
import{NPC_CAREER_PROFILES}from"../data/npc-network.js";
import{ensureNpcCareer,isNpcBusy,reserveNpcExternalSlot,completeNpcExternalSlot,releaseNpcExternalSlots}from"./npc-ecosystem.js";

export function eligibleCreativeCollaborators(project){if(!project?.category)return[];return(state.knownPeople||[]).filter(id=>NPCS[id]&&NPC_CAREER_PROFILES[id]?.specialties?.includes(project.category)).map(id=>{const rel=state.relationships?.[id]||{},career=ensureNpcCareer(id);return{id,name:NPCS[id].name,field:NPC_CAREER_PROFILES[id].field,level:career.level,trust:rel.trust||0,closeness:rel.closeness||0,eligible:(rel.trust||0)>=12||(rel.closeness||0)>=20}}).filter(x=>x.eligible).sort((a,b)=>b.level-a.level||b.trust-a.trust)}
export function toggleCreativeCollaborator(projectId,npcId){const p=state.creativeProjects?.find(x=>x.id===projectId);if(!p||!["contracted","production","ready_release"].includes(p.status))return{ok:false,message:"目前不能調整製作團隊。"};if(!eligibleCreativeCollaborators(p).some(x=>x.id===npcId))return{ok:false,message:"目前關係或專業領域還不足以邀請這位人物。"};p.team??=[];const i=p.team.indexOf(npcId);if(i>=0){p.team.splice(i,1);return{ok:true,message:`已將${NPCS[npcId].name}移出這份作品。`}}if(p.team.length>=3)return{ok:false,message:"同一份原創作品最多邀請三位主要合作夥伴。"};p.team.push(npcId);return{ok:true,message:`${NPCS[npcId].name}加入《${p.title}》製作團隊。`}}
export function toggleSelfParticipation(projectId){const p=state.creativeProjects?.find(x=>x.id===projectId);if(!p)return false;p.selfParticipation=!p.selfParticipation;return p.selfParticipation}
export function creativeTeamPower(project){const team=(project.team||[]).map(id=>ensureNpcCareer(id));const relation=(project.team||[]).reduce((sum,id)=>{const r=state.relationships?.[id]||{};return sum+(r.trust||0)+(r.closeness||0)*.5},0);return team.reduce((sum,c)=>sum+c.level*18+c.momentum*.35,0)+relation*.3}
export function reserveCreativeTeam(project,week,day){const key=`creative:${project.id}`;for(const id of project.team||[])if(isNpcBusy(id,week,day,key))return{ok:false,message:`${NPCS[id]?.name||"合作夥伴"}這天已有其他工作，請換一天。`};const reserved=[];for(const id of project.team||[]){if(reserveNpcExternalSlot(id,{key,week,day,label:`《${project.title}》製作`}))reserved.push(id);else{releaseNpcExternalSlots(key);return{ok:false,message:"合作團隊檔期無法成立。"}}}return{ok:true,key,reserved}}
export function completeCreativeTeamDay(project,week,day){const key=`creative:${project.id}`;for(const id of project.team||[])completeNpcExternalSlot(id,key,week,day)}
export function releaseCreativeTeam(projectId){releaseNpcExternalSlots(`creative:${projectId}`)}
