import { refreshMarriageInvitation } from "../core/romance-life-state.js";
import { chooseRomanceCeremony } from "./romance-life.js";
import { applyPersonalStoryChoice, isPersonalStoryEventCurrent, personalStoryEvent } from "./personal-stories.js";
import { recordCharacterMemory, memoryInvitationDeferral } from "./character-memory.js";
import { applyAgencyAgreementEffect } from "./agency-agreements.js";
import { applyWorkEchoEffect } from "./work-echoes.js";
import { eventContext } from "./event-context.js";
import{state}from"../core/state.js";
import{money,effectiveStat}from"../core/utils.js";
import{adjustRelationship,meetNpc}from"./npc-engine.js";
import{breakUp,setRomanceVisibility,romanceOpportunity}from"./romance-engine.js";
import{careerRoute}from"./career.js";
import{queueEvent,enqueueVisibleEvent,deferMemoryInvitations}from"./event-queue.js";
export{queueEvent,enqueueVisibleEvent,activateNextEvent,dismissActiveEvent}from"./event-queue.js";

export const EVENT_KINDS=Object.freeze({INSTANT:"即時事件",CHOICE:"選擇事件",DELAYED:"延遲事件",CHAIN:"連鎖事件",NPC:"人物事件",CAREER:"職涯事件",PUBLIC:"輿論事件"});
export function classifyEvent(event){if(event.kind)return event.kind;if(event.choices?.length)return EVENT_KINDS.CHOICE;if(event.effect?.npc||event.effects?.some(x=>x.npc))return EVENT_KINDS.NPC;if(event.effect?.delayWeeks||event.followUp)return EVENT_KINDS.DELAYED;if(event.effect?.flag||event.requires?.flags)return EVENT_KINDS.CHAIN;if(event.effect?.rep||event.effect?.fame||event.effect?.fans||event.effects?.some(x=>x.rep||x.fame||x.fans))return EVENT_KINDS.PUBLIC;if(event.effect?.work||event.effect?.award)return EVENT_KINDS.CAREER;return EVENT_KINDS.INSTANT}
export function matchesConditions(c={},game=state){if(c.weekMin&&game.week<c.weekMin)return false;if(c.weekMax&&game.week>c.weekMax)return false;if(c.moneyMin!=null&&game.money<c.moneyMin)return false;if(c.moneyMax!=null&&game.money>c.moneyMax)return false;if(c.fameMin!=null&&game.fame<c.fameMin)return false;if(c.fansMin!=null&&game.fans<c.fansMin)return false;if(c.fatigueMax!=null&&game.fatigue>c.fatigueMax)return false;if(c.fatigueMin!=null&&game.fatigue<c.fatigueMin)return false;if(c.moodMin!=null&&game.mood<c.moodMin)return false;if(c.healthMin!=null&&game.health<c.healthMin)return false;if(c.runMin!=null&&(game.runCount||1)<c.runMin)return false;if(c.knownNpc&&!game.knownPeople.includes(c.knownNpc))return false;if(c.unknownNpc&&game.knownPeople.includes(c.unknownNpc))return false;if(c.flags&&!c.flags.every(flag=>game.eventFlags.includes(flag)))return false;if(c.notFlags?.some(flag=>game.eventFlags.includes(flag)))return false;if(c.stats&&Object.entries(c.stats).some(([name,min])=>effectiveStat(name,game)<min))return false;if(c.hidden&&Object.entries(c.hidden).some(([name,min])=>(game.hidden?.[name]||0)<min))return false;if(c.rep&&Object.entries(c.rep).some(([name,min])=>(game.rep[name]||0)<min))return false;if(c.relationship&&Object.entries(c.relationship).some(([npc,need])=>{const rel=game.relationships[npc]||{};return(need.closeness!=null&&(rel.closeness||0)<need.closeness)||(need.trust!=null&&(rel.trust||0)<need.trust)||(need.affection!=null&&(rel.affection||0)<need.affection)||(need.hostilityMin!=null&&(rel.hostility||0)<need.hostilityMin)||(need.hostilityMax!=null&&(rel.hostility||0)>need.hostilityMax)||(need.romance&&rel.romance!==need.romance)}))return false;if(c.completedWorksMin!=null&&game.completedWorks.length<c.completedWorksMin)return false;if(c.awardsMin!=null&&game.awards.length<c.awardsMin)return false;if(c.completedCategory&&!game.completedWorks.some(w=>w.category===c.completedCategory))return false;if(c.awardResult&&!game.awards.some(a=>a.result===c.awardResult))return false;if(c.agencySigned!=null&&Boolean(game.currentAgencyId)!==Boolean(c.agencySigned))return false;if(c.agencyId&&game.currentAgencyId!==c.agencyId)return false;if(c.activeJob&&game.activeJobs?.[c.activeJob]?.stage!=="active")return false;if(c.jobStage&&Object.values(game.activeJobs||{}).every(j=>j.stage!==c.jobStage))return false;if(c.location&&!(game.freeLocations||[]).includes(c.location))return false;if(c.action&&!game.schedule?.includes(c.action))return false;if(c.careerRoute&&careerRoute(game)!==c.careerRoute)return false;return true}
export function eligibleEvents(pool,game=state){return(pool||[]).filter(event=>matchesConditions(event.requires||{},game))}
function romanceChoiceAvailable(choice,game){
 const effect=choice.effect||choice.effects||{};
 const effects=Array.isArray(effect)?effect:(effect.effects||[effect]);
 return effects.every(item=>!item.romance||["none","broken","rejected"].includes(item.romance)||romanceOpportunity(item.npc,game)?.next===item.romance);
}
export function availableChoices(event,game=state){return(event?.choices||[]).filter(choice=>matchesConditions(choice.requires||{},game)&&romanceChoiceAvailable(choice,game))}
function oneEffect(effect={},source="事件"){const out=[];
if(effect.personalStory){const result=applyPersonalStoryChoice(effect.personalStory);if(result.ok){out.push(...applyEffects(result.effects||[],source));for(const entry of result.memoryEntries||[]){const {npcId,...memory}=entry;recordCharacterMemory(npcId,memory)}if(result.text)out.push(result.text)}}
if(effect.characterMemory){const {npcId,...entry}=effect.characterMemory;if(recordCharacterMemory(npcId,{...entry,source:entry.source||source}))out.push(entry.text||entry.label||"對方記下了這次回應")}
if(effect.agencyAgreement){const result=applyAgencyAgreementEffect(effect.agencyAgreement);if(result.ok)out.push(result.message)}
if(effect.workEcho){const result=applyWorkEchoEffect(effect.workEcho);if(result.ok)out.push(result.message)}
const hiddenName=effect.hidden===true?effect.stat:(typeof effect.hidden==="string"?effect.hidden:null),repName=effect.rep===true?effect.stat:(typeof effect.rep==="string"?effect.rep:null);if(hiddenName){const value=effect.value??1;state.hidden[hiddenName]=Math.max(0,Math.min(1000,(state.hidden[hiddenName]??500)+value));out.push(`${hiddenName}獲得成長`)}if(typeof effect.hidden2==="string"){const value=effect.hiddenValue2??effect.value2??1;state.hidden[effect.hidden2]=Math.max(0,Math.min(1000,(state.hidden[effect.hidden2]??500)+value));out.push(`${effect.hidden2}獲得成長`)}if(repName){const value=effect.value??1;state.rep[repName]=Math.max(0,Math.min(1000,(state.rep[repName]||0)+value));out.push(`${repName}${value>=0?"＋":""}${value}`)}if(typeof effect.rep2==="string"){const value=effect.value2??effect.value??1;state.rep[effect.rep2]=Math.max(0,Math.min(1000,(state.rep[effect.rep2]||0)+value));out.push(`${effect.rep2}${value>=0?"＋":""}${value}`)}if(effect.stat&&!hiddenName&&!repName){const value=effect.value??1;state.stats[effect.stat]=Math.max(0,Math.min(1000,(state.stats[effect.stat]||0)+value));out.push(`${effect.stat}${value>=0?"＋":""}${value}`)}for(const key of["mood","fatigue","money","fame","fans","contract","health"]){if(effect[key]==null)continue;const value=effect[key];if(key==="mood"||key==="health")state[key]=Math.max(0,Math.min(100,state[key]+value));else if(key==="fatigue")state.fatigue=Math.max(0,state.fatigue+value);else if(key==="contract")state.contract=Math.max(0,Math.min(100,state.contract+value));else state[key]=Math.max(0,(state[key]||0)+value);const label={mood:"心情",fatigue:"疲勞",money:"金錢",fame:"知名度",fans:"粉絲",contract:"簽約準備度",health:"健康"}[key];out.push(`${label}${value>=0?"＋":""}${key==="money"?money(value):value}`)}if(effect.flag&&!state.eventFlags.includes(effect.flag)){state.eventFlags.push(effect.flag);out.push(`解鎖「${effect.flag}」`)}if(effect.removeFlag)state.eventFlags=state.eventFlags.filter(x=>x!==effect.removeFlag);if(effect.npc){const met=meetNpc(effect.npc,source);if(met.text)out.push(met.text);const rel=adjustRelationship(effect.npc,{closeness:effect.relation||0,trust:effect.trust||0,affection:effect.affection||0,hostility:effect.hostility||0,romance:effect.romance,source});if(effect.romanceCeremony&&rel.romanceResult?.ok)chooseRomanceCeremony(effect.npc,effect.romanceCeremony);if(effect.romanceVisibility)setRomanceVisibility(effect.npc,effect.romanceVisibility,source);if(effect.breakup)breakUp(effect.npc,source);if(rel.text&&!met.met)out.push(rel.text)}return out}
export function applyEffects(effect={},source="事件"){const list=Array.isArray(effect)?effect:(effect.effects||[effect]);return list.flatMap(item=>{const out=oneEffect(item,source);if(item.careerCommitment){state.careerCommitment={id:item.careerCommitment,label:item.commitmentLabel||item.careerCommitment,sinceWeek:state.week,lockedUntil:state.week+26};state.careerCommitmentHistory??=[];state.careerCommitmentHistory.push({...state.careerCommitment,source});out.push(`未來半年專注「${state.careerCommitment.label}」`)}if(item.doctrineKey){state.careerDoctrine??={};state.careerDoctrine[item.doctrineKey]={id:item.doctrineValue,label:item.doctrineLabel,sinceWeek:state.week};state.majorDecisionHistory??=[];state.majorDecisionHistory.push({week:state.week,year:Math.ceil(state.week/52),key:item.doctrineKey,id:item.doctrineValue,label:item.doctrineLabel,source});out.push(`永久方針：「${item.doctrineLabel}」`)}if(item.invitation){state.npcInvitationHistory??=[];const pending=[...state.npcInvitationHistory].reverse().find(x=>x.id===item.invitation.id);if(pending)Object.assign(pending,{response:item.invitation.response,label:item.invitation.label,resolvedWeek:state.week});out.push(`人物邀約：${item.invitation.label}`)}if(item.ensemble){state.ensembleEventHistory??=[];state.ensembleEventHistory.push({...item.ensemble,week:state.week,source});out.push(`人物關係網：${item.ensemble.label}`)}return out})}
const FLAGSHIP_EVENT_ID=/^flagship-choice:(J\d{3})$/;
const FLAGSHIP_CHOICES=["protect","breakthrough","signature"];
// Old saves can still contain the former weekly-queue snapshot. Never let it
// change an already finished work or grant a second choice's reputation.
export function clearJobProductionEvent(jobId){
 const id=`flagship-choice:${jobId}`;
 state.eventQueue=(state.eventQueue||[]).filter(item=>item.event?.id!==id);
 state.queuedEvents=(state.queuedEvents||[]).filter(item=>item.event?.id!==id);
 if(state.activeEvent?.event?.id===id)state.activeEvent=null;
}
function staleJobProductionEvent(event){
 const jobId=event?.id?.match(FLAGSHIP_EVENT_ID)?.[1];
 return jobId&&(state.activeJobs?.[jobId]?.stage!=="active"
  ||FLAGSHIP_CHOICES.some(choice=>state.eventFlags.includes(`flagship:${jobId}:${choice}`))
  ||state.eventHistory.some(item=>item.id===event.id));
}
export function pruneJobProductionEvents(){
 const snapshots=[state.activeEvent,...(state.eventQueue||[]),...(state.queuedEvents||[])];
 const stale=new Set(snapshots.filter(item=>staleJobProductionEvent(item?.event)).map(item=>item.event.id.match(FLAGSHIP_EVENT_ID)[1]));
 for(const jobId of stale)clearJobProductionEvent(jobId);
 return stale.size;
}
export function resolveEvent(event,choiceId=null){event=refreshMarriageInvitation(event);const deferredWeek=memoryInvitationDeferral(event);if(deferredWeek){deferMemoryInvitations();queueEvent(event,{source:"人物邀約",dueWeek:deferredWeek});return null}if(!isPersonalStoryEventCurrent(event)){prunePersonalStoryEvents();return null}if(staleJobProductionEvent(event)){clearJobProductionEvent(event.id.match(FLAGSHIP_EVENT_ID)[1]);return null}if(!event||(event.id&&state.eventHistory.some(record=>record.id===event.id))||!matchesConditions(event.requires||{}))return null;const choices=availableChoices(event),choice=choices.find(item=>item.id===choiceId);if(event.choices?.length&&!choice)return{pending:true,event};const effect=choice?.effect||choice?.effects||event.effects||event.effect||{};const effects=applyEffects(effect,event.title||"事件");const followUp=choice?.followUp||event.followUp;const record={storyContext:eventContext(event,{...state.activeEvent,week:state.week}),id:event.id||null,week:state.week,kind:classifyEvent(event),title:event.title,text:[...new Set([event.text,...(event.beats||[]).map(beat=>beat.text)].filter(Boolean))].join("\n\n"),choice:choiceId,choiceLabel:choice?.label||"確認這段經歷",outcome:choice?.outcome||event.outcome,effects,hasFollowUp:Boolean(followUp)};state.eventHistory.push(record);const jobId=event.id?.match(FLAGSHIP_EVENT_ID)?.[1];if(jobId)clearJobProductionEvent(jobId);if(followUp){const delay=followUp.delayWeeks||event.effect?.delayWeeks||1;queueEvent(followUp.event||followUp,{source:event.title,dueWeek:state.week+delay})}return{...record,text:event.text}}
export function processQueuedEvents(){deferMemoryInvitations();prunePersonalStoryEvents();pruneJobProductionEvents();const expired=state.queuedEvents.filter(item=>item.expiresWeek&&item.expiresWeek<state.week),due=state.queuedEvents.filter(item=>item.dueWeek<=state.week&&(!item.expiresWeek||item.expiresWeek>=state.week)).sort((a,b)=>(b.priority||0)-(a.priority||0)||(a.queuedWeek||0)-(b.queuedWeek||0)),future=state.queuedEvents.filter(item=>item.dueWeek>state.week&&(!item.expiresWeek||item.expiresWeek>=state.week));state.queuedEvents=future;if(expired.length)state.flags.push({week:state.week,label:"過期消息已整理",note:`${expired.length} 件已失去時效的事件不再打斷目前劇情。`});for(const item of due)if(matchesConditions(item.event.requires||{}))enqueueVisibleEvent(item.event,item.source,{queuedWeek:item.queuedWeek,expiresWeek:item.expiresWeek,priority:item.priority});return due.length}

// Pausing or changing a chapter invalidates its old queued snapshot before any rewards apply.
export function prunePersonalStoryEvents(game=state){
  const current=item=>!item?.event||isPersonalStoryEventCurrent(item.event,game);
  game.eventQueue=(game.eventQueue||[]).filter(current);
  game.queuedEvents=(game.queuedEvents||[]).filter(current);
  if(game.activeEvent&&!current(game.activeEvent))game.activeEvent=null;
}
export function requestPersonalStory(npcId){
  const event=personalStoryEvent(npcId);
  if(!event)return{ok:false,message:"這一章先保留，等合適的時候再接著聊。"};
  const queued=enqueueVisibleEvent(event,"人物連續故事");
  return{ok:!!queued&&queued!=="expired",message:queued?"這一章已排進後續故事，會在接下來的空檔接續。":"這一章已在等待的故事裡，不會重複安排。"};
}
