import { companyShifts, jobExperienceTier } from "./work-progression.js";
import{INDUSTRY_COMPANIES}from"../data/industry.js";
import{NPC_CAREER_PROFILES}from"../data/npc-network.js";
import{JOB_CATALOG}from"../data/jobs.js";
import{state,visitedLocationThisWeek}from"../core/state.js";
import{availableJobs}from"./job-engine.js";
import{activeAgencyOffer}from"./agency-offers.js";
export function companyForLocation(locationId){return Object.values(INDUSTRY_COMPANIES).find(c=>c.locationId===locationId)||null}
export function discoverCompany(locationId){const company=companyForLocation(locationId);if(!company)return null;state.discoveredCompanies??=[];if(!state.discoveredCompanies.includes(company.id))state.discoveredCompanies.push(company.id);return company}
function relevantContact(job){return Object.entries(state.relationships||{}).filter(([id,r])=>state.knownPeople.includes(id)&&NPC_CAREER_PROFILES[id]?.specialties.includes(job.category)&&(r.closeness||0)>=35&&(r.trust||0)>=20&&(r.hostility||0)<45).sort((a,b)=>(b[1].trust||0)-(a[1].trust||0))[0]?.[0]||null}
function hasRecentCastingIntel(locationId){if(!locationId)return false;if(visitedLocationThisWeek(locationId))return true;return(state.visitedLocationsByWeek?.[String(state.week-1)]||[]).includes(locationId)}
export function jobSource(job){const company=Object.values(INDUSTRY_COMPANIES).find(c=>c.categories.includes(job.category));if(!company)return{type:"public",company:null};const existing=state.activeJobs[job.id];if(existing && existing.stage!=="available")return{type:existing.sourceType||"public",company,referrerId:existing.referrerId||null,agencyId:existing.sourceAgencyId||null};if(state.fame>=220&&(state.completedWorks?.length||0)>=12&&job.stars<=Math.min(5,2+Math.floor(state.fame/180)))return{type:"direct",company};const offer=activeAgencyOffer(job.id);if(offer)return{type:"agency",company,agencyId:offer.agencyId};const referrerId=relevantContact(job);if(referrerId)return{type:"network",company,referrerId};if(companyShifts(state,company.id)>=3||(state.completedWorks||[]).filter(w=>company.categories.includes(w.category)).length>=2)return{type:"experience",company};return{type:"public",company}}
export function jobsVisibleAt(locationId){const company=companyForLocation(locationId);if(!company)return[];const unlocked=new Set(availableJobs().map(j=>j.id));return JOB_CATALOG.filter(job=>company.categories.includes(job.category)&&(unlocked.has(job.id)||(state.activeJobs[job.id]&&state.activeJobs[job.id].stage!=="available")))}
export function canAccessJob(job){const source=jobSource(job),record=state.activeJobs[job.id];if(record && record.stage!=="available")return{ok:true,source};if(job.stars>jobExperienceTier(state,job))return{ok:false,source,reason:"先累積正式作品，或完成同公司三次打工以接觸兩星機會。"};if(!availableJobs().some(j=>j.id===job.id))return{ok:false,source,reason:"目前的品牌合作條件尚未開放這份工作。"};if(["agency","network","direct","experience"].includes(source.type))return{ok:true,source};const ok=!!source.company&&hasRecentCastingIntel(source.company.locationId);return{ok,source,reason:ok?"":`先實際到訪${source.company?.name||"製作公司"}詢問近期徵選，或透過工作經驗、人脈與經紀人取得機會。`}}
export function markIndustryVisit(locationId){state.visitedIndustryLocations??=[];if(!state.visitedIndustryLocations.includes(locationId))state.visitedIndustryLocations.push(locationId);return discoverCompany(locationId)}
