import{JOB_BY_ID,JOB_CATALOG}from"../data/jobs-catalog.js";
import{DAYS}from"../data/calendar.js";
import{state}from"../core/state.js";
import{effectiveStat,successRateLabel}from"../core/utils.js";
import{calculateJobIncome}from"./agency.js";
import{addCompletedWork,workQuality}from"./portfolio.js";

export function ensureJobState(id){const job=JOB_BY_ID[id];if(!job)return null;return state.activeJobs[id]||(state.activeJobs[id]={jobId:id,stage:"available",appliedWeek:null,deadlineWeek:null,remainingSessions:job.sessions,completedSessions:0,notice:""})}
export function jobState(id){return state.activeJobs[id]||{jobId:id,stage:"available",remainingSessions:JOB_BY_ID[id]?.sessions||0,completedSessions:0,notice:""}}
export function availableJobs(){return JOB_CATALOG.filter(job=>job.stars<=Math.min(5,1+Math.floor((state.completedWorks?.length||0)/4))) }
export function qualification(job){const rows=job.requirements.map(([name,required])=>({name,required,current:effectiveStat(name),met:effectiveStat(name)>=required}));const training=state.trainingSessionsCompleted||0;return{rows,training,trainingRequired:job.minTrainingSessions,met:rows.every(r=>r.met)&&training>=job.minTrainingSessions}}
export function applyForJob(id){const job=JOB_BY_ID[id],record=ensureJobState(id);if(!job||record.stage!=="available")return false;if((state.trainingSessionsCompleted||0)<job.minTrainingSessions){record.notice=`至少需要 ${job.minTrainingSessions} 次訓練經驗。`;return false}record.stage="applied";record.appliedWeek=state.week;record.notice="試鏡邀請已確認。";state.selectedJobId=id;return true}
export function startJobAudition(id){const record=ensureJobState(id);if(record.stage!=="applied"&&record.stage!=="failed")return false;record.stage="audition";state.selectedJobId=id;return true}
export function auditionChance(job,choice="steady"){const gaps=job.requirements.map(([name,min])=>effectiveStat(name)-min),avg=gaps.reduce((s,n)=>s+n,0)/gaps.length;const hidden=job.softTraits.reduce((s,name)=>s+((state.hidden[name]||500)-500)/40,0);return Math.max(5,Math.min(95,Math.round(52+avg*.16+hidden+(choice==="steady"?8:-3))))}
export function resolveAudition(id,choice){const job=JOB_BY_ID[id],record=ensureJobState(id);if(!job||record.stage!=="audition")return null;const chance=auditionChance(job,choice),passed=Math.random()*100<chance;record.stage=passed?"passed":"failed";record.notice=passed?`試鏡通過・${successRateLabel(chance)}`:`未獲選・${successRateLabel(chance)}`;state.jobHistory.push({jobId:id,week:state.week,type:"audition",result:record.stage,choice});return{passed,chance,label:successRateLabel(chance)}}
export function signJob(id){const job=JOB_BY_ID[id],record=ensureJobState(id);if(!job||record.stage!=="passed")return false;record.stage="active";record.signedWeek=state.week;record.deadlineWeek=state.week+job.deadlineWeeks-1;record.remainingSessions=job.sessions;record.completedSessions=0;record.notice="合約已成立。";state.flags.push({week:state.week,label:`簽署通告：${job.title}`,note:`需於第 ${record.deadlineWeek} 週前完成 ${job.sessions} 次工作。`});return true}
export function scheduleJobSession(id){const job=JOB_BY_ID[id],record=ensureJobState(id);if(!job||record.stage!=="active")return{ok:false,message:"通告目前不在執行中。"};const day=state.schedule.findIndex((action,index)=>job.workDays.includes(index)&&(action==="rest"||action==="free"));if(day<0)return{ok:false,message:`本週指定工作日（${job.workDays.map(i=>DAYS[i]).join("、")}）沒有空檔。`};state.schedule[day]="job_session";state.freeLocations[day]=null;state.scheduledJobIds[day]=id;state.selectedDay=day;return{ok:true,day,message:`《${job.title}》已排入${DAYS[day]}。`}}
export function completeJobSession(id){const job=JOB_BY_ID[id],record=ensureJobState(id);if(!job||record.stage!=="active")return{ok:false,text:"這份通告已不在執行中。"};record.remainingSessions=Math.max(0,record.remainingSessions-1);record.completedSessions+=1;const perSession=Object.entries(job.rewards.growth||{}).map(([name,total])=>{const gain=Math.max(1,Math.round(total/job.sessions));state.stats[name]=Math.min(1000,(state.stats[name]||0)+gain);return`${name}＋${gain}`});if(record.remainingSessions>0)return{ok:true,completed:false,text:`完成本次工作，${perSession.join("、")}。合約剩餘 ${record.remainingSessions} 次。`};record.stage="completed";record.completedWeek=state.week;const income=calculateJobIncome(job.pay);state.money+=income.net;state.fame+=job.rewards.fame;state.fans+=job.rewards.fans;const quality=workQuality(job),work=addCompletedWork(job,{quality});state.jobHistory.push({jobId:id,week:state.week,type:"completed",quality,netIncome:income.net});state.flags.push({week:state.week,label:`完成作品：${job.title}`,note:`作品品質 ${quality}，正式收入 ${income.net}。`});return{ok:true,completed:true,work,income,text:`通告完成！${perSession.join("、")}。作品品質 ${quality}，實領 ${income.net}，知名度＋${job.rewards.fame}、粉絲＋${job.rewards.fans}。`}}
export function checkJobDeadlines(){const breached=[];for(const[id,record]of Object.entries(state.activeJobs)){if(record.stage==="active"&&state.week>record.deadlineWeek&&record.remainingSessions>0){record.stage="breached";record.notice=`逾期未完成 ${record.remainingSessions} 次工作。`;state.rep.業界評價=Math.max(0,(state.rep.業界評價||0)-Math.max(5,JOB_BY_ID[id].stars*5));state.jobHistory.push({jobId:id,week:state.week,type:"breached",remaining:record.remainingSessions});breached.push(id)}}return breached}
