import{JOB_BY_ID,JOB_CATALOG}from"../data/jobs.js";
import{DAYS}from"../data/calendar.js";
import{state}from"../core/state.js";
import{effectiveStat,successRateLabel}from"../core/utils.js";
import{chance}from"../core/rng.js";
import{calculateJobIncome}from"./agency.js";
import{addCompletedWork,workQuality}from"./portfolio.js";
import{assignJobCast,applyJobNpcRelations,confirmJobCastAndSchedule,refreshNpcJobSchedule,jobNpcSlotsForWeek,completeNpcJobSlot,releaseNpcJobSchedule}from"./npc-ecosystem.js";
import{brandEligible,jobMarketModifier}from"./reputation-engine.js";
import{brandAuditionModifier,brandCanWork,recordBrandOutcome}from"./brand-relations.js";
import{recordScandal,scandalMarketPenalty}from"./scandal-engine.js";
import{marketJobModifier}from"./world-market.js";
import{personaJobModifier}from"./persona-engine.js";
import{competitionPressure}from"./competitors.js";
import{roleOptions}from"./work-profile.js";
export function ensureJobState(id){const job=JOB_BY_ID[id];if(!job)return null;return state.activeJobs[id]||(state.activeJobs[id]={jobId:id,stage:"available",appliedWeek:null,deadlineWeek:null,remainingSessions:job.sessions,completedSessions:0,notice:"",lastAuditionWeek:null,npcCast:[],npcScheduleSlots:[],selectedRoleId:null})}
export function jobState(id){return state.activeJobs[id]||{jobId:id,stage:"available",remainingSessions:JOB_BY_ID[id]?.sessions||0,completedSessions:0,notice:"",npcCast:[],npcScheduleSlots:[],selectedRoleId:null}}
export function availableJobs(){return JOB_CATALOG.filter(job=>job.stars<=Math.min(5,1+Math.floor((state.completedWorks?.length||0)/4))&&(job.category!=="廣告"||brandEligible(job.stars))&&brandCanWork(job.client,job.stars))}
function reputationScore(job){if(!job.reputationSignals?.length)return 0;return job.reputationSignals.reduce((sum,name)=>sum+((state.rep[name]||0)-500)/45,0)}
export function qualification(job){const rows=job.requirements.map(([name,required])=>({name,required,current:effectiveStat(name),met:effectiveStat(name)>=required}));const training=state.trainingSessionsCompleted||0,brandOk=(job.category!=="廣告"||brandEligible(job.stars))&&brandCanWork(job.client,job.stars);return{rows,training,trainingRequired:job.minTrainingSessions,brandOk,met:rows.every(r=>r.met)&&training>=job.minTrainingSessions&&brandOk}}
function assertStage(id,allowed){const record=ensureJobState(id);return record&&allowed.includes(record.stage)?record:null}
export function setJobRole(id,roleId){const job=JOB_BY_ID[id],record=assertStage(id,["passed"]),role=roleOptions(job).find(r=>r.id===roleId);if(!job||!record||!role)return false;record.selectedRoleId=role.id;record.notice=`已選擇「${role.label}」版本。`;return true}
export function selectedJobRole(id){const job=JOB_BY_ID[id],record=jobState(id),roles=roleOptions(job);return roles.find(r=>r.id===record.selectedRoleId)||roles[0]||{id:"featured",label:job?.tagline||"主要參與",fame:1,award:1}}
export function applyForJob(id){const job=JOB_BY_ID[id],record=assertStage(id,["available"]);if(!job||!record)return false;const q=qualification(job);if(!q.met){record.notice=!q.brandOk?`${job.client}目前對你的合作評估偏保守，這份工作暫不開放。`:`資格尚未達標：${q.rows.filter(r=>!r.met).map(r=>r.name).join("、")||`至少 ${q.trainingRequired} 次訓練`}`;return false}record.stage="applied";record.appliedWeek=state.week;record.notice="試鏡邀請已確認。";state.selectedJobId=id;return true}
export function startJobAudition(id){const record=assertStage(id,["applied","failed"]);if(!record)return false;if(record.stage==="failed"&&record.lastAuditionWeek!=null&&state.week-record.lastAuditionWeek<2){record.notice="同一通告試鏡失敗後需等待兩週才能再次爭取。";return false}record.stage="audition";state.selectedJobId=id;return true}
export function auditionChance(job,choice="steady"){const gaps=job.requirements.map(([name,min])=>effectiveStat(name)-min),avg=gaps.reduce((s,n)=>s+n,0)/Math.max(1,gaps.length);const hidden=job.softTraits.reduce((s,name)=>s+((state.hidden[name]||500)-500)/40,0);return Math.max(5,Math.min(95,Math.round(50+avg*.16+hidden+reputationScore(job)+jobMarketModifier(job.category)+marketJobModifier(job.category)+personaJobModifier(job.category)-competitionPressure(job.category)+brandAuditionModifier(job.client)+scandalMarketPenalty()+(choice==="steady"?8:-3))))}
export function resolveAudition(id,choice){const job=JOB_BY_ID[id],record=assertStage(id,["audition"]);if(!job||!record)return null;const pct=auditionChance(job,choice),passed=chance(pct);record.stage=passed?"passed":"failed";record.lastAuditionWeek=state.week;record.notice=passed?`試鏡通過・${successRateLabel(pct)}`:`未獲選・${successRateLabel(pct)}`;if(passed){assignJobCast(job,record);record.selectedRoleId=roleOptions(job)[0]?.id||"featured"}else recordBrandOutcome(job.client,"audition_failed");state.jobHistory.push({jobId:id,week:state.week,type:"audition",result:record.stage,choice,chance:pct,npcCast:[...(record.npcCast||[])]});return{passed,chance:pct,label:successRateLabel(pct)}}
export function signJob(id){const job=JOB_BY_ID[id],record=assertStage(id,["passed"]);if(!job||!record)return false;assignJobCast(job,record);record.signedWeek=state.week;record.deadlineWeek=state.week+job.deadlineWeeks-1;record.remainingSessions=job.sessions;record.completedSessions=0;const booking=confirmJobCastAndSchedule(job,record);if(!booking.ok){record.notice=booking.message||"共演陣容檔期無法確認，暫時無法簽約。";record.signedWeek=null;record.deadlineWeek=null;return false}record.stage="active";record.notice=booking.recast?"合約已成立；原合作人選撞檔，製作方已調整陣容。":"合約已成立，合作陣容檔期已鎖定。";state.flags.push({week:state.week,label:`簽署通告：${job.title}`,note:`需於第 ${record.deadlineWeek} 週前完成 ${job.sessions} 次工作。`});return true}
export function jobScheduleOptions(id){const job=JOB_BY_ID[id],record=assertStage(id,["active"]);if(!job||!record)return[];refreshNpcJobSchedule(job,record);const npcDays=record.npcCast?.length?new Set(jobNpcSlotsForWeek(record,state.week).map(slot=>slot.day)):null;return job.workDays.filter(day=>(!npcDays||npcDays.has(day))&&["rest","free"].includes(state.schedule[day])&&!state.scheduledJobIds[day]).map(day=>({day,label:DAYS[day]}))}
export function scheduleJobSession(id,preferredDay=null){const job=JOB_BY_ID[id],record=assertStage(id,["active"]);if(!job||!record)return{ok:false,message:"通告目前不在執行中。"};const options=jobScheduleOptions(id);const selected=preferredDay==null?options[0]:options.find(x=>x.day===Number(preferredDay));if(!selected)return{ok:false,message:record.npcCast?.length?"本週玩家或合作藝人的共同檔期沒有可用空檔。":`本週指定工作日（${job.workDays.map(i=>DAYS[i]).join("、")}）沒有可用空檔。`};const day=selected.day;state.schedule[day]="job_session";state.freeLocations[day]=null;state.scheduledJobIds[day]=id;state.selectedDay=day;return{ok:true,day,options,message:`《${job.title}》已排入${DAYS[day]}。`}}
export function cancelScheduledJobSession(day){if(state.schedule[day]!=="job_session")return false;state.schedule[day]="rest";state.scheduledJobIds[day]=null;return true}
export function completeJobSession(id){const job=JOB_BY_ID[id],record=assertStage(id,["active"]);if(!job||!record)return{ok:false,text:"這份通告已不在執行中。"};record.remainingSessions=Math.max(0,record.remainingSessions-1);record.completedSessions+=1;completeNpcJobSlot(id,state.week,state.runnerDay);const perSession=Object.entries(job.rewards.growth||{}).map(([name,total])=>{const gain=Math.max(1,Math.round(total/job.sessions));state.stats[name]=Math.min(1000,(state.stats[name]||0)+gain);return`${name}＋${gain}`});applyJobNpcRelations(job,record,{completed:false});if(record.remainingSessions>0)return{ok:true,completed:false,text:`完成本次工作，${perSession.join("、")}。合約剩餘 ${record.remainingSessions} 次。`};record.stage="completed";record.completedWeek=state.week;releaseNpcJobSchedule(id);const income=calculateJobIncome(job.pay),role=selectedJobRole(id),fameGain=Math.max(1,Math.round(job.rewards.fame*role.fame)),fanGain=Math.max(0,Math.round(job.rewards.fans*role.fame));state.money+=income.net;state.fame+=fameGain;state.fans+=fanGain;applyJobNpcRelations(job,record,{completed:true});const quality=workQuality(job),work=addCompletedWork(job,{quality,npcCast:record.npcCast,role});recordBrandOutcome(job.client,"completed",{quality});state.jobHistory.push({jobId:id,week:state.week,type:"completed",quality,netIncome:income.net,roleId:role.id,npcCast:[...(record.npcCast||[])]});state.flags.push({week:state.week,label:`完成作品：${job.title}`,note:`以「${role.label}」完成作品，品質 ${quality}，正式收入 ${income.net}。`});return{ok:true,completed:true,work,income,text:`通告完成！${perSession.join("、")}。${role.label}・作品品質 ${quality}，實領 ${income.net}，知名度＋${fameGain}、粉絲＋${fanGain}。`}}
export function checkJobDeadlines(){const breached=[];for(const[id,record]of Object.entries(state.activeJobs)){if(record.stage==="active"&&state.week>record.deadlineWeek&&record.remainingSessions>0){const job=JOB_BY_ID[id];record.stage="breached";record.notice=`逾期未完成 ${record.remainingSessions} 次工作。`;releaseNpcJobSchedule(id);state.rep.業界評價=Math.max(0,(state.rep.業界評價||0)-Math.max(5,job.stars*5));recordBrandOutcome(job.client,"breached");recordScandal("breach",Math.min(3,Math.max(1,job.stars-1)),`《${job.title}》違約`);state.jobHistory.push({jobId:id,week:state.week,type:"breached",remaining:record.remainingSessions,npcCast:[...(record.npcCast||[])]});breached.push(id)}}return breached}
