import{state}from"../core/state.js";
import{managerForAgency}from"../data/managers.js";
import{enqueueVisibleEvent}from"./event-engine.js";
const clamp=n=>Math.max(0,Math.min(100,n));
export function ensureManager(){if(!state.currentAgencyId)return null;const def=managerForAgency(state.currentAgencyId);if(!def)return null;state.managerState??={};if(state.managerState.managerId!==def.id)state.managerState={managerId:def.id,agencyId:def.agencyId,trust:def.initialTrust,stress:def.initialStress,rapport:30,lastInteractionWeek:0,lastEventWeek:0,history:[]};return{def,state:state.managerState}}
export function adjustManager({trust=0,stress=0,rapport=0,source="事件"}={}){const m=ensureManager();if(!m)return null;const s=m.state;s.trust=clamp(s.trust+trust);s.stress=clamp(s.stress+stress);s.rapport=clamp(s.rapport+rapport);s.history.push({week:state.week,trust,stress,rapport,source});if(s.history.length>30)s.history=s.history.slice(-30);return s}
export function managerRelationshipLabel(){const m=ensureManager();if(!m)return"尚未有經紀人";const s=m.state;if(s.trust>=80&&s.rapport>=65)return"高度默契";if(s.trust>=65)return"信任穩定";if(s.trust>=45)return"磨合中";if(s.trust>=25)return"關係緊繃";return"信任危機"}
export function managerInteract(type){const m=ensureManager();if(!m)return{ok:false,message:"目前沒有固定經紀人。"};if(m.state.lastInteractionWeek===state.week)return{ok:false,message:"這週已經和經紀人談過一次了。"};m.state.lastInteractionWeek=state.week;if(type==="career")adjustManager({trust:3,rapport:4,stress:-3,source:"職涯會談"});else if(type==="apologize")adjustManager({trust:5,rapport:2,stress:-5,source:"危機後溝通"});else adjustManager({trust:2,rapport:3,stress:-2,source:"日常聯絡"});return{ok:true,message:`和${m.def.name}談過之後，你們對接下來的安排更有共識了。`}}
export function tickManager(){const m=ensureManager();if(!m)return null;const s=m.state,op=state.publicOpinion?.state||"neutral";let trust=0,stress=-1;if(op==="scandal"){trust-=2;stress+=10}else if(op==="controversial"){trust-=1;stress+=5}else if(op==="viral"){trust+=1;stress+=3}else if(op==="loved")trust+=1;const breaches=(state.jobHistory||[]).filter(x=>x.week===state.week&&x.type==="breached").length;if(breaches){trust-=breaches*4;stress+=breaches*8}const completed=(state.jobHistory||[]).filter(x=>x.week===state.week&&x.type==="completed").length;if(completed){trust+=Math.min(3,completed);stress-=Math.min(3,completed)}adjustManager({trust,stress,source:"每週工作狀態"});const key=`manager:${state.week}`;if(s.lastEventWeek!==state.week&&s.stress>=75&&!state.eventQueue.some(x=>x.event?.id===key)){enqueueVisibleEvent({id:key,kind:"人物事件",title:`${m.def.name}｜我們真的要談一下`,text:`${m.def.name}把行程表放到桌上。最近的工作與輿論讓她的壓力明顯升高，她想確認你到底打算怎麼走下去。`,choices:[{id:"listen",label:"先聽她把話說完",outcome:"你們重新對齊了工作節奏。",effects:[{rep:"可信度",value:6}],effect:{mood:2}},{id:"push",label:"我知道風險，但我想繼續衝",outcome:"她沒有阻止你，只提醒你要承擔後果。",effects:[{rep:"話題度",value:6},{rep:"爭議度",value:3}],effect:{fame:2}}]},"經紀人");s.lastEventWeek=state.week}return s}
