import{NPCS}from"../data/npcs.js";
import{firstMeetingFor,workFirstMeetingFor}from"../data/npc-first-meetings.js";
import{ROMANCE_STAGES}from"../data/romance.js";
import{state}from"../core/state.js";
import{adjustAffection,ensureRomanceFields,transitionRomance}from"./romance-engine.js";
import{enqueueVisibleEvent}from"./event-queue.js";

export const RELATIONSHIP_STAGES=Object.freeze([{id:"acquaintance",label:"初識",closeness:0,trust:0},{id:"familiar",label:"熟識",closeness:20,trust:15},{id:"friend",label:"朋友",closeness:40,trust:30},{id:"confidant",label:"知己",closeness:65,trust:55},{id:"bonded",label:"重要的人",closeness:85,trust:75}]);
export const CONFLICT_STAGES=Object.freeze([{id:"strained",label:"心有芥蒂",hostility:20},{id:"hostile",label:"關係不合",hostility:45},{id:"enemy",label:"已經交惡",hostility:70},{id:"nemesis",label:"宿敵",hostility:90}]);
export{ROMANCE_STAGES};
export function ensureRelationship(id){const rel=state.relationships[id]||(state.relationships[id]={closeness:0,trust:0,romance:"none",affection:0,hostility:0,stage:"acquaintance",lastInteractionWeek:0,lastMilestoneWeek:0,events:[]});ensureRomanceFields(id);rel.hostility=Math.max(0,Math.min(100,Number(rel.hostility)||0));rel.hostilityHistory=Array.isArray(rel.hostilityHistory)?rel.hostilityHistory:[];return rel}
export function relationshipStage(rel){return[...RELATIONSHIP_STAGES].reverse().find(stage=>rel.closeness>=stage.closeness&&rel.trust>=stage.trust)||RELATIONSHIP_STAGES[0]}
export function conflictStage(rel){return[...CONFLICT_STAGES].reverse().find(stage=>(rel.hostility||0)>=stage.hostility)||null}
export function relationshipStance(rel){return conflictStage(rel)||relationshipStage(rel)}
export function hostilitySignal(id){const value=ensureRelationship(id).hostility;if(value>=90)return"對方已將你視為必須正面擊敗的宿敵";if(value>=70)return"敵意非常明確，連公開場合都不願替你留情面";if(value>=45)return"對方明顯避開私下往來，也不願輕易合作";if(value>=20)return"言談之間多了防備，有些事仍沒有真正翻篇";return"目前沒有明顯的敵意或未解衝突"}
export function meetNpc(id,source="偶然相遇",details={}){if(!NPCS[id])return{met:false,text:""};const already=state.knownPeople.includes(id),rel=ensureRelationship(id);if(already)return{met:false,text:""};const familiar=state.familiarNpcs.includes(id),meeting=details.context==="work"?workFirstMeetingFor(id,details.workTitle):firstMeetingFor(id);rel.closeness=(familiar?18:8)+(state.focus==="people"?2:0);rel.trust=(familiar?20:10)+(state.focus==="people"?1:0);rel.stage=relationshipStage(rel).id;rel.lastInteractionWeek=state.week;rel.metWeek=state.week;rel.metSource=source;rel.firstMeetingTitle=meeting.title;rel.firstMeetingText=familiar?`你明明是第一次正式與${NPCS[id].name}說話，彼此卻都有種早已認識的錯覺。${meeting.scene}`:meeting.scene;state.knownPeople.push(id);state.selectedNpc=id;state.flags.push({week:state.week,label:`第一次認識${NPCS[id].name}`,note:rel.metSource});return{met:true,title:`${NPCS[id].name}｜${meeting.title}`,text:`<p class="first-meeting-scene">${rel.firstMeetingText}</p><p class="first-meeting-unlock">交換聯絡方式後，人物檔案已解鎖：<b>${NPCS[id].name}</b></p>${state.focus==="people"?`<em class="focus-result">♡ 策略「拓展人脈」：初次印象親近額外＋2、信任額外＋1</em>`:""}`,npcId:id,npcName:NPCS[id].name,portrait:NPCS[id].bust,accent:NPCS[id].accent,meeting:{week:rel.metWeek,source:rel.metSource,title:rel.firstMeetingTitle,text:rel.firstMeetingText}}}
export function npcFirstMeeting(id){const npc=NPCS[id],rel=state.relationships[id]||{},fallback=firstMeetingFor(id),flag=state.flags?.find(x=>x.label===`第一次認識${npc?.name}`);return{week:rel.metWeek||flag?.week||1,source:rel.metSource||flag?.note||"在星望市偶然相遇。",title:rel.firstMeetingTitle||fallback.title,text:rel.firstMeetingText||fallback.scene}}
function milestoneEvent(id,stage){const npc=NPCS[id],conflict=CONFLICT_STAGES.some(x=>x.id===stage);return{id:`npc-${id}-${stage}`,kind:"人物事件",title:`${npc.name}・${[...RELATIONSHIP_STAGES,...CONFLICT_STAGES].find(x=>x.id===stage)?.label||"關係變化"}`,text:milestoneText(id,stage),outcome:conflict?"這次裂痕將影響往後的相處與合作。":"你們的關係往前走了一步。",effect:{flag:`npc:${id}:${stage}`}}}
function enqueueNpcEvent(event,source){enqueueVisibleEvent(event,source)}
export function adjustRelationship(id,{closeness=0,trust=0,affection=0,hostility=0,romance=null,source="互動"}={}){if(!NPCS[id])return{changed:false,text:""};if(!state.knownPeople.includes(id))meetNpc(id,source);if(state.focus==="people"){if(closeness>0)closeness+=2;if(trust>0)trust+=1}const rel=ensureRelationship(id),before=relationshipStance(rel),oldHostility=rel.hostility;rel.closeness=Math.max(0,Math.min(100,rel.closeness+closeness));rel.trust=Math.max(0,Math.min(100,rel.trust+trust));rel.hostility=Math.max(0,Math.min(100,rel.hostility+hostility));if(rel.hostility!==oldHostility){rel.hostilityHistory.push({week:state.week,delta:rel.hostility-oldHostility,source});rel.hostilityHistory=rel.hostilityHistory.slice(-40)}const affectionResult=adjustAffection(id,affection,source);let romanceResult=romance&&ROMANCE_STAGES.includes(romance)?transitionRomance(id,romance,source):null;if(rel.hostility>=45&&["dating","committed","engaged","married"].includes(rel.romance))romanceResult=transitionRomance(id,"broken",`${source}造成無法忽視的裂痕`);rel.lastInteractionWeek=state.week;const after=relationshipStance(rel);rel.stage=after.id;if(before.id!==after.id){const key=`${id}:${after.id}`;if(!state.npcEventProgress[key]){state.npcEventProgress[key]=true;rel.events=[...(rel.events||[]),{week:state.week,stage:after.id,source}];rel.lastMilestoneWeek=state.week;enqueueNpcEvent(milestoneEvent(id,after.id),source);state.npcMessages.push({week:state.week,npcId:id,title:`與${NPCS[id].name}的關係進入「${after.label}」`,text:milestoneText(id,after.id)});state.flags.push({week:state.week,label:`人物關係：${NPCS[id].name}・${after.label}`,note:source})}}const warmer=closeness>0||trust>0||hostility<0||affectionResult.direction==="up",colder=closeness<0||trust<0||hostility>0||affectionResult.direction==="down",text=romanceResult?.ok?`你和<b>${NPCS[id].name}</b>的關係有了新的定義`:after.id==="nemesis"?`<b>${NPCS[id].name}</b>已經把你視為必須正面擊敗的宿敵`:after.id==="enemy"?`你和<b>${NPCS[id].name}</b>正式交惡`:warmer?`你和<b>${NPCS[id].name}</b>的距離似乎更近了`:colder?`你和<b>${NPCS[id].name}</b>之間留下了沒有解開的裂痕`:`你和<b>${NPCS[id].name}</b>相處了一段時間`;return{changed:true,stageChanged:before.id!==after.id,stage:after,romanceResult,text}}
export function advanceRomance(id,next,source="關係事件"){ensureRelationship(id);return transitionRomance(id,next,source).ok}
function milestoneText(id,stage){const npc=NPCS[id];const text={familiar:`${npc.name}開始記得你的習慣，也願意在工作以外多聊幾句。`,friend:`你們不再只是業界點頭之交，彼此會主動分享近況。`,confidant:`${npc.name}願意讓你看見公眾形象之外的壓力與選擇。`,bonded:`你已成為${npc.name}人生中無法輕易取代的重要存在。`,strained:`${npc.name}對你的態度多了一層防備，某些話題開始刻意避開。`,hostile:`${npc.name}不再願意進行深入往來，合作與推薦也會受到影響。`,enemy:`你們之間的衝突已經不是誤會，${npc.name}明確把你排除在信任圈外。`,nemesis:`${npc.name}將你視為必須正面擊敗的對手，這段宿敵關係會持續影響職涯。`};return text[stage]||`你和${npc.name}的關係有了新的變化。`}
export function npcStoryStatus(id){const rel=state.relationships[id]||{closeness:0,trust:0,hostility:0,events:[]},stage=relationshipStance(rel);return{stage,romance:rel.romance||"none",events:rel.events||[],unread:state.npcMessages.filter(m=>m.npcId===id&&!m.read)}}
