import{state}from"../core/state.js";
import{effectiveStat}from"../core/utils.js";
import{chance}from"../core/rng.js";
import{workTags}from"./work-profile.js";
const AWARD_NAMES={歌曲:"星音年度音樂獎",電影:"金幕電影獎",電視劇:"星河電視獎",綜藝:"金笑綜藝獎",廣告:"年度品牌影響力獎"};
export const AWARD_WEEK_IN_YEAR={歌曲:20,電影:42,電視劇:42,綜藝:46,廣告:48};
export function workQuality(job){const values=job.requirements.map(([name,min])=>Math.min(125,(effectiveStat(name)/Math.max(1,min))*100));const ability=values.reduce((sum,n)=>sum+n,0)/Math.max(1,values.length);const condition=Math.max(35,100-state.fatigue*.45)+(state.mood-50)*.18+(state.health-50)*.12;const hidden=(job.softTraits||[]).reduce((sum,name)=>sum+((state.hidden[name]||500)-500)/80,0);return Math.max(1,Math.min(100,Math.round(ability*.66+condition*.26+hidden*.08)))}
export function addCompletedWork(job,{quality=workQuality(job),completedWeek=state.week,npcCast=[]}={}){if(state.completedWorks.some(work=>work.jobId===job.id))return state.completedWorks.find(work=>work.jobId===job.id);const work={id:`work-${job.id}-${completedWeek}`,jobId:job.id,title:job.title,category:job.category,tags:workTags(job),stars:job.stars,role:job.tagline,client:job.client,quality,completedWeek,completedYear:Math.ceil(completedWeek/52),fame:job.rewards.fame,fans:job.rewards.fans,npcCast:[...npcCast],awards:[]};state.completedWorks.push(work);state.careerProgress[job.category]=(state.careerProgress[job.category]||0)+job.stars*quality;registerAwardCandidate(work);return work}
export function registerAwardCandidate(work){if(work.stars<3||work.quality<72)return false;const offset=AWARD_WEEK_IN_YEAR[work.category]||52,currentYear=Math.max(1,Math.ceil(work.completedWeek/52)),currentCeremony=(currentYear-1)*52+offset,awardYear=work.completedWeek<=currentCeremony?currentYear:currentYear+1,ceremonyWeek=(awardYear-1)*52+offset,key=`${awardYear}:${work.category}`;state.awardSeasons[key]||={key,year:awardYear,category:work.category,name:AWARD_NAMES[work.category],candidates:[],resolved:false,ceremonyWeek};if(!state.awardSeasons[key].candidates.includes(work.id))state.awardSeasons[key].candidates.push(work.id);return true}
function resolveSeason(season){if(!season||season.resolved)return[];const results=[];for(const workId of season.candidates){const work=state.completedWorks.find(w=>w.id===workId);if(!work)continue;const nominationChance=Math.min(95,30+work.quality*.55+work.stars*4);if(!chance(nominationChance))continue;let result="入圍";const winChance=Math.max(8,work.quality-65+work.stars*4);if(chance(winChance))result=work.stars===5&&work.quality>=92&&chance(35)?"年度大獎":"得獎";const identity=work.jobId||work.creativeProjectId||work.id,award={id:`award-${season.year}-${identity}-${work.category}`,week:state.week,year:season.year,workId:work.id,name:AWARD_NAMES[work.category],category:work.category,result};if(!state.awards.some(item=>item.id===award.id)){state.awards.push(award);work.awards.push(award.id);state.flags.push({week:state.week,label:`${award.name}・${result}`,note:`作品《${work.title}》獲得肯定。`});results.push(award)}}season.resolved=true;season.resolvedWeek=state.week;season.results=results.map(r=>r.id);return results}
export function resolveAwardSeason(year,category=null){const seasons=Object.values(state.awardSeasons||{}).filter(s=>s.year===year&&(!category||s.category===category));return seasons.flatMap(resolveSeason)}
export function resolveDueAwardSeasons(){const due=[];for(const season of Object.values(state.awardSeasons||{}))if(!season.resolved&&state.week>=season.ceremonyWeek)due.push(...resolveSeason(season));return due}
export function portfolioSummary(){return{works:state.completedWorks.length,awards:state.awards.length,bestWork:[...state.completedWorks].sort((a,b)=>b.quality-a.quality)[0]||null}}
