import{state}from"../core/state.js";
import{adjustRelationship}from"./npc-engine.js";
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
export function publicOpinionSnapshot(){state.publicOpinion??={state:"neutral",score:0,brandTrust:50,heat:0,scandalLevel:0,lastChangedWeek:0};return state.publicOpinion}
export function jobMarketModifier(category){const p=publicOpinionSnapshot();let mod=0;if(p.state==="viral")mod+=category==="廣告"?12:7;if(p.state==="loved")mod+=6;if(p.state==="controversial")mod-=category==="廣告"?18:8;if(p.state==="scandal")mod-=category==="廣告"?40:18;return mod}
export function brandEligible(stars=1){const p=publicOpinionSnapshot();if(stars<=2)return true;if(p.scandalLevel>=3)return false;if(stars>=4&&p.brandTrust<35)return false;return true}
function pushOpinionNews(from,to){state.industryNews??=[];const labels={neutral:"風向恢復平穩",loved:"路人好感明顯上升",viral:"討論度突然爆發",controversial:"爭議話題持續升溫",scandal:"陷入高強度炎上"},key=`opinion:${state.week}:${to}`;if(state.industryNews.some(n=>n.key===key))return;state.industryNews.unshift({id:`NEWS-OP-${state.week}`,key,week:state.week,category:"輿論",subject:"player",title:`${state.name}${labels[to]}`,body:to==="scandal"?"品牌與製作方開始重新評估合作風險，圈內熟人的態度也受到外界壓力影響。":to==="viral"?"大量討論正在轉化成新的曝光與商業詢問。":to==="neutral"&&from!=="neutral"?"話題逐漸退燒，合作市場開始恢復正常。":"近期公眾風向出現明顯變化。",heat:to==="scandal"?420:to==="viral"?360:180})}
function queueResponseEvent(to){state.eventQueue??=[];if(to==="scandal")state.eventQueue.push({source:"公關危機",event:{id:`scandal-response-${state.week}`,kind:"輿論事件",title:"輿論全面失控",text:"熱搜與論壇討論一路往上燒，品牌窗口開始詢問經紀方的處理方式。現在的回應會影響後續合作。",choices:[{id:"apology",label:"公開說明並道歉",outcome:"你選擇正面回應。風向沒有立刻消失，但可信度開始止跌。",effects:[{rep:"可信度",value:35},{rep:"爭議度",value:-70},{rep:"路人緣",value:15}]},{id:"silent",label:"暫停公開活動，等待退燒",outcome:"你停止回應，把注意力留給時間處理。",effects:[{rep:"爭議度",value:-35},{mood:-3}]},{id:"fight",label:"強硬反擊所有質疑",outcome:"支持者更死忠，但爭議也被推到更高。",effects:[{fans:25},{rep:"爭議度",value:45},{rep:"可信度",value:-15}] }]}});else if(to==="viral")state.eventQueue.push({source:"爆紅話題",event:{id:`viral-response-${state.week}`,kind:"輿論事件",title:"突然所有人都在談你",text:"作品片段、訪談截圖和舊貼文一起被翻出來。經紀窗口問你，要不要趁這波把曝光拉滿。",choices:[{id:"ride",label:"趁熱接曝光",outcome:"你選擇把流量轉成工作與商業價值。",effects:[{fame:8},{fans:35},{rep:"商業價值",value:20},{rep:"話題度",value:18}]},{id:"steady",label:"維持原本節奏",outcome:"你沒有讓行程被流量完全帶著走。",effects:[{rep:"可信度",value:12},{rep:"路人緣",value:10}]}]}})}
export function tickPublicOpinion(news=[]){const p=publicOpinionSnapshot(),before=p.state,rep=state.rep||{};const heatFromNews=news.reduce((s,n)=>s+Math.min(30,Math.round((n.heat||0)/40)),0),controversy=(rep.爭議度||0),trust=(rep.可信度??500),good=(rep.路人緣??500)+(rep.國民度||0)*.6+(rep.業界評價||0)*.35;const score=Math.round((good-trust*.1)/18-(controversy/12)+state.fame/8);p.score=score;p.heat=clamp(Math.round((p.heat||0)*.65+heatFromNews+(rep.話題度||0)/25),0,100);p.brandTrust=clamp(Math.round(50+(trust-500)/18+((rep.路人緣??500)-500)/22-(controversy/16)),0,100);if(controversy>=650&&trust<380)p.state="scandal";else if(controversy>=380)p.state="controversial";else if(p.heat>=70&&score>=15)p.state="viral";else if(score>=35)p.state="loved";else p.state="neutral";p.scandalLevel=p.state==="scandal"?clamp(2+Math.floor((controversy-600)/120),2,5):p.state==="controversial"?1:0;if(before!==p.state){p.lastChangedWeek=state.week;state.publicOpinionHistory??=[];state.publicOpinionHistory.push({week:state.week,from:before,to:p.state,score:p.score,brandTrust:p.brandTrust});pushOpinionNews(before,p.state);queueResponseEvent(p.state);const delta=p.state==="scandal"?-4:p.state==="controversial"?-2:p.state==="viral"?2:p.state==="loved"?3:p.state==="neutral"&&["scandal","controversial"].includes(before)?1:0;for(const id of state.knownPeople||[])if(state.relationships?.[id])adjustRelationship(id,{trust:delta,closeness:delta>0?1:0,source:"外界輿論變化"})}if(p.state==="scandal"){state.rep.商業價值=Math.max(0,(state.rep.商業價值||0)-8);state.mood=Math.max(0,state.mood-5)}else if(p.state==="viral"){state.fans+=Math.max(5,Math.round(state.fame/5));state.rep.商業價值=Math.min(1000,(state.rep.商業價值||0)+5)}else if(p.state==="neutral"&&p.scandalLevel===0)state.rep.爭議度=Math.max(0,(state.rep.爭議度||0)-2);return p}
export function publicOpinionLabel(){return{neutral:"風向平穩",loved:"好感上升",viral:"爆紅熱議",controversial:"爭議升溫",scandal:"炎上危機"}[publicOpinionSnapshot().state]}
