import{state}from"../core/state.js";
import{adjustRelationship}from"./npc-engine.js";

const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
export function publicOpinionSnapshot(){state.publicOpinion??={state:"neutral",score:0,brandTrust:50,heat:0,scandalLevel:0,lastChangedWeek:0};return state.publicOpinion}
export function jobMarketModifier(category){const p=publicOpinionSnapshot();let mod=0;if(p.state==="viral")mod+=category==="廣告"?12:7;if(p.state==="loved")mod+=6;if(p.state==="controversial")mod-=category==="廣告"?18:8;if(p.state==="scandal")mod-=category==="廣告"?40:18;return mod}
export function brandEligible(stars=1){const p=publicOpinionSnapshot();if(stars<=2)return true;if(p.scandalLevel>=3)return false;if(stars>=4&&p.brandTrust<35)return false;return true}
export function tickPublicOpinion(news=[]){const p=publicOpinionSnapshot(),before=p.state,rep=state.rep||{};const heatFromNews=news.reduce((s,n)=>s+Math.min(30,Math.round((n.heat||0)/40)),0),controversy=(rep.爭議度||0),trust=(rep.可信度??500),good=(rep.路人緣??500)+(rep.國民度||0)*.6+(rep.業界評價||0)*.35;const score=Math.round((good-trust*.1)/18-(controversy/12)+state.fame/8);p.score=score;p.heat=clamp(Math.round((p.heat||0)*.65+heatFromNews+(rep.話題度||0)/25),0,100);p.brandTrust=clamp(Math.round(50+(trust-500)/18+(rep.路人緣-500)/22-(controversy/16)),0,100);if(controversy>=650&&trust<380)p.state="scandal";else if(controversy>=380)p.state="controversial";else if(p.heat>=70&&score>=15)p.state="viral";else if(score>=35)p.state="loved";else p.state="neutral";p.scandalLevel=p.state==="scandal"?clamp(2+Math.floor((controversy-600)/120),2,5):p.state==="controversial"?1:0;if(before!==p.state){p.lastChangedWeek=state.week;state.publicOpinionHistory??=[];state.publicOpinionHistory.push({week:state.week,from:before,to:p.state,score:p.score,brandTrust:p.brandTrust});const delta=p.state==="scandal"?-4:p.state==="controversial"?-2:p.state==="viral"?2:p.state==="loved"?3:0;for(const id of state.knownPeople||[])if(state.relationships?.[id])adjustRelationship(id,{trust:delta,closeness:delta>0?1:0,source:"外界輿論變化"})}if(p.state==="scandal"){state.rep.商業價值=Math.max(0,(state.rep.商業價值||0)-8);state.mood=Math.max(0,state.mood-5)}else if(p.state==="viral"){state.fans+=Math.max(5,Math.round(state.fame/5));state.rep.商業價值=Math.min(1000,(state.rep.商業價值||0)+5)}return p}
export function publicOpinionLabel(){return{neutral:"風向平穩",loved:"好感上升",viral:"爆紅熱議",controversial:"爭議升溫",scandal:"炎上危機"}[publicOpinionSnapshot().state]}
