// 邏輯層：「逐日事件」引擎——決定某天有沒有現場選擇（decisionFor）、套用能力成長（applyGains），
// 以及一天／一週的完整結算（startDay → resolveDay → 過勞就 hospitalize，或跑滿七天由 finishWeek 收尾）。
// 這裡是除了 logic/agency.js／logic/jobs.js 之外，唯一會依遊戲規則直接改寫 state 數值的地方。
import{ACTIONS}from"../data/actions.js";
import{JOB}from"../data/job.js";
import{AGENCIES}from"../data/agencies.js";
import{MAP_LOCATIONS}from"../data/map-locations.js";
import{DAYS}from"../data/calendar.js";
import{state}from"../core/state.js";
import{random,money,effectiveStat,successRateLabel,jobWorkDaysText}from"../core/utils.js";
import{deterministicInterviewScore,calculateJobIncome,cancelAgencyInterview,isAgencyContractActive}from"./agency.js";
import{resolveExploration}from"./exploration.js";
import{render}from"../render.js";

// 依當天安排的行程，決定要不要跳出「現場選擇」；回傳 null 代表當天沒有選擇，直接照 resolveDay 的預設分支結算。
export function decisionFor(id){if(id==="agency_interview"&&state.agencyInterview){const agency=AGENCIES[state.agencyInterview.agencyId];return{title:`${agency.name}面談`,text:"人資窗口準備好聽你聊聊自己，你打算怎麼呈現這次機會？",choices:[{id:"steady",label:"穩健回答：說明訓練與職涯規劃",note:`偏向口才、親和力與自律・${successRateLabel(deterministicInterviewScore(agency,"steady"))}`},{id:"bold",label:"展現企圖心：談論想爭取的舞台",note:`偏向膽識、野心與鏡頭感・${successRateLabel(deterministicInterviewScore(agency,"bold"))}`}]}}if(id==="free"){const locationId=state.freeLocations[state.runnerDay],l=MAP_LOCATIONS[locationId];if(l)return{title:`抵達${l.name}`,text:l.note,choices:[{id:"explore",label:"四處走走，主動探索",note:"提高遇見人物或事件的機會"},{id:"focus",label:"專注體驗這個地點",note:"較容易獲得能力或狀態成長"}]}}if(id==="audition")return{title:"導演臨時更換了台詞",text:"輪到你試鏡前，現場突然要求即興。你打算怎麼應對？",choices:[{id:"safe",label:"照原本準備穩穩演",note:"成功率較高，成果穩定"},{id:"bold",label:"順勢加入自己的設計",note:"風險較高，大成功時曝光更多"}]};if(id==="free")return{title:"午後還沒有安排",text:"星望市今天很熱鬧，你想把空閒時間花在哪裡？",choices:[{id:"radio",label:"去廣播電臺附近逛逛",note:"可能遇見業界人物"},{id:"livehouse",label:"鑽進巷子裡的 Live House",note:"可能獲得靈感與舞台經驗"}]};if(id==="street")return{title:"街頭的人比預期更多",text:"你選好位置，卻發現路人來去匆匆。要怎麼抓住注意力？",choices:[{id:"steady",label:"唱最熟悉的歌",note:"穩定演出，成功率較高"},{id:"interact",label:"主動邀請路人點歌",note:"考驗社交，收益波動更大"}]};return null}

export function applyGains(gains){const out=[];gains.forEach(([n,min,max])=>{let gain=random(min,max)+(state.focus==="growth"?1:0);state.stats[n]=Math.min(1000,state.stats[n]+gain);out.push(`<b>${n}＋${gain}</b>`)});return out.join("、")}

// 每天開始時呼叫：先顯示 loading，0.65 秒後依 decisionFor 決定要不要停在「選擇」畫面，沒有選擇就直接結算。
export function startDay(){state.runnerResult=null;state.runnerDecision=null;state.runnerPhase="loading";render();setTimeout(()=>{const d=decisionFor(state.schedule[state.runnerDay]);if(d){state.runnerDecision=d;state.runnerPhase="decision";render()}else resolveDay(null)},650)}

// 結算當天：依行程類型（訓練／休息／自由活動／通告拍攝／經紀公司面談／試鏡與街頭演出）各自計算結果，
// 最後統一寫入 weekResults、檢查過勞（>200 直接進結局、>100 強制住院），否則進入「結果」畫面。
export function resolveDay(choice){const id=state.schedule[state.runnerDay],a=ACTIONS[id];let title="成功！",text="",success=true;state.money-=a.cost;
 if(a.type==="train"){text=`課程順利結束，${applyGains(a.gains)}。學費 <b>－${money(a.cost)}</b>。`;state.stamina=Math.max(0,state.stamina-a.stamina);state.fatigue+=a.fatigue;state.trainingSessionsCompleted=(state.trainingSessionsCompleted||0)+1}
 else if(id==="rest"){title="好好休息！";const reduced=Math.min(state.fatigue,18);state.fatigue-=reduced;state.stamina=Math.min(100,state.stamina+24);state.mood=Math.min(100,state.mood+3);text=`體力 <b>＋24</b>、疲勞 <b>－${reduced}</b>。專業躺平也是職涯管理。`}
 else if(id==="free"){const loc=state.freeLocations[state.runnerDay]||"park";text=resolveExploration(loc,choice)}
 else if(id==="free"){state.fatigue+=3;state.stamina=Math.max(0,state.stamina-4);const loc=state.freeLocations[state.runnerDay]||"park";state.lastVisitedLocation=loc;state.lastVisitedWeek=state.week;if(loc==="radio"){if(choice==="explore"&&!state.knownPeople.includes("jiqing")){const familiar=state.familiarNpcs.includes("jiqing");state.knownPeople.push("jiqing");state.selectedNpc="jiqing";state.relationships.jiqing={closeness:familiar?18:8,trust:familiar?22:12,romance:"none"};state.contract+=4;text=familiar?"你一靠近就覺得眼熟——原來是<b>紀晴</b>，她似乎也對你有點印象，很快就聊開了。簽約進度 <b>＋4%</b>。":"你幫忙撿回散落的訪綱，第一次認識主持人<b>紀晴</b>。簽約進度 <b>＋4%</b>。";state.flags.push({week:state.week,label:"第一次認識紀晴",note:familiar?"雖是新的一輪，卻對彼此有眼熟印象，很快破冰。":"撿回散落的訪綱，建立初次印象。"})}else{const g=random(2,5);state.stats.口才+=g;text=`你在電臺旁觀摩錄影，<b>口才＋${g}</b>。`}}else if(loc==="livehouse"){const g=random(3,7);state.stats.靈感+=g;state.stats.歌藝+=2;text=`你看了一場新人演出，<b>靈感＋${g}、歌藝＋2</b>。`}else if(loc==="park"){const reduced=Math.min(state.fatigue,8);state.fatigue-=reduced;state.mood=Math.min(100,state.mood+5);text=`河邊散步讓妳喘了口氣，<b>疲勞－${reduced}、心情＋5</b>。`}else if(loc==="shop"){const g=random(3,6);state.stats.時尚+=g;text=`你在商場逛了一圈，眼光被訓練得更敏銳，<b>時尚＋${g}</b>。`}else if(loc==="beauty"){const g=random(3,6);state.stats.外貌+=g;text=`造型師幫你重新整理了造型，<b>外貌＋${g}</b>。`}else if(loc==="clinic"){const g=random(2,5);state.stats.外貌+=g;text=`你在整形外科諮詢了保養與調整方案，<b>外貌＋${g}</b>。這裡也承接變性手術，想動刀的話可以到衣櫃裡辦理。`}else if(loc==="cinema"){const g=random(3,6);state.stats.靈感+=g;text=`看完一部電影，腦中冒出不少畫面，<b>靈感＋${g}</b>。`}else{const g=random(2,5);state.stats.口才+=g;text=`你四處走走，累積了一些經驗，<b>口才＋${g}</b>。`}}
 else if(id==="adshoot"){if(state.jobStage!=="active"){title="通告已不在執行中";success=false;text="這份行程不再有效，今天不會重複計算報酬或完成次數。"}else if(!JOB.workDays.includes(state.runnerDay)){title="今天無法執行通告";success=false;text=`合約指定工作日為每週${jobWorkDaysText()}，今天不能計入完成次數。`}else{state.fatigue+=a.fatigue;state.stamina=Math.max(0,state.stamina-a.stamina);state.jobRemaining=Math.max(0,state.jobRemaining-1);const g=random(3,6);state.stats.鏡頭感=Math.min(1000,state.stats.鏡頭感+g);if(state.jobRemaining===0){state.jobStage="completed";state.schedule=state.schedule.map((scheduled,idx)=>idx>state.runnerDay&&scheduled==="adshoot"?"rest":scheduled);const income=calculateJobIncome(JOB.pay);state.money+=income.net;state.fame+=18;state.fans+=120;text=`完成最後一次拍攝！<b>鏡頭感＋${g}</b>。通告總額 <b>${money(income.gross)}</b>，公司抽成 <b>－${money(income.commission)}</b>，實領 <b>＋${money(income.net)}</b>、知名度＋18、粉絲＋120。`}else{text=`完成一階段拍攝，<b>鏡頭感＋${g}</b>。合約還剩 <b>${state.jobRemaining} 次</b>工作。`}}}
 else if(id==="agency_interview"){const active=state.agencyInterview,activeApp=active&&state.agencyApplications[active.agencyId];const valid=active&&active.dayIndex===state.runnerDay&&activeApp&&activeApp.status==="interview_scheduled";if(!valid){title="面談已取消或失效";success=false;text="這場面談目前已不存在，今天不會產生任何結果，也不會重複計算。"}else{const agency=AGENCIES[active.agencyId];state.fatigue+=a.fatigue;state.stamina=Math.max(0,state.stamina-a.stamina);const score=deterministicInterviewScore(agency,choice);success=random(1,100)<=score;const bumpStat=choice==="steady"?"口才":"鏡頭感";if(success){const gain=random(4,8);state.stats[bumpStat]=Math.min(1000,state.stats[bumpStat]+gain);state.contract=Math.min(100,state.contract+8);activeApp.status="offer";state.agencyOffer={agencyId:agency.id,offeredWeek:state.week};title="面談順利，公司決定發出合約！";text=`你以${choice==="steady"?"穩健":"積極"}的方式應對問題，對方相當滿意。<b>${bumpStat}＋${gain}、簽約準備度＋8%</b>。回到經紀公司頁即可查看正式合約。`;state.flags.push({week:state.week,label:`${agency.name}面談通過`,note:`以${choice==="steady"?"穩健":"企圖心"}回答獲得合約邀約。`})}else{const gain=random(1,3);state.stats[bumpStat]=Math.min(1000,state.stats[bumpStat]+gain);activeApp.status="rejected";title="這次沒有獲得錄取通知";text=`公司婉拒了這次機會，不過臨場經驗仍有收穫，<b>${bumpStat}＋${gain}</b>。`;state.flags.push({week:state.week,label:`${agency.name}面談未獲錄取`,note:`以${choice==="steady"?"穩健":"企圖心"}回答應對，這次沒有成功。`})}state.schedule[state.runnerDay]="rest";state.agencyInterview=null}}
 else if(a.gains){text=`自主安排留下成果，${applyGains(a.gains)}。`;state.fatigue+=a.fatigue;state.stamina=Math.max(0,state.stamina-a.stamina)}
 else{state.fatigue+=a.fatigue;state.stamina=Math.max(0,state.stamina-a.stamina);let power=id==="audition"?(effectiveStat("鏡頭感")+effectiveStat("親和力")+effectiveStat("口才"))/3:(effectiveStat("歌藝")+effectiveStat("肢體表現")+effectiveStat("社交"))/3;let chance=Math.max(10,Math.min(78,32+(power-75)*.24+(state.focus==="fame"?8:0)+(choice==="safe"||choice==="steady"?10:-4)));if(Math.random()*100<chance){if(id==="audition"){const f=choice==="bold"?8:4,g=random(5,9);state.stats.鏡頭感+=g;state.fame+=f+(state.focus==="fame"?2:0);state.fans+=random(15,55);state.contract+=choice==="bold"?18:13;text=`導演請你留下資料。<b>鏡頭感＋${g}、知名度＋${f}、簽約進度＋${choice==="bold"?18:13}%</b>。`}else{const earn=choice==="interact"?random(900,1800):random(500,1100);state.money+=earn;state.fame+=2+(state.focus==="fame"?2:0);state.fans+=random(8,35);text=`有人停下來替你鼓掌。小費 <b>＋${money(earn)}</b>，知名度與粉絲也增加了。`}}else{title="這次沒有成功";success=false;const n=id==="audition"?"鏡頭感":"歌藝",g=random(1,3);state.stats[n]+=g;text=`機會擦身而過，但實戰沒有白費，<b>${n}＋${g}</b>。`}}
 state.contract=Math.min(100,state.contract);state.weekResults.push({day:DAYS[state.runnerDay],action:a.label,result:(title+" "+text.replace(/<[^>]+>/g,"")),success});
 if(state.fatigue>200){state.endingType="death";state.screen="ending";state.appOpen=null;render();return}
 if(state.fatigue>100){hospitalize();return}
 state.runnerPhase="result";state.runnerResult={title,text,success};render()}

// 過勞（疲勞 >100）強制住院：取消當週剩餘行程與可能存在的面談，直接進入本週結算畫面。
export function hospitalize(){const at=state.fatigue;const hadInterview=!!state.agencyInterview;if(hadInterview)cancelAgencyInterview("面談因住院取消，可以重新安排。");state.hospitalSkipWeeks=1;state.fatigue=Math.max(0,state.fatigue-90);state.stamina=100;state.mood=Math.max(0,state.mood-5);state.flags.push({week:state.week,label:"強制住院一週",note:`疲勞升至 ${at}，健康崩潰；本週剩餘行程取消，下一週完整住院休養。${hadInterview?"原訂的經紀公司面談已取消，之後可重新安排。":""}`});state.reward={title:"健康亮起紅燈，強制住院一週",text:`疲勞升至 ${at}，超過負荷。本週剩餘行程已取消，接下來一週將無法排行程。${hadInterview?"原訂的經紀公司面談已取消，之後可以重新安排。":""}`};state.history.push({week:state.week,results:[...state.weekResults],reward:false,hospitalized:true});state.screen="summary";state.appOpen=null;render()}

// 七天跑完後的週結算：依「訓練 2 天＋工作 1 次＋疲勞 ≤60」判斷任務是否達成，發放對應獎勵（簽約中則改發公司任務獎勵）。
export function finishWeek(){const train=state.schedule.filter(id=>ACTIONS[id].type==="train").length,work=state.schedule.filter(id=>["work","job"].includes(ACTIONS[id].type)).length,done=train>=2&&work>=1&&state.fatigue<=60;if(isAgencyContractActive()){state.reward=done?{title:"本週任務完成！",text:"公司對妳這週的表現感到滿意。獲得 $2,000，業界評價＋2。"}:{title:"本週任務未完成",text:"訓練、工作或疲勞條件沒有同時達成，下週還能再挑戰。"};if(done){state.money+=2000;state.rep.業界評價=(state.rep.業界評價||0)+2}}else{state.reward=done?{title:"本週任務完成！",text:"妳的準備度受到注意。獲得 $1,500，簽約進度＋10%。"}:{title:"本週任務未完成",text:"訓練、工作或疲勞條件沒有同時達成，下週還能再挑戰。"};if(done){state.money+=1500;state.contract=Math.min(100,state.contract+10)}}state.history.push({week:state.week,results:[...state.weekResults],reward:done});state.screen="summary";render()}
