import{state}from"../core/state.js";
import{enqueueVisibleEvent}from"./event-engine.js";
const TYPES={breach:{label:"違約風波",baseWeeks:8},misstatement:{label:"失言爭議",baseWeeks:6},rumor:{label:"緋聞傳聞",baseWeeks:7},conduct:{label:"私德爭議",baseWeeks:12},generic:{label:"輿論危機",baseWeeks:8}};
export function activeScandal(){return(state.scandals||[]).find(s=>s.status==="active")||null}
export function recordScandal(type="generic",severity=1,source="外界輿論"){state.scandals??=[];const def=TYPES[type]||TYPES.generic,current=activeScandal();if(current){current.severity=Math.min(5,current.severity+severity);current.recoveryWeeks=Math.max(current.recoveryWeeks,def.baseWeeks+severity*2);current.sources.push({week:state.week,source});return current}const scandal={id:`SC-${state.week}-${state.scandals.length}`,type:TYPES[type]?type:"generic",label:def.label,severity:Math.max(1,Math.min(5,severity)),startedWeek:state.week,recoveryWeeks:def.baseWeeks+severity*2,progress:0,status:"active",sources:[{week:state.week,source}],response:null,responseWeek:null,echoes:[]};state.scandals.unshift(scandal);state.flags.push({week:state.week,label:`醜聞：${def.label}`,note:source});return scandal}
export function respondToScandal(id,response){const s=(state.scandals||[]).find(x=>x.id===id&&x.status==="active");if(!s)return false;s.response=response;s.responseWeek=state.week;if(response==="apologize"){s.progress+=3;state.rep.可信度=Math.min(1000,(state.rep.可信度||0)+18);state.rep.爭議度=Math.max(0,(state.rep.爭議度||0)-20)}else if(response==="silence"){s.progress+=1;state.rep.話題度=Math.max(0,(state.rep.話題度||0)-10)}else if(response==="deny"){s.progress+=2;state.rep.可信度=Math.min(1000,(state.rep.可信度||0)+6);s.denyRisk=true}else if(response==="vague"){s.progress+=1;state.rep.話題度=Math.min(1000,(state.rep.話題度||0)+5);s.recoveryWeeks+=2}else if(response==="publicLove"){s.progress+=2;state.rep.話題度=Math.min(1000,(state.rep.話題度||0)+18);state.rep.爭議度=Math.max(0,(state.rep.爭議度||0)-8);if(state.partnerId&&state.relationships?.[state.partnerId])state.relationships[state.partnerId].visibility="public"}return true}
function ensureResponseEvent(s){const id=`scandal-choice:${s.id}`;if(s.response||state.eventQueue.some(x=>x.event?.id===id)||state.eventHistory.some(x=>x.id===id))return;const choices=[{id:"apologize",label:"正式說明並承擔責任",note:"可信度回升較快，短期聲量下降",outcome:"你選擇先處理受影響的人與合作方，而不是搶回熱搜。",effect:{flag:`scandal-response:${s.id}:apologize`}},{id:"silence",label:"暫不回應，等待退燒",note:"避免再添新話題，但空白會被別人解讀",outcome:"你沒有再增加新的句子，輿論慢慢冷卻。",effect:{flag:`scandal-response:${s.id}:silence`}},{id:"deny",label:"明確否認",note:"短期止血快；若後續出現反證，代價更大",outcome:"你的立場非常清楚，現在外界只剩下相信或不相信。",effect:{flag:`scandal-response:${s.id}:deny`}},{id:"vague",label:"模糊處理",note:"保留空間，但猜測會拖更久",outcome:"聲明沒有把門關死，也沒有真的結束討論。",effect:{flag:`scandal-response:${s.id}:vague`}}];if(s.type==="rumor"&&state.partnerId)choices.push({id:"publicLove",label:"直接公開關係",note:"把緋聞變成正式戀情事件，品牌與粉絲會立刻回應",outcome:"你沒有再把對方藏在『只是朋友』後面。",effect:{flag:`scandal-response:${s.id}:publicLove`}});enqueueVisibleEvent({id,kind:"醜聞",title:`公關危機｜${s.label}`,text:`這次${s.label}已經不只是單日熱搜。經紀人、品牌與合作方都在等你的正式態度；這個選擇會在接下來幾週反覆被提起。`,choices},"醜聞")}
export function syncScandalResponseFlags(){const s=activeScandal();if(!s||s.response)return;for(const r of["apologize","silence","deny","vague","publicLove"])if(state.eventFlags.includes(`scandal-response:${s.id}:${r}`)){respondToScandal(s.id,r);break}}
function queueScandalEcho(s){if(!s.response||!s.responseWeek)return null;const age=state.week-s.responseWeek,key=`${s.id}:${age}`;if(s.echoes.includes(key))return null;let echo=null;if(age===1){echo={id:`scandal-echo-1:${s.id}`,kind:"輿論事件",title:"聲明後的第一週",text:s.response==="silence"?"你沒有說話，但節目主持人、論壇與品牌窗口都在解讀這份沉默。":s.response==="publicLove"?"緋聞被改寫成公開關係，祝福、質疑與品牌詢問同時湧進來。":"你的正式態度已經變成這場風波的新焦點。"}}else if(age===3){echo={id:`scandal-echo-3:${s.id}`,kind:"輿論事件",title:"風波開始留下職涯後果",text:s.response==="deny"&&s.denyRisk?"媒體開始重新整理時間線；如果之後出現矛盾證據，這次否認會比原始新聞更傷可信度。":"話題熱度下降，但合作方已經把你的危機處理方式記進下一次評估。"}}if(echo){s.echoes.push(key);enqueueVisibleEvent(echo,"醜聞後續")}return echo}
export function tickScandals(){state.scandals??=[];syncScandalResponseFlags();let s=activeScandal();if(!s&&state.publicOpinion?.state==="scandal")s=recordScandal("generic",Math.max(2,state.publicOpinion.scandalLevel||2),"高強度輿論炎上");if(!s)return null;ensureResponseEvent(s);queueScandalEcho(s);const trust=state.rep.可信度??500,controversy=state.rep.爭議度||0,base=1+(trust>=600?1:0)+(controversy<300?1:0)+(s.response==="apologize"?1:0)-(s.response==="vague"?1:0);s.progress+=Math.max(0,base);if(s.progress>=s.recoveryWeeks&&controversy<450){s.status="recovered";s.recoveredWeek=state.week;state.flags.push({week:state.week,label:`危機解除：${s.label}`,note:`歷經 ${state.week-s.startedWeek+1} 週後，外界焦點逐漸離開這場風波。`});state.rep.可信度=Math.min(1000,(state.rep.可信度||0)+8)}return s}
export function scandalMarketPenalty(){const s=activeScandal();return s?-Math.min(30,s.severity*6):0}
