import{state}from"../core/state.js";
import{enqueueVisibleEvent}from"./event-engine.js";
const TYPES={breach:{label:"違約風波",baseWeeks:8},misstatement:{label:"失言爭議",baseWeeks:6},rumor:{label:"緋聞傳聞",baseWeeks:7},conduct:{label:"私德爭議",baseWeeks:12},generic:{label:"輿論危機",baseWeeks:8}};
export function activeScandal(){return(state.scandals||[]).find(s=>s.status==="active")||null}
export function recordScandal(type="generic",severity=1,source="外界輿論"){state.scandals??=[];const def=TYPES[type]||TYPES.generic,current=activeScandal();if(current){current.severity=Math.min(5,current.severity+severity);current.recoveryWeeks=Math.max(current.recoveryWeeks,def.baseWeeks+severity*2);current.sources.push({week:state.week,source});return current}const scandal={id:`SC-${state.week}-${state.scandals.length}`,type:TYPES[type]?type:"generic",label:def.label,severity:Math.max(1,Math.min(5,severity)),startedWeek:state.week,recoveryWeeks:def.baseWeeks+severity*2,progress:0,status:"active",sources:[{week:state.week,source}],response:null};state.scandals.unshift(scandal);state.flags.push({week:state.week,label:`醜聞：${def.label}`,note:source});return scandal}
export function respondToScandal(id,response){const s=(state.scandals||[]).find(x=>x.id===id&&x.status==="active");if(!s)return false;s.response=response;if(response==="apologize"){s.progress+=3;state.rep.可信度=Math.min(1000,(state.rep.可信度||0)+18);state.rep.爭議度=Math.max(0,(state.rep.爭議度||0)-20)}else if(response==="silence"){s.progress+=1;state.rep.話題度=Math.max(0,(state.rep.話題度||0)-10)}else if(response==="fight"){s.progress=Math.max(0,s.progress-1);state.rep.話題度=Math.min(1000,(state.rep.話題度||0)+16);state.rep.爭議度=Math.min(1000,(state.rep.爭議度||0)+12);state.fans+=Math.max(3,Math.round(state.fame/8))}return true}
function ensureResponseEvent(s){const id=`scandal-choice:${s.id}`;if(s.response||state.eventQueue.some(x=>x.event?.id===id)||state.eventHistory.some(x=>x.id===id))return;enqueueVisibleEvent({id,kind:"選擇事件",title:`公關危機｜${s.label}`,text:`這次${s.label}已經不只是單日熱搜。經紀與合作方都在等你的正式態度，處理方式會影響後續復原速度。`,choices:[{id:"apologize",label:"正式說明並承擔責任",outcome:"你選擇降低火勢，短期聲量下滑，但可信度開始回升。",effect:{flag:`scandal-response:${s.id}:apologize`}},{id:"silence",label:"暫停回應，等待退燒",outcome:"話題慢慢冷卻，但外界仍會觀察你接下來的行動。",effect:{flag:`scandal-response:${s.id}:silence`}},{id:"fight",label:"強硬反擊",outcome:"支持者更團結，但爭議也被重新推上檯面。",effect:{flag:`scandal-response:${s.id}:fight`}}]},"醜聞")}
export function syncScandalResponseFlags(){const s=activeScandal();if(!s||s.response)return;for(const r of["apologize","silence","fight"])if(state.eventFlags.includes(`scandal-response:${s.id}:${r}`)){respondToScandal(s.id,r);break}}
export function tickScandals(){state.scandals??=[];syncScandalResponseFlags();let s=activeScandal();if(!s&&state.publicOpinion?.state==="scandal")s=recordScandal("generic",Math.max(2,state.publicOpinion.scandalLevel||2),"高強度輿論炎上");if(!s)return null;ensureResponseEvent(s);const trust=state.rep.可信度??500,controversy=state.rep.爭議度||0,base=1+(trust>=600?1:0)+(controversy<300?1:0)+(s.response==="apologize"?1:0)-(s.response==="fight"?1:0);s.progress+=Math.max(0,base);if(s.progress>=s.recoveryWeeks&&controversy<450){s.status="recovered";s.recoveredWeek=state.week;state.flags.push({week:state.week,label:`危機解除：${s.label}`,note:`歷經 ${state.week-s.startedWeek+1} 週後，外界焦點逐漸離開這場風波。`});state.rep.可信度=Math.min(1000,(state.rep.可信度||0)+8)}return s}
export function scandalMarketPenalty(){const s=activeScandal();return s?-Math.min(30,s.severity*6):0}
