import{state}from"../core/state.js";
import{checkAgencyContractExpiry}from"./agency.js";
import{refreshAgencyJobOffers}from"./agency-offers.js";
import{checkJobDeadlines}from"./job-engine.js";
import{recordCareerRoute}from"./career.js";
import{processQueuedEvents}from"./event-engine.js";
import{resolveDueAwardSeasons}from"./portfolio.js";
import{enqueueCalendarEvents}from"./calendar-events.js";
import{tickNpcCareers}from"./npc-ecosystem.js";
import{syncNpcAutonomousWork,cleanupNpcAutonomousSchedules}from"./npc-autonomy.js";
import{tickNpcRelationshipDynamics}from"./npc-dynamics.js";
import{cleanupActivities}from"./scheduled-activities.js";
import{generateIndustryNews}from"./industry-news.js";
import{queueNpcStoryEvents}from"./npc-storylines.js";
import{tickPublicOpinion}from"./reputation-engine.js";
import{tickBrandRelations}from"./brand-relations.js";
import{tickScandals,syncScandalResponseFlags}from"./scandal-engine.js";
import{tickRumors}from"./rumor-engine.js";
import{tickManager}from"./manager.js";
import{tickWorldMarket}from"./world-market.js";
import{evaluatePersona}from"./persona-engine.js";
import{tickCompetitors}from"./competitors.js";
import{tickWorkLifecycles}from"./work-lifecycle.js";
import{syncFandom}from"./fandom.js";
import{tickNpcProactiveEvents}from"./npc-proactive.js";
import{maybeQueueMediaEvent}from"./media-engine.js";
import{tickSequelOpportunities}from"./sequel-engine.js";
import{queueAnnualWorldEvent}from"./world-events.js";

export function advanceWorldWeek(){
 const closingNews=generateIndustryNews();
 tickPublicOpinion(closingNews);
 syncScandalResponseFlags();
 if(state.hospitalSkipWeeks)state.history.push({week:state.week+1,results:[],reward:false,hospitalized:true,fullRecovery:true});
 state.week+=1+state.hospitalSkipWeeks;
 state.hospitalSkipWeeks=0;
 cleanupActivities();
 cleanupNpcAutonomousSchedules();
 checkAgencyContractExpiry();
 const breached=checkJobDeadlines();
 const awards=resolveDueAwardSeasons();
 const market=tickWorldMarket();
 const rivalUpdates=tickCompetitors();
 const workUpdates=tickWorkLifecycles();
 const npcGrowth=tickNpcCareers();
 const npcWork=syncNpcAutonomousWork();
 const npcRelationUpdates=tickNpcRelationshipDynamics();
 const rumorUpdates=tickRumors();
 const npcUpdates=[...npcWork,...npcGrowth,...npcRelationUpdates,...rumorUpdates,...rivalUpdates,...workUpdates];
 const news=generateIndustryNews({awards,npcUpdates});
 const opinion=tickPublicOpinion(news);
 tickBrandRelations();
 const scandal=tickScandals();
 tickManager();
 refreshAgencyJobOffers();
 recordCareerRoute();
 const persona=evaluatePersona();
 const fandom=syncFandom();
 const due=processQueuedEvents();
 const calendar=enqueueCalendarEvents();
 const npcStories=queueNpcStoryEvents();
 const proactive=tickNpcProactiveEvents();
 const media=maybeQueueMediaEvent();
 const sequel=tickSequelOpportunities();
 const worldEvent=queueAnnualWorldEvent();
 return{breached,awards,market,npcUpdates,rumorUpdates,news,opinion,scandal,persona,fandom,due,calendar,npcStories,proactive,media,sequel,worldEvent};
}
