export function migrateV1ToV2(state){const next=structuredClone(state);if(!Array.isArray(next.freeLocations)&&Array.isArray(next.schedule))next.freeLocations=next.schedule.map(id=>id==="free"?(next.mapLocation||null):null);return next}
export function migrateV2ToV3(state){const next=structuredClone(state);if(!next.activeJobs&&next.jobStage&&next.jobStage!=="available")next.activeJobs={J001:{jobId:"J001",stage:next.jobStage,appliedWeek:1,deadlineWeek:next.jobDeadline||3,remainingSessions:next.jobRemaining??3}};next.activeJobs||={};return next}
export function migrateV3ToV4(state){const next=structuredClone(state);Object.assign(next,{saveVersion:4,eventQueue:Array.isArray(next.eventQueue)?next.eventQueue:[],activeEvent:next.activeEvent||null,health:Number.isFinite(next.health)?next.health:100,overworkStrikes:Number.isInteger(next.overworkStrikes)?next.overworkStrikes:0,awardSeasons:next.awardSeasons&&typeof next.awardSeasons==="object"?next.awardSeasons:{},careerRouteHistory:Array.isArray(next.careerRouteHistory)?next.careerRouteHistory:[],rngSeed:Number.isInteger(next.rngSeed)?next.rngSeed:(Date.now()>>>0),rngCursor:Number.isInteger(next.rngCursor)?next.rngCursor:0});return next}
export function migrateV4ToV5(state){const next=structuredClone(state);Object.assign(next,{saveVersion:5,npcCareers:next.npcCareers&&typeof next.npcCareers==="object"?next.npcCareers:{},npcCareerHistory:Array.isArray(next.npcCareerHistory)?next.npcCareerHistory:[],npcInteractionsByWeek:next.npcInteractionsByWeek&&typeof next.npcInteractionsByWeek==="object"?next.npcInteractionsByWeek:{},npcSocialRelations:next.npcSocialRelations&&typeof next.npcSocialRelations==="object"?next.npcSocialRelations:{}});return next}
export function migrateV5ToV6(state){const next=structuredClone(state);next.saveVersion=6;next.npcSchedules=next.npcSchedules&&typeof next.npcSchedules==="object"?next.npcSchedules:{};return next}
export function migrateV6ToV7(state){const next=structuredClone(state);Object.assign(next,{saveVersion:7,birthMonth:Number(next.birthMonth)||8,birthDay:Number(next.birthDay)||1,scheduledActivityIds:Array.isArray(next.scheduledActivityIds)&&next.scheduledActivityIds.length===7?next.scheduledActivityIds:Array(7).fill(null),lastScheduledActivityIds:Array.isArray(next.lastScheduledActivityIds)?next.lastScheduledActivityIds:null,scheduledActivities:next.scheduledActivities&&typeof next.scheduledActivities==="object"?next.scheduledActivities:{},agencyJobOffers:Array.isArray(next.agencyJobOffers)?next.agencyJobOffers:[]});return next}
export function migrateV7ToV8(state){const next=structuredClone(state);Object.assign(next,{saveVersion:8,industryNews:Array.isArray(next.industryNews)?next.industryNews:[],npcStoryHistory:Array.isArray(next.npcStoryHistory)?next.npcStoryHistory:[]});for(const p of next.creativeProjects||[]){p.productionProgress=Number(p.productionProgress)||0;p.productionSessions=Number(p.productionSessions)||0;p.releaseWeek=p.releaseWeek||null;p.marketScore=Number(p.marketScore)||0;p.revenue=Number(p.revenue)||0}return next}
export function migrateV8ToV9(state){const next=structuredClone(state);Object.assign(next,{saveVersion:9,publicOpinion:next.publicOpinion&&typeof next.publicOpinion==="object"?next.publicOpinion:{state:"neutral",score:0,brandTrust:50,heat:0,scandalLevel:0,lastChangedWeek:0},publicOpinionHistory:Array.isArray(next.publicOpinionHistory)?next.publicOpinionHistory:[]});for(const p of next.creativeProjects||[]){p.team=Array.isArray(p.team)?p.team:[];p.selfParticipation=p.selfParticipation??true}return next}
export function migrateSaveState(state,version){let next=structuredClone(state),v=version;if(v<2){next=migrateV1ToV2(next);v=2}if(v<3){next=migrateV2ToV3(next);v=3}if(v<4){next=migrateV3ToV4(next);v=4}if(v<5){next=migrateV4ToV5(next);v=5}if(v<6){next=migrateV5ToV6(next);v=6}if(v<7){next=migrateV6ToV7(next);v=7}if(v<8){next=migrateV7ToV8(next);v=8}if(v<9){next=migrateV8ToV9(next);v=9}return{version:v,state:next}}
